### ISSUE TITLE
`valid()` should return `false` if any pending validations

### ISSUE THREAD

**Issue by jzaefferer** [jquery-validation/jquery-validation#1045]
When the `remote` method is called as part of invoking `valid()`, the result should be `false` if there's any validation still pending. Probably...

See also #1044

**Comment by NotionCommotion** [comment]
According to http://stackoverflow.com/questions/2510623/jquery-validation-plugin-valid-does-not-work-with-remote-validation/3884995#3884995, element used to return undefined while the asynchronous call is running.  Is this an option?  Ideally, the response would be asynchronous and wait for the reply.

**Comment by leandromatos** [comment]
Any solution?

**Comment by leandromatos** [comment]
The error continues... any solution?

**Comment by suclogger** [comment]
Encounter the same error,any bypassing method?

**Comment by davidplappert** [comment]
Just wondering if there was any movement on this issue?

**Comment by heldersepu** [comment]
I got the same error, there seems to be a workaround using
` .removeData("previousValue");`

http://stackoverflow.com/questions/2710548/how-to-use-jquery-to-remotely-validate-a-field-that-depends-on-another-field-in

http://stackoverflow.com/questions/1433139/with-jquery-validation-plugin-i-want-to-change-the-remote-validation-method

**Comment by jarfer** [comment]
Hi - can we re-open this please? This is still an issue (for me)

Basically, calling either/both .valid(...) and .element(...) always returns true, regardless of the state of the input itself.

So I would suggest either removing from the documentation here: https://jqueryvalidation.org/Validator.element/

Or fixing this method so it actually does the thing documented.

**Comment by staabm** [comment]
@jarfer feel free to provide either a patch for the docs which mentions the exeption for the „remote“ validation or a fix for the library

**Comment by molihub** [comment]
As I wrote in issue #956 remote validation causes double submit, I found a solution like below can avoid this issue temporary.
```
theForm.on("submit", function(e) {
    if (!theForm.valid() || theForm.find("input." + this.validator.pendingClass).length) {
         // attention: I have this.validator in my code.
         return false;
    }

    // ...
}
```

**Comment by burakt91** [comment]
I wonder are there any updates on this issue? Still the form.valid() returns true even though the form has a pending remote validation and submit handler running twice. The codesandbox.io demo is [here](https://codesandbox.io/s/jquery-validation-double-submit-prqnd?file=/index.html) (see the console window after clicked submit).
