### ISSUE TITLE
Select tag with rangelength rule problem

### ISSUE THREAD

**Issue by tyther9** [jquery-validation/jquery-validation#107]
Using version 1.8.1:

When using the rangelength rule to enforce that the selected value of a dropdown is (in my case a length of 2) a certain length,  the rule reports that an error condition exists when in fact it does not. The error seems to occur within the following lines in particular the line marked with **:

``` js
getLength: function(value, element) {
     switch( element.nodeName.toLowerCase() ) {
    case 'select':
        ** return $("option:selected", element).length;
    case 'input':
        if( this.checkable( element) )
            return this.findByName(element.name).filter(':checked').length;
        }

    return value.length;
}
```

It does not return the length of the selected value. I was unable to determine what length it is returning.

**Comment by MarquitosPT** [comment]
This function continues with error when validating "select" element

`case "select":
                if (element.multiple)
                    return $("option:selected", element).length;`

it should be at least:

`case "select":
                if (element.multiple)
                    return $("option:selected", element).val().length;`
