### ISSUE TITLE
setDefaults not working + suggested solution

### ISSUE THREAD

**Issue by bresleveloper** [jquery-validation/jquery-validation#1184]
hi
the jQuery.validator.setDefaults({...}) is not working and not updating the settings.
i've suggested a fix here
http://stackoverflow.com/questions/11612939/invalidhandler-setdefault-ignored-in-validator-call-jquery-validation-plugin/24369083#24369083

**Comment by jcperez2405** [comment]
I have the same problem.

__Details:__
jQuery v1.11.3
jQuery validator v1.13.1

```javascript
//main.js ----
$.validator.setDefaults({
 //options including 'rules', etc.
})
// -----------
```
```javascript
//manager.js ----
$('form').validate()
// -----------
```
But no apply the default settings!

__Additional information:__
1. jQuery validator is loaded before main.js
2. main.js is loaded before manager.js

Thanks in advance for any solution.

**Comment by jzaefferer** [comment]
Please provide an actual testpage that shows the problem. Code snippets are insufficient. Also, commenting on closed tickets is generally a bad strategy.

**Comment by mansoor-omrani** [comment]
I noticed the same issue with jQuery 1.9.1. (setDefaults() not working properly).

**Comment by RouR** [comment]
Same problem jQuery 2.2.3 + jQuery-Validation 1.15.0 + jQuery.validate.unobtrusive.js

**Comment by RouR** [comment]
https://jsfiddle.net/3uznxttf/5/

**Comment by mrojas18** [comment]
i have the same error,but a solved just calling first jquery and then jquery validator... its weard, but its works. 

<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.validate.js"></script>

**Comment by murraycollingwood** [comment]
Same problem jQuery 2.2.3 + jQuery-Validation 1.17.0
See RouR's page above - I just changed the jQuery library to 1.17.0 and it still fails to highlight/unhighlight.

**Comment by staabm** [comment]
I did not check it further, but as 2 people report the same error we should investigate...

**Comment by murraycollingwood** [comment]
Just an update - I had a colleague add the code to the setDefaults() function and it is now working.  Not much different.  Perhaps a different location in the setup but otherwise nothing that should have impacted this.  
Thanks for re-opening however I now have a working 'setDefaults()' function.

**Comment by Eltargrim** [comment]
I experienced this issue as well but in my case I had one earlier project working fine and the new one was not working. In both cases I had the same version of jQuery (2.2.0), jquery-validation (1.14.0) and jquery-valdiation-unobtrusive(3.2.6). After a lot of back and forth trying to figure out what was different between these two projects it simply boiled down to the order in which the scripts were loaded.

setDefaults was NOT working when order was:
1) jQuery
2) jQuery Validation
3) jQuery Validation Unobtrusive
4) My custom script to set the defaults

setDefaults DID work when order was:
1) jQuery
2) my custom script to set the defaults
3) jQuery Validation
4) jQuery Validation Unobtrusive

To clarify - my custom script that updates the defaults is in a jQuery doc ready and wrapped with an if($.validator){ }. So it won't execute before the validation scripts load, but for whatever reason the exact same code being loaded AFTER the validation scripts load will result in the setDefaults being ignored.

Unfortunately I don't have a code-solution for you, but I did want to add the extra information that may help with a fix.

**Comment by TheSpyridon** [comment]
I had a similar experience as @Eltargrim. 

The only way I could get it to work was in between jQuery Validation and unobtrusive.

Versions:
- jQuery | 3.3.1
- jQuery Validation | 1.17.0
- jQuery Validation Unobtrusive | 3.2.10

My problem stemmed from #1729. The final comment on that thread is the problem that I am currently having. 
![image](https://user-images.githubusercontent.com/25783350/42530852-1b8f4db2-8437-11e8-8757-a1674469cb3e.png)

I'm not quite sure how the validation works, but prior to this issue, I assumed it didn't occur until the form submit.

**Comment by jeremycook** [comment]
Thanks @Eltargrim. I think I now understand the problem I'm experiencing. Like most ASP.NET MVC (Core) developers I load my scripts in the following order:

* jquery.js
* jquery.validate.js
* jquery.validate.unobtrusive.js
* app.js

Unobtrusive validation will do its thing as soon as that script loads and document.ready can run, which is before app.js is loaded and anything in it has ran. So I've updated my code to do the following:

```javascript
// Inside app.js
$(function () {
    if ($.validator) {
        var ignore = ":hidden, [contenteditable='true']:not([name])";

        // This sets `ignore` for future jquery validate configurations, 
        // but not for unobtrusive validation if it has already been loaded.
        $.validator.setDefaults({
            ignore: ignore
        });

        // Update unobtrusive validation's ignore setting when that script was
        // loaded before this script.
        $('form').each(function () {
            if ($(this).data('validator'))
                $(this).data('validator').settings.ignore = ignore;
        });
    }
});
```

The `$('form').each(function () { …` part is necessary because I am loading jquery.validate.unobtrusive.js before app.js, which means unobtrusive has already used whatever default settings were set.

On the otherhand if I loaded my scripts in the following order I would not need the `$('form').each(function () { …` part because unobtrusive will have the expected defaults that I configure in app.js before it can run.

* jquery.js
* jquery.validate.js
* app.js
* jquery.validate.unobtrusive.js

**Comment by nfplee** [comment]
Like @jeremycook I believe this issue shows up when using ASP.NET's unobtrusive validation. The unobtrusive validation library calls the validate method passing in options which overrides the defaults.

Therefore I think it can probably be closed.

**Comment by MiguelAmezquita** [comment]
on jQuery Validation Plugin v1.17.0 

try 

$.extend($.validator.messages, {
    required: "Ur message",
});
