### ISSUE TITLE
Multiple forms, same field names

### ISSUE THREAD

**Issue by DCarper** [jquery-validation/jquery-validation#125]
Hiya,

I have N dynamically generated copies of the same form on one page where basically the only difference is an ID that ties into the database on the backend.

form[1] will fail if form[0] is invalid because all the inputs share names. It seems form[0] is not dependent on from[1] being valid though (which makes me wonder if I'm doing something wrong)

There's a lot of "stuff" out there for when a single form has inputs of the same name, but this was the only example I found of someone else having this same problem: http://forum.jquery.it/topic/validate-plugin-multiple-forms-with-same-form-field-names

(they're using #rules where I'm just using #validate - probably inconsequential but figured I'd include as much detail as possible)

Any advice? Am I missing something? Is there a blog post I missed that you can point me at? If the solution is to fork and fix then I wouldn't mind a point in the right direction :P

Thanks,
Dan

**Comment by devsainii** [comment]
<script type="text/javascript">
        $(document).ready(function () {

            $('form').each(function () {
                $(this).validate({
                    // your options
                });
            });

        });
    </script>

**Comment by JayParmar271** [comment]
hi
