### ISSUE TITLE
Uncaught TypeError: Cannot read property 'settings' of undefined  jquery validation 1.13.0

### ISSUE THREAD

**Issue by svogt0511** [jquery-validation/jquery-validation#1267]
Pretty simple, I comment out my validate call in document ready and the error goes away.

The error occurs when I click on certain for elements.  Even if this is not a validate bug, I am having a hard time debugging.

$(document).ready(function(){ 
...

   // validate main form
    $('#case_form').validate({
        debug: true,
        rules: {
            phone: {
                phoneUS: true,
                required: true
            },
            model: {
                required: false
            },
            serial_number: {
                required: true
            },
            client_group_id: {
                required: true
            },
            description: {
                required: true
            },
            backup_data: {
                required: true
            },
            first_name: {
                required: true
            },
            last_name: {
                required: true
            },
            email: {
                required: true,
                email: true
            },
            department: {
                required: function() {
                    return departmentRequired();
                }
            },
            assigned_to: {
                required: function() {
                    return assigneeRequired();
                }
            },
            operating_system_id: {
                required: true
            },
            warranty: {
                required: true
            }
        },
        messages: {
            phone: '555-555-5555',
            serial_number: 'X',
            client_group_id: 'X',
            description: 'X',
            backup_data: 'X',
            first_name: 'X',
            last_name: 'X',
            email: 'X',
            department: 'X',
            assigned_to: 'X',
            operating_system_id: 'X',
            warranty: 'X'
        },
        invalidHandler: function(form, validator) {
            var errors = validator.numberOfInvalids();
            if (errors) {
                var message = errors === 1
                    ? 'You missed 1 field.'
                    : 'You missed ' + errors + ' fields.';
                displayMessage(message);
            } 
        },
        submitHandler: function(form) {
            $('#main-bubble').spin({ lines: 12, length: 12, width: 4, radius: 12 });
            $('#save_case_form').attr('disabled', 'disabled');
            $('#save_case_form_and_return').attr('disabled', 'disabled');

```
        form.submit();
    }
});
```

...

});

**Comment by josencv** [comment]
I had a similar problem. I was trying to add a custom rule to a field via javascript, but it looks like the browser had unfinished tasks that were needed for the .rules() method to work properly.

To fix it i used the following snippet:

```javascript
setTimeout(function() {
   //Do some calls
}, 0);
```

This [stackoverflow post](http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful) explains why this works.

**Comment by jzaefferer** [comment]
@josencv thanks for chiming in, but commenting on closed issues without anything that reproduces the issue, its unlikely to make any difference.

**Comment by sunil20panchal** [comment]
Thanks its working fine @josencv...

**Comment by zhenglixuan** [comment]
I just meet this issue. I think it is because that form is created by js. So you need to reset the validate.
See the below code:
$('form').validate().resetForm();
$('form').validate();
It work to me.

**Comment by trungjc** [comment]
I got same issue, and found out that, the class name of form same with other element, so i rename class of form and it work
