### ISSUE TITLE
validation of data-val-length-max doesn't consider trailing spaces

### ISSUE THREAD

**Issue by Ef0Dev** [jquery-validation/jquery-validation#1274]
If my input has data-val-length-max="500", and I put in 501 characters, and the 501st character is a regular character, jQuery validation rightfully catches it as invalid. However, if I put in 501 characters, and the 501st character is a whitespace (often happens when text is copied/pasted for example), it does _not_ catch it - it lets it pass as valid.

The problem with this is that databases do consider those trailing spaces as characters... so if you let this through to the database for a varchar(500), you'd get an error. Additionally, MVC server-side validation (ie; check for ModelState.IsValid()) rightfully catches it as invalid, so there is a discrepancy in the behavior between the two. Without server-side validation in place, Entity Framework will throw a DbEntityValidationException when you call SaveChanges() on the context.

It seems to make more sense for jQuery validation to consider the trailing spaces.

**Comment by b-t-o** [comment]
Hi. This method now don't trim email values, if the maxlength is set.

<input type="text" tabindex="73" maxlength="70" size="32" id="email" name="email" data-mini="true" class="user-success">

Entering an email address like "xyz@web.de " will throw an error :(
