### ISSUE TITLE
aria-describedby character escaping (with fix suggstion)

### ISSUE THREAD

**Issue by a-barry** [jquery-validation/jquery-validation#1331]
ref #1269 

When using non label error elements with asp.net web forms the $ character is used in element IDs/names. This causes an error from sizzlejs on the second form submit (dues to the $ in the aria-describedby value).

core.js line 773 needs $ adding to the escape characters ;

``` javascript
- errorID = error.attr( "id" ).replace( /(:|\.|\[|\])/g, "\\$1");
+ errorID = error.attr( "id" ).replace( /(:|\.|\[|\]|\$)/g, "\\$1");
'''
```

**Comment by pascallapointe** [comment]
Error Id in aria-describedby that contain escape character (\) are duplicate each time the field is validate.
Those escape characters need to be escape too.

Try this on line 788 in core.js:
`!describedBy.match( new RegExp( "\\b" + errorID.replace( /(\\)/g, "\\\\$1" ) + "\\b" ) )`
