### ISSUE TITLE
No prepublish script in package.json

### ISSUE THREAD

**Issue by sjmeverett** [jquery-validation/jquery-validation#1339]
Currently the NPM package is useless, as it has nothing built in it.  This is easily fixed by adding  `"prepublish": "grunt"` to the `"scripts"` section in `package.json`.  I tried to patch it so I could submit a pull request, but the `commitplease` module crashes with a syntax error every time I try to commit.

While you're at it, could you also please consider adding something like `files: ['dist']` to `package.json` so it doesn't pull down all the unnecessary stuff when you install it.

Thanks.

**Comment by ryan-sandy** [comment]
Could you publish this as a pre release using the tag option?

    npm publish --tag 1.13.2-pre

NPM [docs](https://docs.npmjs.com/misc/config#tag)

**Comment by jasonmadigan** [comment]
Just wondering, is the preview (or a release) planned to be released soon?

**Comment by noirbizarre** [comment]
Same quesiton for me: Any pre-release, preview or release planned ?

**Comment by geirsagberg** [comment]
I'm waiting for this release as well. using `jquery-validation-dist` package in the meantime.
