### ISSUE TITLE
<optgroup> in select is not supported when onclick() is called

### ISSUE THREAD

**Issue by nzamani** [jquery-validation/jquery-validation#141]
I use jQuery 1.6.1 and Validation 1.8.1.

I have the following code in HTML (includes optgroup!):

&lt;select size="1" id="salutation" class="required" name="list" id="list"&gt;
    &lt;optgroup label="please select a salutation"&gt;
        &lt;option value="1" >Mr&lt;/option&gt;
        &lt;option value="2" >Mrs&lt;/option&gt;
        &lt;option value="3" >Dr&lt;/option&gt;
        &lt;option value="4" >Prof Dr&lt;/option&gt;  
    &lt;optgroup&gt;
&lt;/select&gt;

Now imagine $('#salutation').valid() returns false and the <select> is highlighted.
What I expect is that on selection of any of the options the errors are unhighlighted - no matter if selected
via keyboard or via clicking with mouse.
But if you use your mouse this only works if you select an option via click and afterwards click somewhere else
to make onfocusout() in validate.js being fired. Using keys seems to work fine.

In validate.js I can see:

```
onfocusout: function(element) {
    if ( !this.checkable(element) && (element.name in this.submitted || !this.optional(element)) ) {
        this.element(element);
    }
},
onkeyup: function(element) {
    if ( element.name in this.submitted || element == this.lastElement ) {
        this.element(element);
    }
},
onclick: function(element) {
    // click on selects, radiobuttons and checkboxes
if ( element.name in this.submitted )
    this.element(element);
// or option elements, check parent select in that case
else if (element.parentNode.name in this.submitted)
    this.element(element.parentNode);
}
```

It seems only onfocusout() and onkeyup() work fine if fired.
onclick() does not work.

If I leave away the <optgroup> then everything works as expected.

It would be great to have the <optgroup> handling fixed in onkeyup() and onclick().

**Comment by didsun** [comment]
@bartsipes Can you post the solution?

**Comment by bartsipes** [comment]
@didsun not sure what you mean. There was no solution or fix. It was working already when I tested it.
