### ISSUE TITLE
function showErrors works on unselected elements

### ISSUE THREAD

**Issue by leojin** [jquery-validation/jquery-validation#1503]
I found the function showErrors may works on unselected elements.
It may be affected when the focus is changed.
I wrote a demo to describe this issue.
http://leojin.com/demo/jquery_validation_showErrors/

And in my project, i fixed this problem in the following way:

``` javascript
    jQuery.validator.prototype.showErrorsFix = function (cnf) {
        var list = [];
        for (var key in cnf) {
            var tmp = $('[name=' + key + ']');
            if (tmp.size()) {
                list.push(tmp[0]);
            }
        }
        this.currentElements = $(list);
        this.showErrors(cnf);
    };
```

**Comment by jzaefferer** [comment]
This is related to the bad state management of the plugin. Instead of tracking the status of each field individually, it just has one place to store what's valid and what isn't. This is likely very difficult to fix.
