### ISSUE TITLE
Secure funding for future development

### ISSUE THREAD

**Issue by jzaefferer** [jquery-validation/jquery-validation#1507]
The pledgie campagin has helped with server costs and to get a logo designed, but overall donation-based funding like that isn't enough.

A few ideas to enable future developments:
- Mozilla Foundation Grants: http://www.mozilla.org/en-US/grants/
- NLNet: http://www.nlnet.nl/foundation/request/application.html
- Pay What You Want model: Promote its free and open source character, explain the rights they have and what paying for the product gives them; Suggest a few prices, for example 0 for students, 50 for individuals, 500 for companies

This is more of a reminder to myself, but if anyone has experience with this or ideas or just has a company at hand that might want to fund the project, please let me know. Here or email (joern.zaefferer@gmail.com).

**Comment by stijnherreman** [comment]
Have you been in contact with Microsoft before? They've been using this library in their ASP.NET MVC templates for some years now, in combination with https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Validation/

**Comment by jzaefferer** [comment]
About crowdfunding for open source: https://twitter.com/fronx/status/520137832921575424 which points at https://www.indiegogo.com/projects/tern-intelligent-javascript-editing#/story and https://marijnhaverbeke.nl/fund/

@stijnherreman I should try that again, thanks for the hint

**Comment by jzaefferer** [comment]
Some discussion of funding open source in general: https://coderanger.net/funding-foss/

**Comment by jzaefferer** [comment]
See also http://marijnhaverbeke.nl/blog/sustainable-maintenance.html
