### ISSUE TITLE
Docs: bad link on return types

### ISSUE THREAD

**Issue by staabm** [jquery-validation/jquery-validation#1517]
The return type `Validator` on http://jqueryvalidation.org/validate/ links to api.jquery.com but does not describe the actual type.

**Comment by jzaefferer** [comment]
That's tricky to fix, since those links are generated in the `grunt-jquery-content` module. And there isn't even a page for the `Validator` type itself.

**Comment by staabm** [comment]
So is it possible that we get the docs for our types fed into api.jquery.com instead? Or maybe we need to rewrite some of the urls before rendering them to the browser?

**Comment by jzaefferer** [comment]
I doubt they want any plugin-specific types there. So I guess we'd need a separate page, then somehow change the links for `#Validator` to point there instead.
