### ISSUE TITLE
Date validation with non US locales

### ISSUE THREAD

**Issue by Kuvalda** [jquery-validation/jquery-validation#153]
http://stackoverflow.com/questions/2385474/set-a-locale-in-javascript - i have same problem with all latest browsers Chrome, IE, FF.

there is description and fix (at 2009!):
http://geekswithblogs.net/EltonStoneman/archive/2009/10/29/jquery-date-validation-in-chrome.aspx

Please fix your code :)
10nx!

**Comment by akirayamamoto** [comment]
Same here
