### ISSUE TITLE
Using jquery-validation for displaying server-side errors via AJAX

### ISSUE THREAD

**Issue by dave-newson** [jquery-validation/jquery-validation#1543]
I need help figuring out how I can make jquery-validation correctly manage server-side generated validation errors. I'm about half way there, but I keep running into problems.

**Setup**
- Symfony2 back-end using Symfony Forms, and custom validation rules
- Symfony/twig generated HTML
- jquery-validation plugin rigged into the form
- Backend uses an expensive API call, so ultimately validation only occurs on the final submit of the form.
- Form submitted by jQuery `$.ajax()` call, errors returned in JSON format, and passed to `showErrors`.

**Recommended method**
I think normally you would use the jquery ajax form plugin (http://jquery.malsup.com/form/) for ajax? However we manage our data in a somewhat complicated manner, and that plugin just gets in our way. As a result we want to use jQuery `$.ajax` calls, and jquery-validation in a stand-alone manner.

**Data format**
Symfony2 is expecting the JSON form data as:

```
{
    'myForm[firstname]': "john",
    'myForm[lastname]': "doe",
    'myForm[likes][0]': "beans",
    'myForm[likes][1]': "meanz",
    'myForm[likes][2]': "heinz"
}
```

This gives me some nice symmetry, because jQuery validation accepts this format for the errors:

```
{
    'myForm[firstname]': ["First name should be capitalised"],
    'myForm[likes]': ["We don't like beans here."]
}
```

That part works perfectly, and is the reason I'm using jquery-validation in the first place.

**Example implementation**
http://jsfiddle.net/2q3xx2ve/
In this example, you can repeatedly click "Show Errors" to populate the form with errors that might be returned by our API.

Because "Likes" (`myForm[likes]`) isn't actually a physical field (yay checkboxes etc!), the error gets mapped to a non-existent "parent" field by Symfony. To cater for this, we've augmented the `showErrors()` and `errorPlacement()` code to map those errors into `[data-name=the_field_name]`. In the HTML, this is a Bootstrap Alert box.

We use this technique a lot, as Symfony can map errors to all sorts of not-really-existing names, and we can then map them to the appropriate locate on the page. It's some very helpful magic.

**Problem 1: Clearing errors**
Each time we submit to the API, we want to clear the validation errors on our side until a response comes back.
The only way I can see to do this, is calling `resetErrors()`.
Unfortunately `resetErrors()` only clears the error _messages_, and not the _highlight_ on the field.

This happens because `this.toHide` contains a reference to the message, but `this.elements()` filters out inputs which do not possess a jquery-validate rule, so `this.settings.unhighlight` is never called for those inputs.

We have way too many forms, some of which are dynamic, to define "empty" rules for out forms. I really like that jquery-validate can add errors to fields it's not monitoring, but it's failure to un-highlight those same fields is an issue.

**Problem 2: Hiding those alerts**
Similar to the above, when we use `showErrors()` to toggle the visibility of a Bootstrap Alert box, we don't then have a good way to track that alert box. 
I couldn't inject it into `toHide` or `toShow` for reasons I couldn't determine, but it looked like either an issue with `addWrapper()` or the fact that HideErrors is called after ShowErrors and I was getting the state order wrong.

Anyway, here's a version where I monkey-patched the functionality in, but it's a horrific hack that makes me uncomfortable:
http://jsfiddle.net/2q3xx2ve/1/

**What I need**
I can make a PR for most of this, but I need some guidance before I go breaking everything.
- jquery-validate should be able to track the validation errors it adds to a form, regardless of the rules in play, so it can remove and unhighlight them, too.
- The show/hide errors code should be flexible enough to handle the "alert" scenario as well as the standard forms errorPlacement stuff. This could probably be helped by:
- Add some event triggers! Rather than using callbacks, events would let me augment the functionality of jquery-validation easier and not be forced to monkey-patch my way around the code (I've seen the roadmap - why isn't this in yet?).

Any feedback or help is welcome. Also if I've taken a completely idiot approach to my goals, let me know how I should be doing things.

**Comment by shooftie** [comment]
Did you ever get this working? +1 if not...

**Comment by manchumahara** [comment]
possible solution is 

`
//$form_validator  is instance of form validator
//$jsondata  is json data you get from server or manually build
//example data format
/*
{
    "post_title": "Sorry title can not be empty"
}
*/

$form_validator.showErrors($jsondata);
`
