### ISSUE TITLE
showErrors() generated errors removed prematurely on keyup when resubmitting with Enter key

### ISSUE THREAD

**Issue by nathanhornby** [jquery-validation/jquery-validation#1553]
Hopefully you can reproduce this, but I'm having an issue with a manually assigned error in Meteor (using the wrapper provided by [themeteorchef](https://github.com/themeteorchef/jquery-validation)), using the `showErrors()` technique:

```
  if (error.reason === "URI Taken" || error.reason === "URI special match") {
    validator.showErrors({
      uri: "Sorry, that URI is already in use."
    });
  }
```

Firstly the error clears on `blur` - I assume this is because the plugin is re-evaluating the field and doesn't find an error (because the error comes from the server in this case). Not ideal, but I can live with that, it makes sense, hard to avoid.

However the bigger issue is if the form is resubmitted using the enter key. Steps to reproduce:
- Enter invalid value, submit the form (using any method).
- Give focus back to the field with the invalid value, and hit enter while the value is still invalid.

The message flashes up and immediately disappears, the `keyup` on the enter seems to reset the validation - but only when it's resubmitted. It flashes up so quickly that it's never properly shown.

Is this an issue with `keyup` re-validating the form? Is there a way I can avoid it in this case? Do we need a special case for keyup on enter?

**Comment by nathanhornby** [comment]
**Update:** Using the `onkeyup: false` option has resolved my issue - so it seems that there might need to be a special case for the Enter key? Although this gets more complicated for textareas which allow returns :/

**Comment by staabm** [comment]
Could you provide a jsfiddle demonstrating your issue and describe the steps required?

**Comment by nathanhornby** [comment]
The steps to reproduce are in the report, the problem should exist with any implementation (as far as I can remember...). It's not specific to any markup.

**Comment by staabm** [comment]
As the libs behaviour highly depends on markup, used settings other libs on the same page etc. the information above is not enough to help you.

Please create a reduced jsfiddle which shows your problem and tells us the steps how to reproduce.

**Comment by nathanhornby** [comment]
As is the law of the land, however I wasn't really after help, just reporting an issue. I'm not able to assist any more, perhaps the next time I use the plugin I'll revisit.

But to reiterate, when using the showErrors() method then this:

Enter invalid value, submit the form (using any method)
Give focus back to the field with the invalid value, and hit enter while the value is still invalid
Bugs the error.

If you don't have any implementations using showErrors() to test that on then maybe the next time :-)
