### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by jzaefferer** [jquery-validation/jquery-validation#1569]
I'm looking for maintainers for this project! I haven't given up on it, but my available time is currently too limited to even deal with the day-to-day issue and PR triage. Especially when people contribute code, its a shame to have those pull requests lie around untouched for weeks.

If you're interested in getting involved in an open source project that has a large user base, let me know!
You can get started right away - look through open issues and pull requests, help fix or land them.

**Comment by Kellamity** [comment]
What level of expertise is required here?  Would someone who is familiar with jQuery and also using this plugin be able to jump in, or do you have to be a verifiable jQuery master?  Is there a minimum time to commit per week?

**Comment by programmersujeet** [comment]
Hey @jzaefferer , I am interested to be the maintainer of this project. I am a JS ninja, a fullstack developer.
Having Skills in JS/jQuery/Anguler/requireJS/Handelbars etc.

**Comment by staabm** [comment]
I will spent a few hours each month on ticket triage and providing feedback on PRs. I am not interessted in managing future development though.

**Comment by christopherbauer** [comment]
Like Kellamity, I'm looking into jquery-validation quite a bit, and have recently issued a pull request recently as well. What level of experience are you looking for?

**Comment by kylecarter** [comment]
I am willing to help where I can. I use jquery validation a lot and am willing to dedicate some time to help maintain it.

**Comment by Arkni** [comment]
I can help reviewing pull requests and providing some feedback on issues, I can also help in maintaining the project. All that in my free time.

**Comment by Hermannovich** [comment]
Really interesting. Young developer but with an energy to maintain this project.

**Comment by timbeadle** [comment]
I'll help where I can - jQuery Validation has been so valuable to me over the last few years.

**Comment by dkrahn** [comment]
I willing to help. What are the necessary skills?

**Comment by nguyenvanduocit** [comment]
I willing to. I use this lib in all of my front-end project

**Comment by mord4z** [comment]
I want to help, I like this project and use a lot it.

**Comment by rolfen** [comment]
I am interested. I've only just begun using this plugin but have some experience rewriting re-usable helper code (some server-side, though). Anyway I believe that I have enough JavaScript, jQuery and programming expertise to help and contribute somehow.

**Comment by staabm** [comment]
Anyone willing to help could give feedback on open issues.. Please try to reproduce the reported issues on jsfiddle and post a link to it in the corresponding issue.

At best you could provide a unit test which reproduces the issue after a jsfiddle proved it actually exists.

**Comment by FagnerMartinsBrack** [comment]
@jzaefferer I found this repo about OSS funding discussions https://github.com/pybee/paying-the-piper. It might be useful in some way.

**Comment by SakyaStelios** [comment]
I want to help, too

**Comment by nicolasguzca** [comment]
Willing to help too!

**Comment by khairulhasanmd** [comment]
yes, willing to help as much as i can.

**Comment by pavankumarlpersonal** [comment]
I'm willing too. Please let me know if you are still in need of maintainers

**Comment by staabm** [comment]
Just in case, Let me quote my comment, because most people do not read the entire thread:

> Anyone willing to help could give feedback on open issues.. Please try to reproduce the reported issues on jsfiddle and post a link to it in the corresponding issue.

> At best you could provide a unit test which reproduces the issue after a jsfiddle proved it actually exists.

**Comment by staabm** [comment]
Will maintain the plugin for now.

**Comment by bytestream** [comment]
@staabm please reopen this. For the past 12 months or more there's been no maintenance, and it cannot be said that the library is bug free hence why it's *quiet*

I would be happy to help, currently I maintain - https://github.com/proengsoft/laravel-jsvalidation

**Comment by staabm** [comment]
@bytestream thx for your engagement.

feel free to provide pull requests/fixes for open problems.
you might also help other people who try to contribute to get their PR over the finishing line.

we are open for every kind of support as long as we keep the lib on the track and dont offend against the libs principles/ideas.

**Comment by Arkni** [comment]
@bytestream Thanks a lot for you interest :)

I pinned the issue for more visibility.

**Comment by sunny-shu** [comment]
@Arkni 
Is there still a shortage of people for this project?i found there are many issues here that are not closed.
if yes,i am happy to maintainer this project.My current job is to maintain the open source software used in our project. so i can pay more time on it.

**Comment by bytestream** [comment]
@sunny-shu the usual response is that you can help by responding to issues and reviewing PRs. Once you've gained their trust then they might give you access to the repository. It wouldn't necessarily be wise to dish out immediate write access to randoms given wide spread usage of this project.

@Arkni @staabm I don't think there's a way to give people just issue access? ie so they can close issues. It could be worth creating an issue only repository and dishing out access to that - https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-an-issues-only-repository. That would help to reduce load. A big problem at the moment is people open issues that aren't actually bugs, people reply and the issue owner never close it... if there were people with access to close issues who paid close attention to the repository this would help.

**Comment by RobJohnston** [comment]
Is StaleBot not running anymore to close old issues?  https://github.com/marketplace/stale

**Comment by bytestream** [comment]
Nop, someone with write access needs to re-enable it. No issues with https://github.com/jquery-validation/jquery-validation/blob/master/.github/stale.yml

**Comment by TonyGravagno** [comment]
This project shouldn't use the stalebot - a huge number of issues could be autoclosed because they haven't been triaged.
