### ISSUE TITLE
Addition Methods - Canadian Postal Code - REGEX Changes

### ISSUE THREAD

**Issue by james-gerard-rodgers** [jquery-validation/jquery-validation#1591]
The regex for Canadian postal codes is in upper case and requires a space, for usage it should accept upper and lower and the centre space is optional.

the following postal codes are correct and are accepted by almost every system I have ever used
M1L 2S9
M1L2S9
m1l 2s9
m1l2s9

speaking as a  Canadian, almost no one uses the upper case format and the space is sometimes omitted.

**Comment by staabm** [comment]
@james-gerard-rodgers are you willing to provide unit tests for your postals and a fix?

**Comment by james-gerard-rodgers** [comment]
I have never done that for github; is there a standard method for providing these? if you can link me a sample of how the unit tests should be provided I can do it.

I have a regex that i use on for other instances but the current implementation i am working on was better with jquery validation.

**Comment by Arkni** [comment]
The Canadian postal code tests is here: https://github.com/jzaefferer/jquery-validation/blob/master/test/methods.js#L1229-L1241

And the regex that you can change is here: https://github.com/jzaefferer/jquery-validation/blob/master/src/additional/postalCodeCA.js#L15

**Comment by RobJohnston** [comment]
This can be closed.  All the examples given by @james-gerard-rodgers  pass now.  

Looks like it was done in https://github.com/jquery-validation/jquery-validation/pull/1536.

Updated link to tests:  https://github.com/jquery-validation/jquery-validation/blob/master/test/methods.js#L1626

P.S.  I'm sure he meant to say, "almost no one uses the **lower** case format".

**Comment by Arkni** [comment]
@RobJohnston Thanks for the reminder

Will close this for now. Please ask if you have followup questions.
Thanks!
