### ISSUE TITLE
errorElement 'a' in conjunctions with errorPlacement

### ISSUE THREAD

**Issue by powpow12** [jquery-validation/jquery-validation#1622]
When using errorPlacement, I would like the errorElement to be 'a' with the href equal to the id of the error element.  Also, errorPlacement should receive focus on failure. These are related to recent findings of a accessibility test.

**Comment by staabm** [comment]
Please show us the markup you want to be used for invalid elements.

What do you mean by errorPlacement should receive focus? What to focus when several fields are invalid?

**Comment by powpow12** [comment]
right, here is what I got so far off the errorcontainer-demo.html:

```
<div class="container" aria-live="assertive">
	<h4>There are serious errors in your form submission, please see below for details.</h4>
	<ol>
		<li><a id="email-error" class="error" href="#email">Please enter your email address</a><li>
		<li><a id="phone-error" class="error" href="#phone">Please enter your phone <b>number</b> (between 2 and 8 characters)</a></li>
		<li><a id="address-error" class="error" href="#address">Please enter your address (at least 3 characters)</a></li>
		<li><a id="avatar-error" class="error" href="#avatar">Please select an image (png, jpg, jpeg, gif)</a></li>
		<li><a id="cv-error" class="error" href="#cv">Please select a document (doc, docx, txt, pdf)</a></li>
	</ol>
</div>
```
If the error container receives focus then the user can tab through each of the error links.  This may also need a pushDown parameter that will add extra padding when developers have sticky headers (so the field isn't hidden behind the header).

Note: I am already working on this 'feature' on my fork, I created this issue to have a reference id and keep up with your standards for commit messages (very good read by the way).  I plan on working and completing this in the next day or two.

**Comment by powpow12** [comment]
So my timeline was off by some, on my fork I have created a new demo, accessible-errrorContainer-demo.html

I have almost completed the necessary fixes but ran into an issue when I have groups. This excerpt is from showLabels:

```javascript
group = this.groups[ element.name ];
					if ( group ) {
						console.log("Before this");
						console.log(this);
						$.each( this.groups, function( name, testgroup ) {
							if ( testgroup === group ) {
								console.log("After this");
								console.log(this);
								$( "[name='" + this.escapeCssMeta( name ) + "']", this.currentForm )
									.attr( "aria-describedby", error.attr( "id" ) );
							}
						} );
```

Here is the console log: http://snag.gy/6J99h.jpg

````
Before this
jquery.validate.js:872 Object {settings: Object, currentForm: form#form2.cmxform, labelContainer: jQuery.fn.init[1], errorContext: jQuery.fn.init[1], containers: jQuery.fn.init[3]…}
jquery.validate.js:875 After this
jquery.validate.js:876 String {0: "s", 1: "t", 2: "a", 3: "t", 4: "e", 5: "_", 6: "p", 7: "r", 8: "o", 9: "g", 10: "r", 11: "a", 12: "m", 13: "s", length: 14, [[PrimitiveValue]]: "state_programs"}
jquery.validate.js:697 Exception occurred when checking element agree, check the 'require_from_group' method. TypeError: this.escapeCssMeta is not a function(…)
````

For now, I am commenting out the "group check", but I would like to work on a fix for this error. I am out of the country for two weeks and will have minimal access to emails from 11/22-12/5.

**Comment by staabm** [comment]
I still dont know what the actual issue is. Please provide a jsfiddle which demonstrates your issue.

**Comment by powpow12** [comment]
Sorry, I forgot to share this earlier.  Here are the results of our accessibility audit earlier this year:

# Paciello Report

## Multiple error messages 
When one or more errors can happen per page, and are summarized in the error message as shown in Figure 42 or Figure 43, we present the following best practice recommendations to improve the ability of a user to both understand and correct the multiple errors within the form. For a working example, refer to the form validation demonstration

*  Create a container `<div>`, add `tabindex="-1"` to the container `<div>` to make the container focusable via the use of the JavaScript `.focus()` method. Make sure this container receives focus after the user activates the “Submit” button if one or more errors have been made. 
*  Apply `role="group"` to the `<div>` to inform assistive technologies that the container represents a collection of related items.
*  Mark up the summary error message as a heading so that it is more easily discoverable, and use the aria-labelledby attribute on the container `<div>` with the list’s heading id as its value.
*  Mark up each individual error as a link back to the form field that contained the error.
*  Make sure that aria-invalid and aria-required (where appropriate) are applied to the form field(s) containing the error, and are both set to true as appropriate.
Once a user has submitted incorrect or insufficient data, the error message list is displayed on the page.
*  Move focus to the error message container element. This results in all users being alerted to the presence of the error message. For screen reader users the errors are announced.
*  Any user can navigate to the incorrect fields via the linked error messages.

## Resources
[provided example](http://files.paciellogroup.com/training/commonsamples/formvalidator_demo/html/FormValidatorDemo2.html)

Here is the a fiddle of the current setup [current_validate] (https://jsfiddle.net/50p0bw4j/).  To see the  changes I made, please see my fork.  I have everything completed with the caveat of the error I am running into with require_from_group.
