### ISSUE TITLE
notEqualTo messages

### ISSUE THREAD

**Issue by afattahi54** [jquery-validation/jquery-validation#1677]
I found that the `notEqualTo` method was added but can not find the messages update in many locales for this new method.
Am I wrong ?!

**Comment by staabm** [comment]
Patches for other language files are welcome

**Comment by RobJohnston** [comment]
An examples of how to do this, there have been two added so far:

- French in https://github.com/jquery-validation/jquery-validation/pull/2033
- Danish in https://github.com/jquery-validation/jquery-validation/pull/2067

**Comment by staabm** [comment]
Will close for now because of inactivity. Feel free to ask further questions/provide furhter information regarding this topic here. We can re-open if required.

@RobJohnston thx for pointing the author of the issue in the right direction
