### ISSUE TITLE
Please facilitate conditional requirements not based on dependencies (require_from_group.js)

### ISSUE THREAD

**Issue by Chealer** [jquery-validation/jquery-validation#1694]
I searched the documentation for half an hour trying to find a way to require one of 4 fields to be filled. Eventually, I found an additional method for that: https://github.com/jzaefferer/jquery-validation/blob/master/src/additional/require_from_group.js

The plugin supports well conditional requirement based on dependencies; for example, requiring _y_ if _x_ is set to some value. However, it is difficult to require that at least 1 field from a set of _z_ fields are filled. Using the require_from_group method worked for me, though the result is not great:
1. require_from_group validates each of the semi-required fields. This is suboptimal in terms of CPU usage.
2. The error is apparently not translated to French. This is solved in version 1.15.
3. Using require_from_group is painful. For my case, I needed the code at the bottom. This takes time to write and reduces performance and maintainability.
4. CSS selectors are flaky. "input[type=text]" worked, "form input[type=text]" didn't ($fields was empty).

I suggest either shipping built-in support for such conditional requirements, or somehow referring to require_from_group from the documentation, for example in demos.

Note that the reason it took me so much time to figure out that such a requirement could be achieved with addMethod() is the wording of [addMethod()'s documentation](http://jqueryvalidation.org/jQuery.validator.addMethod):

> method
> Type: Function()
> The actual method implementation, returning true if an element is valid. First argument: Current value. Second argument: Validated element. Third argument: Parameters.

In my mind, I was validating a form, not **an element**.

Appendix: the code I ended up with

```
jQuery('form').validate({
    rules: {
        searchtel: {
            require_from_group: [1, "input[type=text]"]
        },
        searchnom: {
            require_from_group: [1, "input[type=text]"]
        },
        searchcp: {
            require_from_group: [1, "input[type=text]"]
        },
        searchglobal: {
            require_from_group: [1, "input[type=text]"]
        },
    }
    });
``
```

**Comment by staabm** [comment]
Feel free to propose how things could get improved.

PRa to improve the additional plugin are welcome. I dont think this funcnionality will move into core in the foreseeable future.

**Comment by Chealer** [comment]
Hi staabm.

For a documentation approach, a sentence in addMethod() explicitly stating that validity is contextual would help:
> The actual method implementation, returning true if an element is valid. **Validity can be contextual; for example, a field's validity may depend on another field's value.** First argument: Current value. Second argument: Validated element. Third argument: Parameters

Or adding an example to addMethod()'s documentation. Or adding a demo using require_from_group, or by modifying a demo to use require_from_group.

As for building this in, there could be a requireSome(?) method taking a selector as first argument, and an optional integer as second argument to specify a minimum number of filled fields other than 1.

**Comment by Chealer** [comment]
I no longer work on a project using jquery-validation and do not know if the issue persists, but I very much disagree with automated ticket closure.
