### ISSUE TITLE
Adding support for a 1 digit in 3rd position of CO code for non-geographical area codes in PhoneUS validator

### ISSUE THREAD

**Issue by gswartwood** [jquery-validation/jquery-validation#1695]
As discussed in a previously closed issue, non-geographical US area codes can have a 1 in the third position of the CO code. The current phoneUS validator does not support this.

For example:
888-511-xxxx (replacing xxxx with some real 4 digit number) is a valid US phone number but not accepted by the validator.

**Comment by staabm** [comment]
PR with a unit test + fix is welcome
