### ISSUE TITLE
evaluate the required changes to get a jquery free build

### ISSUE THREAD

**Issue by staabm** [jquery-validation/jquery-validation#1702]
check what needs to be done to get the plugin running without requiring jquery.

no external dependency on jQuery is a big plus, especially for mobile application.s

**Comment by Arkni** [comment]
1. Does that means dependency free ? If yes, should the name of the plugin change as well ?
2. Can we drop support for legacy browsers (mainly IE, we can set it to `>=IE10` and latest version of every other browser) ?
3. Which [pattern](https://addyosmani.com/resources/essentialjsdesignpatterns/book/) should be used then ?

**Comment by staabm** [comment]
I am not sure yet what this means exactly. 
Lets brainstorm how a future jq-validate could look like.

Maybe we can define/provide/document the minimum jq-build required (so which modules of jquery are required).  

This could even mean some kind of process/loop in which we at first define what the ext. Dependencies are right now and then try to minimize those (and starting over).

**Comment by Arkni** [comment]
Maybe we can use [`Zepto`](https://github.com/madrobby/zepto) or [`Sprint`](https://github.com/bendc/sprint) to replace `jQuery` or the hard way ,a full rewrite of the plugin using only _`vanilla JS`_.
