### ISSUE TITLE
Multiple forms with duplicate element ids

### ISSUE THREAD

**Issue by govis** [jquery-validation/jquery-validation#171]
Hi,

I use .element("#elementid") syntax to validate individual fields. When I have more then one form on the page and they happen to share element ids the plugin doesn't work correctly. When elements of subsequent forms (declared in the markup after the first form) get validated - the method does return false for invalid elements but they don't get highlighted until I click the form to have the focus enter and leave the invalid element.

It seems that if I modify the "clean" function that is called by the “element” function so it uses currentForm or errorContext for selector’s context or use .element($("#elementid", elementForm)) it seems to work with one exception - if I call .showErrors(errors) method to display a custom error then last invalid element that was validated just before I called showErrors method loses it's highlighting. Somehow it makes it into the validElements in the "unhighlight" loop of the defaultShowErrors routine.

On the other hand .form() method works fine and handles forms with duplicate element ids without problems.

Any idea what's going on here?

Thanks for your help.

**Comment by inversionandy** [comment]
https://vase-mass-produced.github.io/florian401/ the answer is found
