### ISSUE TITLE
email input type and the multiple attribute

### ISSUE THREAD

**Issue by RobJohnston** [jquery-validation/jquery-validation#1722]
HTML5 has a [multiple attribute](https://www.w3.org/TR/2012/WD-html5-20121025/common-input-element-attributes.html#attr-input-multiple) that can be specified for e-mail addresses as well as files.  For e-mail, it would be [a set of comma-separated strings, each of which is a valid email address](https://www.w3.org/TR/html-markup/input.email.html#input.attrs.multiple).  

When applying the multiple attribute to the existing [jQuery Validation Plugin Demo](http://jqueryvalidation.org/files/demo/), more than one e-mail address will not validate.

There are solutions to this (e.g., http://stackoverflow.com/questions/10352221/jquery-validation-plugin-multiple-email-addresses), but ideally, one should be able to write the following without using addMethod:

``` html
<input id="email1" name="email1" type="email" multiple>
```

**Comment by staabm** [comment]
This seem to be pretty new, never seen it in the wild yet.

PR with a patch and unit test welcome.

**Comment by Sven-Mad** [comment]
hi @ll

here my solution, for multiple-emails
`        jQuery.validator.methods.email = function(value, element) {
            if (this.optional(element) && '' == value) {
                return true;
            }
            if (value != element.value ||
                !element.multiple
            ) {
                return /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test( value )
            } else {
                var emails = value.split(/[,]+/); // split element by ,
                valid = true;
                for (var i in emails) {
                    value = emails[i];
                    valid = valid &&
                             jQuery.validator.methods.email.call(this, jQuery.trim(value), element);
                }
                return valid;
            }
        }`
i hope it helps

**Comment by RobJohnston** [comment]
See also:  https://stackoverflow.com/questions/10352221/jquery-validation-plugin-multiple-email-addresses#10352428

**Comment by Sven-Mad** [comment]
My function is for the HTML5 element input-type = "email" with and without the attribute multiple
`<input id="email1" name="email1" type="email" multiple>`

It verifies by itself whether it is multiple and then makes the right test
