### ISSUE TITLE
remote method: mismatch between ajax dataType and response handling

### ISSUE THREAD

**Issue by MrGabriCavi** [jquery-validation/jquery-validation#1725]
In method remote I have found a mismatch between the ajax dataType setting (setted @ "json" in library) and the handling of response variable in method "success" of ajax call.
The method "remote" declaration refer tu a "valid" variable that assuming is true (bool) or "true" (string), it work if, in fact, response from ajax request is "true"; otherwise the "response" handling try to put "response" itself in validation error messages. 
It doesn't work beacause jquery trying to treat "response" as JSON data type. 
I have tried to switch dataType declaration from "json" to "text" and it begin work:
if the ajax response is "true", method set the field as valid, otherwise the ajax response is inserted in the error message, you could display message like "domain invalid" or "something wrong I want to tell".
I hope this will be useful for those have my same issue.

**Comment by staabm** [comment]
I dont get what you are saying.. Could you demonstrate using a jsfiddle what the issue is?
