### ISSUE TITLE
Can you provide method to "require no more than X fields"

### ISSUE THREAD

**Issue by ofry** [jquery-validation/jquery-validation#1742]
Can you provide method to "require no more than X fields"?

Almost same as "require_from_group"...

> /*
>      \* Lets you say "no more than X inputs that match selector Y must be filled."
>      *
>      \* The end result is that neither of these inputs:
>      *
>      \*  <input class="productinfo" name="partnumber">
>      \*  <input class="productinfo" name="description">
>      *
>      \*  ...will validate unless no more than one of them is filled.
>      *
>      \* partnumber:  {some_method: [1,".productinfo"]},
>      \* description: {some_method: [1,".productinfo"]}
>      *
>      \* options[0]: number of fields that should be filled in the group
>      \* options[1]: CSS selector that defines the group of conditionally required fields
>      */

Sorry for my English...

**Comment by staabm** [comment]
Please provide more information. This kind of questions should be asked on stackoverflow though...

It sounds like a very app specific feature request which is not general enough to bundle it with the core.

**Comment by ofry** [comment]
More information? OK.

For sample, I need only a certain amount of fields that match selector Y to be filled.

With this rule and required_from_group it will be trivial.

And code which realises that is trivial:

`$.validator.addMethod( "require_maximum_from_group", function( value, element, options ) {
        var $fields = $( options[ 1 ], element.form ),
            $fieldsFirst = $fields.eq( 0 ),
            validator = $fieldsFirst.data( "valid_req_grp" ) ? $fieldsFirst.data( "valid_req_grp" ) : $.extend( {}, this ),
            isValid = $fields.filter( function() {
                    return validator.elementValue( this );
                } ).length >= options[ 0 ];

        // Store the cloned validator for future validation
        $fieldsFirst.data( "valid_req_grp", validator );

        // If element isn't being validated, run each require_from_group field's validation rules
        if ( !$( element ).data( "being_validated" ) ) {
            $fields.data( "being_validated", true );
            $fields.each( function() {
                validator.element( this );
            } );
            $fields.data( "being_validated", false );
        }
        return isValid;
    }, $.validator.format( "Please fill no more than {0} of these fields." ) );`

**Comment by ofry** [comment]
https://dl.dropboxusercontent.com/u/97349870/require_maximum_from_group.js
