### ISSUE TITLE
Can't remove 'required'-rule when element has 'required'-attribute

### ISSUE THREAD

**Issue by ischas** [jquery-validation/jquery-validation#1745]
When the element has a 'required'-attribute, you can't remove it by calling `$(element).rules('remove','required')`.

https://jsfiddle.net/6hnw855z/1/

A pull-request to solve the problem will follow up.

**Comment by k0stenko** [comment]
try to use double quotes with "remove"
$(element).rules("remove",'required')

**Comment by Arkni** [comment]
Closing for now. See https://github.com/jquery-validation/jquery-validation/pull/1746#issuecomment-372032944 for reason.
