### ISSUE TITLE
data-rule-number broken

### ISSUE THREAD

**Issue by jinglesthula** [jquery-validation/jquery-validation#1754]
### Subject of the issue

data-rule-number doesn't work in 1.15.0 (although it the rule does work if you pass `rules: {foo: {number: true}}` in the options instead of using the data-rule-\* attribute approach).
### Your environment
- 1.15.0 (served via https://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js)
- Chrome 49
### Steps to reproduce

https://jsfiddle.net/jinglesthula/amaxhbyq/
Enter `abcd` in the field and try to submit.  It accepts the non-numeric value.   The person who reported the bug to me mentioned that some of the other rules also weren't working using `data-rule-*` attributes, but I have a hunch they all stem from how numeric values are handled.
(Note: you can verify that the plugin itself is running by leaving it blank to see the required rule apply correctly.)

Also, I discovered that it was working in 1.13.1: https://jsfiddle.net/jinglesthula/swtb3Lf5/
### Expected behaviour

It should show the `Please enter a valid number` message and prevent form submission.
### Actual behaviour

Doesn't appear to be applying the rule

**Comment by Arkni** [comment]
This commit fa5f69c529614fcf7d32e20c6ba41f8ce84f647e (PR #1391) is the culprit.

**Comment by Arkni** [comment]
For now, you have to use 
```js
data-rule-number="true"
```

**Comment by staabm** [comment]
Unittest + PR welcome.

**Comment by AlexGodofsky** [comment]
This appears to affect pretty much any custom rule as well that doesn't take a parameter. `normalizeAttributeRule` just never decides that the rule is worth adding.

**Comment by kodecount** [comment]
@Arkni @staabm @AlexGodofsky Well confirm any `data-rule-*` needs `="true"` using version 1.15.0
