### ISSUE TITLE
Problems with HTML step attribute of 0.01

### ISSUE THREAD

**Issue by tgljamesuk** [jquery-validation/jquery-validation#1764]
### Subject of the issue

Validating a number field with a step attribute of 0.01 produces unexpected results for me - e.g. 0.01, 0.02, 0.04 all validate, whereas other multiples of  0.01 such as 0.03, 0.05 don't.
### Your environment

jquery-validate 1.15.0
Chrome 49.0.2623.112 m
### Steps to reproduce

Enter 0.05 into this fiddle https://jsfiddle.net/9opste2z/ and submit
### Expected behaviour

It validates.
### Actual behaviour

It doesn't validate. Am I missing something?

**Comment by Arkni** [comment]
See #1760

**Comment by Arkni** [comment]
Fixed by #1809
