### ISSUE TITLE
Dynamic validation not working properly

### ISSUE THREAD

**Issue by its2mc** [jquery-validation/jquery-validation#1774]
### Checklist for this issue
- validator adding rules to all elements in a form, even if the selector is used on one element.
### Subject of the issue

I am adding rules dynamically using the validator plugin, but I am getting an issue where even though I added a rule to a specific element.. say 
                $("#cardONames").rules("add",{
                required: true
            });
or in the case of a class that only occurs once,
                $(".cc_ccv").rules("add",{
                required:true,
                digits: true
            });
The validator seems to add the same rules to all the elements on the form, even though if I call the jquery selector in the console I only get one element.. I just dont understand.. is there a way I can ignore the class instead?
### Your environment

Jquery 1.15.0
Chrome Version 49.0.2623.112 (64-bit)
### Steps to reproduce

make a form, add some elements, some with ids some without. Make a button that adds rules on click and removes them on click (basically toggles the rules on and off.)
### Expected behaviour

Should only add/remove rules for each element as specified.
### Actual behaviour

A rule that has only been made for one element will be applied to all he elements in the form, even if the classes/names are totally dfferent.

**Comment by staabm** [comment]
I guess your problem is related to your application or a mix of js code. Can you reproduce the issue on jsfiddle with a very simple/reduced example?

**Comment by ptflp** [comment]
How can i push dynamically array to validate? I'm using bootstrap wizard, in 1 step it works fine, but on next tabs always returns true. 
`
var array=[ 
1: {
Citizenship:"required",
Degreeobtained:"required",
Doe:"required",},
2: {
Fos:"required",
From:"required",
FromH:"required"
}
]
        onNext: function(tab, navigation, index){
			var x= validateStep(array[index]);
			console.log (x);
			return x;
       }
function validateStep(fs){
		console.log(fs);
    $(".wizard-card form").validate({
		rules: fs
	}); 

	if(!$(".wizard-card form").valid()){
    	//form is invalid
		return false;
	}
	else {
	       return true;
	}
}`

**Comment by ptflp** [comment]
How can i push dynamically array to validate? I'm using bootstrap wizard, in 1 step it works fine, but on next tabs always returns true. 
`
var array=[ 
 1: {
  Citizenship:"required",
  Degreeobtained:"required",
  Doe:"required"
 },
 2: {
  Fos:"required",
  From:"required",
  FromH:"required"
 }
]
        onNext: function(tab, navigation, index){
			var x= validateStep(array[index]);
			console.log (x);
			return x;
       }
function validateStep(fs){
		console.log(fs);
    $(".wizard-card form").validate({
		rules: fs
	}); 

	if(!$(".wizard-card form").valid()){
    	//form is invalid
		return false;
	}
	else {
	       return true;
	}

`

**Comment by jordan-enev** [comment]
If the added fields have same name (i.e. name="inputs[]") - the validation don't work. Here is a fiddle: http://jsfiddle.net/jordan_enev/31u5p7cy/

**Comment by qublibjohnny** [comment]
Is this still an issue? I'm experiencing the same problems as @jordan-enev with adding dynamic fields.

**Comment by Arkni** [comment]
@qublibjohnny jquery-validate requires every element to have a unique name per form. A lot of people has requested this feature but unfortunalety we have enough time to work on it and even the proposed fixes from the community only fix a portion of the issue. Untill I got some free time to work on it, this plugin will still require fields to have unique names.

Thanks for your patience :)
