### ISSUE TITLE
setDefaults bug

### ISSUE THREAD

**Issue by longxinH** [jquery-validation/jquery-validation#1776]
errorPlacement and success Will perform
`$.validator.setDefaults({
        errorPlacement: function(error, element) {
            console.log(error);
        },
        success: function(error, element) {
            console.log('ok');
        },
    });`

line 919 run errorPlacement and line 964 run success

**Comment by staabm** [comment]
I dont get what you are reporting here. Could you elaborate a bit what works and what doesnt? Example?

**Comment by RouR** [comment]
https://jsfiddle.net/3uznxttf/5/
