### ISSUE TITLE
Please add reverseElements option to reverse the result of elements(): useful for tooltip errors

### ISSUE THREAD

**Issue by cmanley** [jquery-validation/jquery-validation#1791]
### Subject of the issue

When using tooltips to display error messages, these are currently created in the same order as the elements occur in the form, because that's how the elements() method returns them. The problem with that is that when tooltips overlap on a single line with multiple inputs, then the right-most tooltips will overlap the left-most tooltips. I solved this by creating a "reverseElements" boolean option (default false) and a little array reverse block at the bottom of the elements() method.

This is the modified method in v1.15.0:

``` javascript
        elements: function() {
            var validator = this,
                rulesCache = {};

            // Select all valid inputs inside the form (no submit or reset buttons)
            var $elements = $( this.currentForm )
            .find( "input, select, textarea, [contenteditable]" )
            .not( ":submit, :reset, :image, :disabled" )
            .not( this.settings.ignore )
            .filter( function() {
                var name = this.name || $( this ).attr( "name" ); // For contenteditable
                if ( !name && validator.settings.debug && window.console ) {
                    console.error( "%o has no name assigned", this );
                }

                // Set form expando on contenteditable
                if ( this.hasAttribute( "contenteditable" ) ) {
                    this.form = $( this ).closest( "form" )[ 0 ];
                }

                // Select only the first element for each name, and only those with rules specified
                if ( name in rulesCache || !validator.objectLength( $( this ).rules() ) ) {
                    return false;
                }

                rulesCache[ name ] = true;
                return true;
            } );
            if (this.settings.reverseElements) {
                var a = $elements.get();
                a.reverse();
                $elements = $(a);
            }
            return $elements;
        },
```

Below is how tooltips look when the reverseElements = true, otherwise the rightmost tooltip will block the left one making the error impossible to read and the field covered.
![tooltips](https://cloud.githubusercontent.com/assets/591285/15637820/404cf268-2619-11e6-9ac2-8d363643453f.png)
B.t.w. that's generated from a jquery proxy plugin I recently made called validate-tooltipster that combines validate and tooltipster.

**Comment by staabm** [comment]
I dont think this is something which should be solved in jq-validate. Couldnt you solve it in your plugin instead?

**Comment by cmanley** [comment]
In order to do that, I'd need to create a subclass of validity wherein the elements() method is overridden. I don't think validity can be subclassed though as there are many references to $.validity within validity itself.

**Comment by staabm** [comment]
Could you show us a jsfiddle so we can get a clearer view what you are doing and what libs are involved?

**Comment by cmanley** [comment]
That's a lot of work to clarify something. What exactly isn't clear so that I can explain it in more detail?
When tooltips are displayed by tooltipster, then the most recently displayed tooltip will overlap the previous tooltip when they're in each others space.
By this logic, when the jquery-validation elements() method processes the form input elements in standard order and 2 adjacent elements trigger a tooltipster error, well then the rightmost tooltip will overlap the previous tooltip, since the right one is created after the left one.
That means that it can happen that the user can't read the whole tooltip for the left field, but also can't access the right field because the tooltip of the left field is blocking it.

Just imagine that the tooltips on the middle row in the screenshot above had opposite z-orders, then you'll understand the problem visually.

Attached are the proxy classes. 
validate-tooltipster combines tooltipster with validate.
validate-custom is specific to my site and adds on to validate-tooltipster.
[validate-tooltipster.zip](https://github.com/jzaefferer/jquery-validation/files/315217/validate-tooltipster.zip)
[validate-custom.zip](https://github.com/jzaefferer/jquery-validation/files/315219/validate-custom.zip)

**Comment by staabm** [comment]
From the initial picture I can only see what your visual problem is.
I am not familiar with the libs your code is using and I cant see why a reverse-elements option can help in your situation.

Since we already have way too much options and this kind of deature request wasnt necessary for any other user yet you need to convince me/us to add this option.

If you are not willing to invest the time to build a small fiddle which reproduces the issue and shows us the actual problem (for which maybe more elegant solitions exist), we will not change a line of code for the use case.

Did you try to report the same issue on the issue tracker of this tooltip plugin you are using?

**Comment by jaireina** [comment]
This seems to be very specific to that use case with those tooltips. I don't see why the plugin should change to adapt to it. This issue should be closed.
