### ISSUE TITLE
Required fields (without $Trim function) : whitespaces are now valid

### ISSUE THREAD

**Issue by newfylox** [jquery-validation/jquery-validation#1794]
### Update

I just noticed that it's been removed since version 1.14.0. I wonder why? If someone could explain me, because documentation says that blanks are invalid, which is not true when trying the demo. Thanks
### Input Required Fields accept whitespaces ($trim function is removed from v1.15.0)
- version of `jquery-validate` : 1.15.0
- which browser and its version : Chrome 50.0.2661.102 m

On version 1.11.0, validation of required has that block of code `$.trim(value).length > 0;` but with version 1.15.0, it's only `value.length > 0;`, so whitespaces are now valid. Maybe documentation is no more updated, or it's a real bug. I'm using your first demo on page https://jqueryvalidation.org/required-method, which says **Makes "field" always required. Nothing and blanks are invalid**. It seems wrong because a whitespace is valid, which shout be false (Because It was false in previous version of jQuery-validate ie. 1.11.0).
### Expected behaviour

A whitespace in an input field should be invalid.
### Actual behaviour

A whitespace in an input field is valid, which is bad.

**Comment by staabm** [comment]
the demo is wrong. we intenitionally removed the trim.

**Comment by newfylox** [comment]
I was updating my issue when you answered me :) Is there any reason why we removed the trim?

**Comment by staabm** [comment]
we dropped it with https://github.com/jzaefferer/jquery-validation/commit/2ad0ca82daf091fc692018b38e01e896fd304015 and for people which still require some kind of value modification pre-validation a transformation features was introduced.

see https://github.com/jzaefferer/jquery-validation/issues/1602

**Comment by newfylox** [comment]
Thanks!
