### ISSUE TITLE
Enhancement/fix bug on line 404

### ISSUE THREAD

**Issue by Surechun** [jquery-validation/jquery-validation#1795]
### Subject of the issue

In my project,I used bootstrap-table(https://github.com/wenzhixin/bootstrap-table/),and used x-editor(https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable) plugin for it,I put them in a form,when I append a row into bootstrap-table,and  click a cell for edit,the error occurence,the error in line 404 of _jquery.validate.js_file:
`var validator = $.data( this.form, "validator" ),
                    eventType = "on" + event.type.replace( /^validate/, "" ),
                    settings = validator.settings;`
**error msg**:jquery.validate.js:404 Uncaught TypeError: Cannot read property 'settings' of undefined

Beacuse the _validator_ is undefined,so I added a valid checking for _validator_ object,as follows:
`var validator = $.data( this.form, "validator" );
                if(validator==undefined)
                {
                    return;
                }`
sloved.
### Your environment

jQuery Validation Plugin v1.15.0
Current Chrome
### Steps to reproduce

according to _Subject of the issue_
### Expected behaviour

It should checking object is undefined or not.
### Actual behaviour

jquery.validate.js:404 Uncaught TypeError

**Comment by staabm** [comment]
Could you create a small jsfiddle which reproduces the issue?

**Comment by ltdeta** [comment]
i have made a simple fiddle
https://jsfiddle.net/ltdeta/2oxts9bj/

- pushing submit button valdiator is active
- pushing test button valdiator 'should' be destroyed
- selecting form element the error occure console.log
```
TypeError: validator is undefined
https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.js
Line 409
```

**Comment by jaireina** [comment]
It seems like you're trying to destroy the validator instance from that form using this line of code: `$.removeData(form,'validator');`

You should use the destroy method instead. 

Please see an updated fiddle and advise: https://jsfiddle.net/2oxts9bj/1/
