### ISSUE TITLE
Pressing "Alt Gr" triggers validation

### ISSUE THREAD

**Issue by iwasherefirst2** [jquery-validation/jquery-validation#1803]
### Subject of the issue

If I selected a field and press the "Alt Gr" key, the field  gets validated.
### Your environment
- Version of jQuery Validation Plugin: 1.15
-  Using Firefox 45.0.2
### Steps to reproduce

For example, go to the [demo page ](https://jqueryvalidation.org/files/demo/) and click on the field name. Enter "s" - no error appears so far. Now press "Alt Gr" and you suddenly get the error message _Please enter at least 2 characters._

Even worse, go to the next field and enter your email address. I have a german keyboard and I have to press "Alt Gr" + "Q" to enter the @ symbol. Therefore, when I enter any email, as soon as I enter the @ symbol I get the error message _Please enter a valid email address_.  This is very confusing, because "myemail" produces no error message but "myemail@" suddenly produces one. 
### Expected behaviour

A field should be validated only when the form is submitted or if the user enters something in a non-marked field, and tabs/clicks away from it (blur the field).
### Actual behaviour

A field also gets validated when pressing the "Alt Gr" key.

**Comment by Arkni** [comment]
That's strange. I just tested the demo following your steps and everything works as expected, see following screen-cast (tested in Chrome 50 and Firefox 46.0.1):
![anim](https://cloud.githubusercontent.com/assets/6888059/16204204/5aee440a-370d-11e6-9793-729036f394b9.gif)

Also, the `Alt Gr` key is ignored by this plugin alongside other keys, see https://github.com/jzaefferer/jquery-validation/blob/38310a1/src/core.js#L274-L300

**Comment by iwasherefirst2** [comment]
Thank you for testing it. I just checked it on Windows 7 on Chrome and Firefox and everything works as expected. In Ubuntu 14.04 LTS however, I get the strange behavior as explained above in Firefox ( I have all Add-ons disabled). Note that the problem occurs already when I only press <code>Alt Gr</code>

<img src="https://i.imgur.com/bRyqBOM.gif">

I also checked in on Chrome on Ubuntu, and there it works. So it only does not work on Ubuntu with Firefox. Can anyone reproduce this error on Ubuntu as well or is it just me?

**Comment by Arkni** [comment]
Forgot to mention that I used Ubuntu 14.04.4 LTS to do the tests. So, I guess there's something wrong in your part.

**Comment by iwasherefirst2** [comment]
I have still the same problem. Whenever I tab into a new field the content is selected when pressing ' Alt Gr'.

**Comment by iwasherefirst2** [comment]
@Arkni  thank you this was actually a browser related bug.
