### ISSUE TITLE
Form with non-unique element names and remote validator exception + proposed FIX

### ISSUE THREAD

**Issue by Mike120Git** [jquery-validation/jquery-validation#1804]
### Subject of the issue

Exception is thrown when validating input with **remote validator** when element **name is not unique** on the form (input is nested in some other elements with the same name).

The problem is related to usage of findByName function.
### Your environment
- jQuery Validation Plugin v1.15.0
- IE 11, Chrome
### Steps to reproduce

Look at my example code here:
https://plnkr.co/edit/93QhyqGer417qLPhflrJ?p=preview
### Expected behaviour

There are three elements with the same name="Nip" on the form (I am using some custom Angular components in my app), but only one input element to validate.
**Remote validator** returns false, so error label should appear for input[name=Nip].
The validator should ignore any element on the form, wchich it could not validate. 
It should look only for validatable elements, such as inputs and text areas. 
### Actual behaviour

Exception in line 995: 'Uncaught TypeError: Cannot read property 'replace' of undefined'
escapeCssMeta: function( string ) {
            return string.replace( /([\!"#$%&'()*+,./:;<=>?@[]^`{|}~])/g, "\$1" );
        },
because string is undefined.

The function findByName: function( name ) in line 1018 is called during validation, it returns three elements. In the next steps the first element from the collection is considered as input element, wchich is wrong.

When using simple "required" validator instead of remote, it works as expected - function findByName is not called at all.
### My solution

Change findByName function to look for elements, wchich are validatable (input, textarea).

```
    findByName: function( name ) {
        //var result = $( this.currentForm ).find( "[name='" + this.escapeCssMeta( name ) + "']" );
        var result = $( this.currentForm ).find( "textarea[name='" + this.escapeCssMeta( name ) + "'],input[name='" + this.escapeCssMeta( name ) + "']" );
        return result;
    },
```

The patch above solved my problem, but it could possibly break something else, if this function is used also for finding non-input elements - **so verify it please**.

I have included patched query.validate.debug.js, the patch in line 1021 is commented.
https://plnkr.co/edit/93QhyqGer417qLPhflrJ?p=preview

greetings
Mike

**Comment by seifsg** [comment]
This still persists in  v1.16.0 .
Why is this still open?
