### ISSUE TITLE
[Request] promise support

### ISSUE THREAD

**Issue by happyDemon** [jquery-validation/jquery-validation#1806]
### Subject of the issue

I'm writing an image dimension validation rule (for which I have to wait for the image to load in order to be able to check its width & height). Normally I'd make a promise and return that while the image is being loaded. Once the image is loaded it would be easy to resolve or reject the promise based on the defined dimension restrictions.

I thought the remote rule would be the same (since out of the box it returns a promise). but it only seems to return 'pending'.

is there an easy way for me actually implement this rule? or is a promise-based return value on the schedule?

I have implemented this in parsleyJS which was able to take a promise as a return, so I'm kind of confused why it's not possible here.
### Your environment

n/a
### Steps to reproduce

n/a
### Expected behaviour

n/a
### Actual behaviour

n/a

**Comment by staabm** [comment]
This library pre-dates promises in JS, so thats the reason why those are not yet supported.

I am open to discuss how a promise integration could look like though.

**Comment by happyDemon** [comment]
hopefully it shouldn't be too hard, switching out the "pending" handler with a promise handler is basically what needs to be done.
This promise handler would need to support jquery 1.x & 2.x flavoured promises and the standard JS promises (also featured in jquery 3).
After that a little rewrite of the remote rule and we're done.

I can get cracking on a pull request.

**Comment by staabm** [comment]
I would be ok to only support ES6 promises.

The change needs to be backwards compatible though.

**Comment by santiagodoldan** [comment]
@happyDemon were you able to implement something? I'd like to help if possible
