### ISSUE TITLE
Can't completely hide the label on success

### ISSUE THREAD

**Issue by nathanl** [jquery-validation/jquery-validation#182]
If an element is valid, I want its label to be hidden, so that it doesn't take up space. Currently, this seems to be impossible.

My first attempt was to use the `success` option to set a CSS class with `display: none;`. My second was, within the success callback, to explicitly call `hide()`.

Both of those fail because the `success` callback is called in the middle of `defaultShowErrors`, which ends by doing this: `this.addWrapper( this.toShow ).show();`. So in all cases, the label is shown.

My final attempt was to use the `showErrors` callback to do something like this:

``` javascript
  showErrors: function(errorMap, errorList) {
    this.defaultShowErrors();
    // after the label is shown, hide it again
```

But this won't work, because if the element is valid, neither errorMap nor errorList contains a reference to find the element and the label again.

As a workaround, I modified the plugin myself as follows: at the end of `defaultShowErrors`, I checked a custom setting and re-hid the error.

``` javascript
      var error = this.addWrapper( this.toShow ).show();
      if( !this.errorList.length && this.settings.hideLabelOnSuccess) {
        error.hide();
      }

```

_Is there a better way to do this?_ If not, is this a sensible modification to contribute back? It doesn't seem ideal to add another setting, but this is the best solution I have so far.

(The "shouldn't take up space requirement is my input is inside a table cell as part of a grid of calculations, and I'm putting the error message directly underneat the input inside the cell.)

**Comment by Neve12ende12** [comment]
Just wanted to point out 6 years later and now I am also trying to solve this problem.

**Comment by prancky** [comment]
i think this will help for you.

`success: function (element) {
            $(element).closest('.form-group').removeClass('has-error');
            element.remove();  
          }`

**Comment by AK3897** [comment]
> Just wanted to point out 6 years later and now I am also trying to solve this problem.

and 2 years after your comment i'm looking for solutions too :'D
