### ISSUE TITLE
Contenteditable  fails whan has not id or name

### ISSUE THREAD

**Issue by konradsikorski** [jquery-validation/jquery-validation#1835]
### Subject of the issue

When contenteditable element has not set id or name attribute than jquery.validation will throw error:
Uncaught TypeError: Cannot read property 'replace' of undefined

The content editable element must has some content.

Not sure is it a bug or feature but some many controls doesnt set this attributes.
### Your environment
- version of `jquery-validate` 1.5.1
- browsers: Edge, Chrome
#### (1) simple example

https://jsfiddle.net/_KoSiarz_/o3bcj3w7/
Repro steps:
- click on the contenteditabel element (to make it focuse)
- click outside content editable element (to lost focuse)
- error in console
#### (2) samle with fraola cotrol

https://jsfiddle.net/_KoSiarz_/t5g7qsmj/
Repro steps:
- click on the contenteditabel element (to make it focuse)
- click outside content editable element (to lost focuse)
- error in console
### Expected behaviour

content editable element with content and without id or name on lost focus should not throw any error
### Actual behaviour

content editable element with content and without id or name on lost focus is throwing error

**Comment by sparky672** [comment]
I don't quite understand why this is classified as a bug when the plugin mandates a `name` attribute on any element being validated.

**Comment by staabm** [comment]
@sparky672 is obviously right. Thanks.

**Comment by konradsikorski** [comment]
jquery-validation has many strange requirements that make it harder to use it properly. This is one of theme. Why the id or name is required? I just want to have a control on my page and validate it, what is wrong with that? Or if it is not supported than check the null and do not throw an error. In my opinion it is a bug.

**Comment by staabm** [comment]
We somehow need to identify the elements...

**Comment by sparky672** [comment]
Yes, the [documentation](https://jqueryvalidation.org/reference/#link-markup-recommendations) seems pretty clear to me:

>  Mandated: A 'name' attribute is required for all input elements needing validation, and the plugin will not work without this...

**Comment by konradsikorski** [comment]
ok than why you try to validate it, just omit inputs without id and name

**Comment by TheBigK** [comment]
I'm facing the exact issue. Is there a way to use both Froala editor and jQuery validation. Is there any way to make them work without producing error message?

**Comment by konradsikorski** [comment]
To workaround the bug you can use following code:
`jQuery.validator.setDefaults({
        ignore: "[contenteditable='true']"
    });`

This will disable validation on all contenteditable elements. Of course you can be more specific and add rule for contenteditable with empty name.

**Comment by TheBigK** [comment]
@konradsikorski - Thanks! I was able to get rid of the error by upgrading to the latest jQuery-Validation plugin. Looks like they've fixed the bug.
