### ISSUE TITLE
validate.showErrors.errorList elements miss optional method property in documentation

### ISSUE THREAD

**Issue by MaceWindu** [jquery-validation/jquery-validation#1848]
### Subject of the issue

https://jqueryvalidation.org/validate/ does not document method property for showErrors handler errorList parameter elements.
### Your environment
- version of `jquery-validate` : 1.15.1
### Expected behaviour

method property documented with notes on when it exists and when not
or
property removed

**Comment by staabm** [comment]
@MaceWindu I am not sure what you mean. the docs [1] describe the `showErrors`  function with both, `errorMap` and `errorList` parameters below.

[1] https://jqueryvalidation.org/validate/#showerrors

I will close this for now, feel free to discuss further or clarify in case I missed something.

**Comment by MaceWindu** [comment]
I'm talking about errorList parameter. It's documented as a list of  {message, element} objects, but in reality it contains {message, element, method} and {message, element } objects

**Comment by staabm** [comment]
Right.. There is one spot were we have one assitional property https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L840
