### ISSUE TITLE
validating a json object 

### ISSUE THREAD

**Issue by oceatoon** [jquery-validation/jquery-validation#1855]
i googled around , but the words seem mixed 
I was wondering if I could validate a json object with this pluggin 
I tried but didnt rely work , is something like this possible 

'''
var test = {name:"kiki",toto:"coco"};
test.validate({
        rules : {
            name : {
                required : true
            }
        },
        submitHandler : function(form) {
            alert("good");
            return false; // required to block normal submit since you used ajax
        },
        invalidHandler : function(event, validator) {//display error alert on form submit
            alert("bad");
        }
    });
''''

**Comment by staabm** [comment]
The primary use-case for the lib is form based validation.
However you can write a custom validation method which takes whatever global variable etc into account
