### ISSUE TITLE
Broken link to "Type: Validator"

### ISSUE THREAD

**Issue by Chealer** [jquery-validation/jquery-validation#1862]
https://jqueryvalidation.org/validate contains:

> validator
> Type: Validator
> The validator instance for the current form.

The link on "Validator" brings to http://api.jquery.com/Types/#Validator
That page exists, but does not contain a Validator anchor.

**Comment by Chealer** [comment]
I no longer work on a project using jquery-validation and do not know if the issue persists, but I very much disagree with automated ticket closure.

**Comment by bytestream** [comment]
This should be transferred to [jquery-validation/validation-content](https://github.com/jquery-validation/validation-content)
