### ISSUE TITLE
Localization files should use window.jQuery object instead of window.$ to allow them to work in noConflict mode.

### ISSUE THREAD

**Issue by rubenvincenten** [jquery-validation/jquery-validation#1874]
### Subject of the issue

As you may know, jQuery has a noConflict mode where $ is not assigned to jQuery. In particular, this is kind of a nag when writing plugins for wordpress, where jQuery is ran in noConflict mode by default.
### Steps to reproduce
1. Link jQuery.
2. `<script>jQuery.noConflict()</script>`
3. Try to link any localization files.
### Expected behaviour

jQuery validation messages should be translated using the location file you linked in step 3.
### Actual behaviour

You will get an error in the console:
`Uncaught ReferenceError: $`
### Suggested fix:

wrap all the files like this:

``` js
(function($){
   $.extend( $.validator.messages, {});
})(jQuery);
```

**Comment by staabm** [comment]
Hmm I thought that our build process would take care of that... need to check that

**Comment by Arkni** [comment]
This was already fixed by our build process. For anyone who is having the same issue, please make sure you're using the distribution files.
