### ISSUE TITLE
JQUERY Validation Plugin bug -- rule of min(value) does not respect the minimum value, if the value contains commas 

### ISSUE THREAD

**Issue by rchakravarti** [jquery-validation/jquery-validation#188]
Reference:  http://docs.jquery.com/Plugins/Validation/Methods/min#value
Validation Plugin Version 1.8.1
jQuery Core Version 1.5.1

To reproduce the bug:
On the Demo for the Validate a minimum of 13,
1) Enter the value 1,300 (1300 with a comma) with
the "min" rule in place, validation fails

Any number with a comma fails validation when the
"min" rule is in place, the validate plugin incorrectly reports an error

2) Remove the "min" requirement from the rule, and enter
1,300 (with the comma) -- the error goes away

Expected behavior:
The plugin should treat numbers with commas in  the same 
manner as numbers without commas.

---

The same issue was encountered using the "range" rule

Appreciate any reply to help on this issue

**Comment by piersh** [comment]
this is a joke. both issues #188 and #379 which have been unfixed for years are closed referring to each other as reasons for closing. yet this fix STILL has not made it into release.

**Comment by joeRinehart** [comment]
In case anyone hits this and needs a quick, U.S.-but-customizable fix, I already had numeral.js involved and using it to preformat values was a pinch:

https://gist.github.com/joeRinehart/0e8af523fdfc567cc670ddca2eaff137
