### ISSUE TITLE
How to validate idna encoded url

### ISSUE THREAD

**Issue by tonal** [jquery-validation/jquery-validation#1893]
### Subject of the issue
Valid national url `http://промсофт.рф` encoded to pynicode is `http://xn--l1adbbfiip.xn--p1ai`.

### Your environment
* 1.15.0
* Google Chrom  54.0.2840.100 (64-bit)

### Steps to reproduce
Go to https://jqueryvalidation.org/url-method/
Validate first and second url

### Expected behaviour
Both valid

### Actual behaviour
First is valid, bat second is not.

**Comment by Arkni** [comment]
The regex used by the `url` method is based on [`this gist`](https://gist.github.com/dperini/729294) (with a small change) which doesn't support the IDN urls (see https://gist.github.com/dperini/729294#gistcomment-1299190)

**Comment by staabm** [comment]
Feel free to provide a fix for this issue. we will only take it if it doesnt not make the implementation way more complex though.

**Comment by Arkni** [comment]
Quoting the author of the RegExp (https://gist.github.com/dperini/729294#gistcomment-1299190):

> the regexp already supports international URLs, just write them using natural UTF-8 encoding.
The following is the UTF-8 version of the URL you typed above:
http://папироска.рф
It would be hard to type or remember IDN URLs like the one you typed, nobody will do.
This has been written to validate URLs typed by users and/or found in log files.

The implementation of the `url` method is unlikely to change in the near future.

In case you need to accept those urls, please consider [`redefining`](https://jqueryvalidation.org/jQuery.validator.methods/) the `url` method with a custom RegExp.

I'm going to close this issue for now. Feel free to ask if you have follow up questions.
