### ISSUE TITLE
Mastercard new BIN range

### ISSUE THREAD

**Issue by mourawaldson** [jquery-validation/jquery-validation#1904]
Hi,
Is there any plan to start supporting new range of bin for mastercard?

https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html

Thanks.

**Comment by staabm** [comment]
Depending on the patch size required to support the new ranges I will accept a PR.

**Comment by Castle-XC** [comment]
I, too, would like to know if support for the new BIN range for Mastercard will be supported

**Comment by tritontech** [comment]
In the 'creditcardtypes' method update the mastercard case to include the new range.

`if ( validTypes & 0x0001 && (/^(5[12345])/.test( value ) || /^(2[234567])/.test( value ))) { // Mastercard`
