### ISSUE TITLE
remote validation with select drop downs marks all fields as valid

### ISSUE THREAD

**Issue by thinking2** [jquery-validation/jquery-validation#1907]
### Checklist for this issue
If your issue is about the regex used in `email` rule, please note that as of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use (https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.
In case you need to adjust the built-in validation regular expression patterns, please follow the documentation (http://jqueryvalidation.org/jQuery.validator.methods/).

### Subject of the issue
remote validation with select drop downs marks all fields as valid

### Your environment
* version of `jquery-validate` 1.15.0
* tested with firefox (50.1.0) and chrome (Version 55.0.2883.87 m (64-bit))

### Steps to reproduce
Tell us how to reproduce this issue. If pssible, please provide a working demo in JSFiddle 

Go to the following links and submit the empty form and you will see the bug

Working Example using validate.1.13.0
http://www.t2beta.com/sample-remote.asp
click submit without entering any values within the form and it marks the invalid and valid correctly

Bug Example using validate.1.15.0
http://www.t2beta.com/sample-remote-bug.asp
click submit without entering any values within the form and it marks the invalid fields but then quickly changes them back to valid colors with error description still showing. If you click off of it then shows invalid colors correctly. 

Working Bug Example without select using validate.1.15.0
http://www.t2beta.com/sample-remote-bug-no-select.asp
click submit without entering any values within the form and it marks the invalid fields correctly with no select field. 

### Expected behaviour
Tell us what should happen
after marking them invalid it should not remark them as valid

### Actual behaviour
it is marking them invalid and them changing them back to valid but still showing the error. This only happens with a select drop down field within the form

**Comment by snobo** [comment]
I think I have a similar or the same issue. By analyzing the source code, I noticed that in the `ajax.success` callback of the `remote` method, there is a call to `validator.resetInternals()` in case when the remote validation is successful. Which effectively marks all the form fields as valid, even if they are currently invalid. I think this is not correct - validation of a single element should not reset the whole form. If there are no secret drawbacks, maybe this call should be removed?

**Comment by FM1973** [comment]
Hello.

I got the same problem. As snobo I do think a single field validation should not reset the whole form.
