### ISSUE TITLE
Add method to check form without triggering errors

### ISSUE THREAD

**Issue by mririgoyen** [jquery-validation/jquery-validation#191]
I'm really looking for a way to check the form's validation status without triggering errors. Basically, we need something that just says "Yeah, this form is completely valid" or "No, it's not". The reason for this is we want to enable/disable the submit button based on the form's validation status. However, using the validate().checkForm() method triggers the errors to be displayed upon entering a field. I cannot figure a way to currently do this. If you could add a method that just gives a simple true/false, that would be most helpful.

**Comment by alexbooker** [comment]
I have the **exact** same requirement. 

I instantiated a validator: 

```javascript
var validator = $("..).validate();
```

And then in my event handler, I call `checkForm`: 
```javascript
validator.checkForm()
```
`checkForm` returns `true` if the form is valid without showing the errors. It is perfect. I just wonder, why is this not documented? Should it be?
