### ISSUE TITLE
Add docs for `Validator.destroy()` on the webpage.

### ISSUE THREAD

**Issue by d-ph** [jquery-validation/jquery-validation#1912]
### Subject of the issue
Add docs for `Validator.destroy()` on the webpage.

### Your environment
n/a

### Steps to reproduce
1. Go to https://jqueryvalidation.org/documentation/

### Expected behaviour
Webpage mentions the existence of `Validator.destroy()`

### Actual behaviour
Webpage doesn't mention the existence of `Validator.destroy()`

### Why this is needed
SPA devs want to know how to clean up the html for frontend navigation purpose. `Validator.destroy()` is the method they look for, but in order to discover it, they need to read, process and understand [this](http://stackoverflow.com/questions/9642384/jquery-validator-unbinding) instead of just getting the info from the the official docs.

I can PR myself. Just let me know it this is something you'd merge, please.

**Comment by staabm** [comment]
PR welcome at https://github.com/jzaefferer/validation-content ;-)

**Comment by xr280xr** [comment]
In what version was the destroy function added? Sorry, I don't know how to search for that on github. I am using 1.11.1 and destroy is not a function in it.

**Comment by staabm** [comment]
It was adddd in 1.14

https://github.com/jquery-validation/jquery-validation/commit/747890974caecf0a339f38963a239c3a2f4eb864
