### ISSUE TITLE
Validation does not re-initialize once the form is submitted

### ISSUE THREAD

**Issue by nbarquin** [jquery-validation/jquery-validation#1937]
### Checklist for this issue
Add a function that allows validation to run after from submit - multiple form submits

### Subject of the issue
The validation messages do not display after the form is submitted

### Your environment
1.13.0
Chrome 55.0.2883.87

### Steps to reproduce
o Start with a freshly refreshed page/form with blank fields
o Tab through the fields – no validation messages will display
o Fill in valid info for all fields except for one (such as your email address)
o Attempt to submit – validation message will appear
o Fix the invalid field(s) and submit – form will submit
o Tab through the fields – the fields that failed validation before will have their validation message displayed when they are tabbed to

Demo: http://www.foambymail.com/blog/how-to-create-the-ultimate-cozy-bedroom-this-winter/?test=1 (click on mail icon)

### Expected behaviour
vlaidation messages should appear
### Actual behaviour
validation messages do not appear

**Comment by Arkni** [comment]
Can you test with the latest version `1.16.0` and see if the same issue appears ?

**Comment by nbarquin** [comment]
are you hosting the script somewhere? I currently have: ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js tried ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js but didn't work

**Comment by staabm** [comment]
I somehow forgot that we had connectivity problems and the website wasn't up2date.

just published the latest release on the website https://jqueryvalidation.org/
