### ISSUE TITLE
Cannot read property 'settings' of null

### ISSUE THREAD

**Issue by ethorz** [jquery-validation/jquery-validation#1938]
Hi! 
I have a dinamically form, created via ajax. After first submit - not has errors, but on second call, if try to $.validate - in console.log displayed error "Cannot read property 'settings' of null" on **settings = validator.settings;** 
```
function delegate( event ) {
	var validator = $.data( this.form, "validator" ),
		eventType = "on" + event.type.replace( /^validate/, "" ),
		settings = validator.settings;
         if ( settings[ eventType ] && !$( this ).is( settings.ignore ) ) {
	     settings[ eventType ].call( validator, this, event );
        }
}

```
I try clean old validator and init new options, but settings is undefined.

```
$('form').data('validator', null);
$("form").unbind('validate');

var validator = $("form").validate(formOpts);
```

jquery.validate v. 1.15.0
jquery 2.2.2
Chrome 55.0.2883.87 m

**Comment by Arkni** [comment]
Please provide a [`JSFiddle`](https://jsfiddle.net/)

**Comment by Arkni** [comment]
@ethorz 
Any reason why you closed this issue ?
Did you find a solution ? Care to share ?

**Comment by ethorz** [comment]
@Arkni

No, the problem was not in the validator. There the validate plugin works good. The error was in my code. 

Thank you.

**Comment by Arkni** [comment]
Thanks!

**Comment by masfelix** [comment]
@ethorz . can explain error in your code, i am the same error.
