### ISSUE TITLE
Add method is not working for me ...

### ISSUE THREAD

**Issue by kkashou** [jquery-validation/jquery-validation#1943]
I created a simple jsfiddle to show my issue ... https://jsfiddle.net/om9wgcfh/ 

For some reason my multiemail add method is not being called and I am not sure why. I am just trying to validate a text field that allows users to type in multiple emails up to 5 max and comma separate them. 

Any help would be great!

Thanks

**Comment by Arkni** [comment]
Change the type of the input from `type="email"` to `type="text"`, otherwise `jQuery-validation` will attach to it the `email` validator, which will be executed before your validator. And, in case the entered text is not a valid mail, `jQuery-validation` will always stop at `email` validator level.

**Comment by kkashou** [comment]
Thank you very much! :) Both option works perfect for what I need.

**Comment by Arkni** [comment]
You're welcome :)

**Comment by amuagarwal** [comment]
Hi

I am facing the same issue with select nothing is working for me the method added is nto getting fired. my code is as follow:
HTML:
`<select id="ExamId" name="ExamId" class="validate" title="" required>
    <option value="" disabled selected>Select Exam</option>
    <option value="1" >option 1</option>
    <option value="2" >option 2</option>
</select>`

Javascript:
`$.validator.addMethod('SelectRequired', function (value, element) {
            alert("I am in check select");
        }, "");

var validator = formToValidate.validate({
            rules: {
                ExamId: "SelectRequired"
            }
        });
        var isValid = formToValidate.valid();`


but the "SelectRequired" method is not firing in any browser.
