### ISSUE TITLE
 Url validation should pass if it's not required, what should I do?

### ISSUE THREAD

**Issue by OzanKurt** [jquery-validation/jquery-validation#1945]
```
            "action_button[action]": {
                "laravelValidationRemote": [
                    ["RequiredIf:hasActionButton,1", ["action_button[action]", "eyJpdiI6IjFZeTBQanp1TzdZT0gzQVpSMjM5b0E9PSIsInZhbHVlIjoiSjRQREVmeGFjeEJhZ0hcL0srMXR3SnlHVTNIZmZRK0Q1RkZuV0xFeXBQOWF6ODluQmZRRGZsMVIxb1U5MVVWTFhxRmFZK1REVU8yMjA4c2lFTFwvRXVrUT09IiwibWFjIjoiNGIwY2QzZGE5NDlmMjBjMDI1N2YwYTdlN2M0Mjk2ZDg5ODZhNTU3NWUzZmZhYjFjZTY4Y2M5NjhkNjI2ZDVjNSJ9", false], "validation.required_if:has_action_button,1", false]
                ],
                "laravelValidation": [
                    ["Url", [], "The action button.action format is invalid.", false]
                ]
            }
```

Url validation should pass if it's not required, what should I do?

jQuery Validation Plugin v1.14.0

**Comment by OzanKurt** [comment]
👍

**Comment by staabm** [comment]
the initial reported issue seems to be related to a product/framework which is build on top of jQuery Validation. the syntax example described above is not something you usually achieve with jQuery Validation.

until we get more information on how to reproduce the reported issue, a jsfiddle or similar, or more infos about the context, we cannot help you.

feel free to provide more information and we can re-open the issue at any time.
