### ISSUE TITLE
A rule for contenteditable element cannot be assigned via .validate()

### ISSUE THREAD

**Issue by sparky672** [jquery-validation/jquery-validation#1946]
### Subject of the issue
The `contenteditable` element is only validated when the rule is assigned via one of the inline attribute methods.  When the rules is assigned via the `rules` object of `.validate()` or via the `.rules()` method, it is ignored.   Any custom message of this rule assigned via the `messages` object is also ignored.

### Your environment
* jQuery Validate 1.16.0

### Steps to reproduce
Rule assigned via HTML5 attribute (working):  [jsfiddle.net/eL8051Lr/3/](https://jsfiddle.net/eL8051Lr/3/)
Rule assigned via inline class (working): [jsfiddle.net/eL8051Lr/2/](https://jsfiddle.net/eL8051Lr/2/)
Rule assigned via `.validate()` method (**not** working):  [jsfiddle.net/eL8051Lr/ ](https://jsfiddle.net/eL8051Lr/ )
Rule assigned via `.rules()` method (**not** working):  [jsfiddle.net/eL8051Lr/4/
](https://jsfiddle.net/eL8051Lr/4/
)
### Expected behaviour
Should be able to assign a rule for a `contenteditable` element via the `.validate()` and `.rules()` methods, no different than an `input`, `select`, and `textarea`.

### Actual behaviour
As per jsFiddle demos above, rules for a `contenteditable` element can only be assigned via a `class` or HTML5 attribute.

**Comment by Arkni** [comment]
Here is a fix for this issue:
```patch
 src/core.js | 13 ++++++++++++-
 1 file changed, 12 insertions(+), 1 deletion(-)

diff --git a/src/core.js b/src/core.js
index febd8d6..e7f3b8c 100644
--- a/src/core.js
+++ b/src/core.js
@@ -121,7 +121,16 @@ $.extend( $.fn, {
 			settings, staticRules, existingRules, data, param, filtered;

 		// If nothing is selected, return empty object; can't chain anyway
-		if ( element == null || element.form == null ) {
+		if ( element == null ) {
+			return;
+		}
+
+		if ( !element.form && element.hasAttribute( "contenteditable" ) ) {
+			element.form = this.closest( "form" )[ 0 ];
+			element.name = this.attr( "name" );
+		}
+
+		if ( element.form == null ) {
 			return;
 		}

@@ -384,6 +393,7 @@ $.extend( $.validator, {
 				// Set form expando on contenteditable
 				if ( !this.form && this.hasAttribute( "contenteditable" ) ) {
 					this.form = $( this ).closest( "form" )[ 0 ];
+					this.name = $( this ).attr( "name" );
 				}

 				var validator = $.data( this.form, "validator" ),
@@ -617,6 +627,7 @@ $.extend( $.validator, {
 				// Set form expando on contenteditable
 				if ( this.hasAttribute( "contenteditable" ) ) {
 					this.form = $( this ).closest( "form" )[ 0 ];
+					this.name = name;
 				}

 				// Select only the first element for each name, and only those with rules specified
```

**Comment by Arkni** [comment]
PR: #1947
