### ISSUE TITLE
Homepage: Current version outdated (1.15.0 superceded by 1.15.1)

### ISSUE THREAD

**Issue by Chealer** [jquery-validation/jquery-validation#1948]
According to [the homepage](https://jqueryvalidation.org/), the current version is 1.15.0. This version was superceded by 1.15.1 in July: https://github.com/jzaefferer/jquery-validation/releases/tag/1.15.1

This issue occurs intermittently since at least October. At times, the right version is shown. This issue was previously reported in ticket #1881.

**Comment by staabm** [comment]
This is ancloudflare caching issue in my eyes.. the latest version is 1.16.0

Maybe some of you guys could also make some noise
https://twitter.com/markusstaab/status/827206737799286786
