### ISSUE TITLE
Email rule not catering for Unicode characters as required by HTML standard spec

### ISSUE THREAD

**Issue by medmondson** [jquery-validation/jquery-validation#1949]
### Subject of the issue
Email rule not catering for Unicode characters as required by [the HTML standard spec](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address)

### Your environment
* jquery-validate v1.15.1
* Google Chrome 56.0.2924.87

### Steps to reproduce
The following email address is being considered invalid:

`óscar@yahoo.com`

To test:
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test( 'óscar@yahoo.com' );

### Expected behaviour
As per [the specification ](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address): 

> A valid e-mail address is a string that matches the email production of the following ABNF, the character set for which is **Unicode**.

### Actual behaviour
Because the regex is testing for the a-z A-Z range it is not correctly considering unicode characters, causing the above e-mail address to incorrectly fail validation.

If you would like any more details, including how it was discovered, please [check my original stackoverflow question](http://stackoverflow.com/q/42164543/436028).

**Comment by staabm** [comment]
we use the regex proposed by the spec you are linking, see https://github.com/jquery-validation/jquery-validation/blob/cf925cf21bad2b305e2611a5e4baeb3ef9c35d02/src/core.js#L1348

**Comment by medmondson** [comment]
The problem is a-zA-Z0-9.!#$%&' doesn't allow for non-ascii Unicode characters

**Comment by staabm** [comment]
@medmondson where did you found the regex from your example? its a different one we use internally (even if our doesnt work with the mentioned email address nevertheless)

**Comment by medmondson** [comment]
@staabm - EmailAddress attribute, [I highlighted the line](https://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/EmailAddressAttribute.cs,54) above.

**Comment by RobJohnston** [comment]
So the existing e-mail address validation covers [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.4.1) but not [RFC 6530](https://tools.ietf.org/html/rfc6530#section-4.2).  The method of validation to use depends on if the mail server in question can handle the new spec [SMTPUTF8](https://en.wikipedia.org/wiki/Extended_SMTP#SMTPUTF8).

Could the solution be as simple as a new function like [email](https://github.com/jquery-validation/jquery-validation/blob/master/src/core.js#L1356), but called something like **emailUTF8**?

Background:  
* https://stackoverflow.com/a/42204217/4930982
* https://en.wikipedia.org/wiki/Email_address#Internationalization

**Comment by staabm** [comment]
yep, having a separate email method sounds like the way to go

**Comment by RobJohnston** [comment]
Yes, I struggled to find a good name.  I suggested **emailUTF8** because it mimics the new spec **SMTPUTF8**.  

Deciding on the name is the hardest part... are you suggesting **email6530**, **emailRFC6530**, or something else?

**Comment by RobJohnston** [comment]
Wait a second... once something passes jQuery Validation, it's going to be subjected to the browser's built-in validation.  I don't see this passing that test.

I put "óscar@yahoo.com" into the following form and got stopped by the browser every time:

- IE 11: "You must enter a valid email address."
- Chrome 61: "A part followed by '@' should not contain the symbol 'ó'.
- FireFox 52: "Please enter an email address."

I've read that it may pass in Opera.

```html
<html>
<head>
    <title>Test</title>
</head>
<body>
    <form action="#">
        <input type="email" name="email1" id="email1" />

        <button type="submit">Submit</button>
    </form>
</body>
</html>
```

**Comment by Ponant** [comment]
Hi,
I am hitting a similar situation here https://github.com/aspnet/AspNetCore/issues/9107
it is important to validate the unicode of the domain more than the local part of an email because the latter is prohibited in unicode in Edge Chrome and FF. Hence a better example to the given above is to test a@ü.com and allow that to validate.
