### ISSUE TITLE
Code change for Email Rule

### ISSUE THREAD

**Issue by dbonness** [jquery-validation/jquery-validation#1958]
I wrote a work around for the known email validation issue, you can get the update dist file here if you would like to use it.
https://github.com/dbonness/jquery-validation/commit/a95f30ba4248b50da1d59518716b61e57942488f

**Comment by staabm** [comment]
See the README.md for details.

> **IMPORTANT NOTE ABOUT EMAIL VALIDATION**. As of version 1.12.0 this plugin is using the same regular expression that the [HTML5 specification suggests for browsers to use](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider [using a custom method](http://jqueryvalidation.org/jQuery.validator.addMethod/).
In case you need to adjust the built-in validation regular expression patterns, please [follow the documentation](http://jqueryvalidation.org/jQuery.validator.methods/).

**Comment by dbonness** [comment]
I read this and I am not asking you to change it I just wanted to give people a file that actually worked correctly to download and use. Thanks

**Comment by staabm** [comment]
there is no need to change anything in the lib. you just can define whichever email pattern you like as described in the docs https://jqueryvalidation.org/jQuery.validator.methods/
