### ISSUE TITLE
Credit Card Validation Error

### ISSUE THREAD

**Issue by dbonness** [jquery-validation/jquery-validation#1959]
When using the creditcard validation it returns and error in the jquery.validation.js. It will say this field required since I am requiring it but after that is does nothing. It will not except anything as valid.

Here is the markup:
`    $('#orderForm').validate({
        rules:{
            creditCardNumber:{
                required: true,
                creditcard: true
            }
        }
    });`

Here is the error:
`Uncaught TypeError: Cannot read property 'call' of undefined.  Exception occurred when checking element , check the 'creditCard' method.
    at $.validator.check (jquery.validate.js:754)
    at $.validator.element (jquery.validate.js:479)
    at $.validator.onkeyup (jquery.validate.js:317)
    at HTMLInputElement.delegate (jquery.validate.js:406)
    at HTMLFormElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLFormElement.q.handle (jquery-3.1.1.min.js:3)`

**Comment by Arkni** [comment]
`creditcard` method is not part of the core, you should include the additional methods to get it.

**Comment by dbonness** [comment]
Thanks, the additional methods are already included, still has the same issue.

**Comment by Arkni** [comment]
I just did a re-read of the error. I think you made a typo: `creditCard` => `creditcard` (all lowercase)

**Comment by dbonness** [comment]
My original post had creditCard, I was trying this to see if this was the error. However I tried both ways and originally had it spelled creditcard. Still gave me the error.

**Comment by Arkni** [comment]
Please create a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) so we can see where the error is.

**Comment by Arkni** [comment]
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the question or request made to them ~2 months ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!
