### ISSUE TITLE
If a form haven't a validator, an error is thrown

### ISSUE THREAD

**Issue by Raystorm7** [jquery-validation/jquery-validation#1963]
Hello, 
I have a form without validator but when I blur a field, the validator check the file but thrown an error because the validator wasn't found.

The code that goes in error is:

function delegate( event ) {
// Set form expando on contenteditable
   if ( !this.form && this.hasAttribute( "contenteditable" ) ) {
	 this.form = $( this ).closest( "form" )[ 0 ];
    }
	var validator = $.data( this.form, "validator" ),
		eventType = "on" + event.type.replace( /^validate/, "" ),
                **settings = validator.settings;**
        if ( settings[ eventType ] && !$( this ).is( settings.ignore ) ) {
		settings[ eventType ].call( validator, this, event );
	}
}

At **settings = validator.settings**, the  validator variable is undefined.

How can I solve this?

Thanks!

**Comment by Arkni** [comment]
Please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a reproducible example.

**Comment by Arkni** [comment]
@Raystorm7 

Any reason why you closed this issue ?
Did you find a solution ? Care to share ?

**Comment by Raystorm7** [comment]
@Arkni, yes. It's a work project, too code to reproduce on jsfiddle, too many libraries to include and to test, I haven't much time to do.
Thanks anyway! :)
