### ISSUE TITLE
'pattern' validator should not add ^...$ to string-based regex

### ISSUE THREAD

**Issue by alexweissman** [jquery-validation/jquery-validation#1967]
The [`pattern`](https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/pattern.js) rule [now accepts](https://github.com/jquery-validation/jquery-validation/issues/223) either a Javascript regex literal or a string, as per the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp).

However the thing I'm not clear on, is why it wraps string-based regex's in `^...$`.  This seems to be unnecessarily limiting.  Shouldn't the `^...$` be added by the consumer if desired?

**Comment by alexweissman** [comment]
Looking at `pattern.js` on the master branch, this appears to still be a problem.

**Comment by Arkni** [comment]
Sorry about the comments from the bot.

I don't really have the time to work on this issue, but if you or anyone can, we welcome any PR :)

**Comment by Lexmark-haputman** [comment]
This is the way that the pattern attribute works in HTML. From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern)
> The pattern's regular expression, when matched against the value, must have its start anchored to the start of the string and its end anchored to the end of the string, which is slightly different from JavaScript regular expressions: in the case of pattern attribute, we are matching against the entire value, not just any subset, as if a ^(?: were implied at the start of the pattern and )$ at the end.

This is as defined in the [HTML Spec](https://html.spec.whatwg.org/multipage/input.html#attr-input-pattern)

**Comment by bytestream** [comment]
It would be a breaking change to change it now. You can always add your own validator method.
