### ISSUE TITLE
addMethod documentation change

### ISSUE THREAD

**Issue by brow416** [jquery-validation/jquery-validation#1968]
This is a minor request for clarifying the documentation on this page: https://jqueryvalidation.org/jQuery.validator.addMethod/

The issue is that the description for the method does not clearly indicate the value that should be returned by the custom function. If it said to return true when the validation passes and false when it fails, it would be helpful.

I had to Google for about 15 minutes to figure it out, and a simple sentence or two added to the documentation would help. Thank you for your consideration!

**Comment by jaireina** [comment]
In the description of the **method** parameter it starts with: 

> The actual method implementation, returning true if an element is valid.
