### ISSUE TITLE
Chrome - submit param lost if submitHandler is set and child element of submit button is clicked.

### ISSUE THREAD

**Issue by Wrongusername** [jquery-validation/jquery-validation#1969]
Codepen : https://codepen.io/Wrongusername/pen/NpbyLW

Param is lost when temporary hidden input is added before submitHandler call;

Bug originates here.

this.on( "click.validate", ":submit", function( event ) {
				if ( validator.settings.submitHandler ) {
					validator.submitButton = event.target;
				}

Possible solution - use document.activeElement instead of event.target,

Looks like click.submit only works as intended in Firefox, in IE/Chrome event.target is actual child element.

**Comment by Arkni** [comment]
Fixed by #1901
