### ISSUE TITLE
Strange behavior on required fields

### ISSUE THREAD

**Issue by francoism90** [jquery-validation/jquery-validation#1975]
### Subject of the issue
Required (error) message not always showing when:
1. A required field is already filled in
2. Make it empty
3. Tab to next field -> no error message
4. Tab to previous -> no error message
5. Fill in something, and empty the field -> now the required message popups

### Your environment
* version of `jquery-validate`: 1.16.0
* which browser and its version: Firefox 52

### Steps to reproduce
http://jsfiddle.net/f2obn9e1/

### Expected behaviour
Error message should this display on first 'empty'

### Actual behaviour
(Error) message visible on second attempt

**Comment by dglooker** [comment]
I think this issue stems from the onfocusout event handler:

onfocusout: function( element ) {
                        if ( !this.checkable( element ) && ( element.name in this.submitted || !this.optional( element ) ) ) {
				this.element( element );
			}
		},

The call to  this.optional( element )   returns either true or 'dependency-mismatch' ,  so !this.optional( element ) always evaluates to false,  which I'm assuming is a bug.  The element() check gets skipped tabbing through the form until the element makes it into this.submitted .

I changed the if condition to:

if ( !this.checkable( element ) && ( element.name in this.submitted || this.optional( element )==='dependency-mismatch') ) {

which triggers the element() check as expected for required fields. 


Its not clear to me though what 'dependency-mismatch' means so I'm not sure if this the correct (or only) change needed to solve this problem.

**Comment by evilnes** [comment]
Behavior still present in 1.17.0

My required fields are not triggering error state when cleared of their initial value.

**Comment by allpassos** [comment]
i'm confirm the issue present as of v1.19.3. and the solution gave by https://github.com/jquery-validation/jquery-validation/issues/1975#issuecomment-360350493 fix my error. i dont know the consequences and ill go throught with care, my app is huge and for now i detect this issue at this point.
In my case the issue occurs when you have the field already validated and then focusout and focusin the input field. I figureout that not only focusout and focusin reproduce the error, also keybords shortcuts. 
If this thread grows , ill still reporting
