### ISSUE TITLE
email validation with "name@domain"

### ISSUE THREAD

**Issue by TorosyanV** [jquery-validation/jquery-validation#1979]
In `/test/methods.js
`
`assert.ok( method( "name@domain" ), "Valid email" );`
why? 

**I think it's invalid**

**Comment by TorosyanV** [comment]
valid regex for email use
`  $.validator.methods.email = function( value, element ) {
            return this.optional( element ) || /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test( value );
        }`

**Comment by Arkni** [comment]
See the `README.md` for details.

> **IMPORTANT NOTE ABOUT EMAIL VALIDATION**. As of version 1.12.0 this plugin is using the same regular expression that the [HTML5 specification suggests for browsers to use](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider [using a custom method](http://jqueryvalidation.org/jQuery.validator.addMethod/).
In case you need to adjust the built-in validation regular expression patterns, please [follow the documentation](http://jqueryvalidation.org/jQuery.validator.methods/).
