### ISSUE TITLE
Google's Invisible reCaptcha submit form & fields validation issue

### ISSUE THREAD

**Issue by dev-101** [jquery-validation/jquery-validation#1980]
### Subject of the issue
When we bind invisible captcha via class to submit button, it no longer validates the form on submit, instead captcha takes precedence over the button, launches captcha even when required fields are not filled-in and blank form can be submitted.

### Your environment
- latest version (1.16): makes no difference
- browser independent behavior

### Steps to reproduce

Here's the most important part:

```
invalidHandler: function(form, validator) {
	$('html,body').animate({ scrollTop: $('h1').offset().top }, { duration: 250, easing: 'swing'});
},
submitHandler: function(form){
	$('button[type=submit], input[type=submit]').attr('disabled', 'disabled');
	form.submit();
}
```

submitHandler shoud disable the button, yet it does not work anymore when captcha's script is loaded.

### Expected behaviour
Submit button action should be prevented if the form is blank, required fields are empty or invalid.

### Actual behaviour
Already described.

**Comment by BassemN** [comment]
Did you find a solution for your issue?

**Comment by dev-101** [comment]
No

**Comment by cameroncz** [comment]
Same issue here.., no solution found yet

**Comment by pagelab** [comment]
You can integrate the JQuery Validation by [programmatically invoking the ReCapcha challenge](https://developers.google.com/recaptcha/docs/invisible#explicit_render).

See [this StackOverflow topic.](https://stackoverflow.com/questions/43872550/google-invisible-recaptcha-on-multiple-forms-in-a-same-page-php/)

**Comment by HorlogeSkynet** [comment]
This problem still exists in 2018.

**Comment by jebaited** [comment]
Is there any solution for this?

**Comment by HorlogeSkynet** [comment]
Check the workaround linked 3 messages above 👍

**Comment by HeishPi** [comment]
We're in February, 2019, and this problem still exists, even with reCaptcha v3

**Comment by luigitek** [comment]
October, 2019... issue persists.

![images-2](https://user-images.githubusercontent.com/41933828/66505421-fc43c200-ea90-11e9-9efe-60c0a6d8280d.jpg)
