### ISSUE TITLE
has-error does not correctly placing..

### ISSUE THREAD

**Issue by codeigniterd** [jquery-validation/jquery-validation#1986]
jQuery JavaScript Library v3.2.1
jQuery Validation Plugin v1.16.0

### Subject of the issue
```
<form id="loginForm" action="" method="post">
            <div class="form-group">
              <input class="form-control" placeholder="Email" name="email" type="email">
            </div>
            <div class="form-group">
              <input class="form-control" placeholder="Password" name="password" type="password" >
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
              </div>
            </form>
```
Error Message is not correctly showing..
`<form id="loginForm" action="" method="post" novalidate="novalidate">
            <div class="form-group">
              <input class="form-control error" placeholder="Email" name="email" aria-required="true" aria-invalid="true" type="email"><label id="email-error" class="error" for="email">We need your email address to login</label>
            </div>
            <div class="form-group">
              <input class="form-control error" placeholder="Password" name="password" aria-required="true" type="password"><label id="password-error" class="error" for="password">We need your password</label>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <div class="icheckbox_square-blue" style="position: relative;"><input style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;" type="checkbox"><ins class="iCheck-helper" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;"></ins></div> Remember Me
                        </label>
                    </div>
                </div>
              </div>
            </form>
![screenshot-localhost-2017-04-04-04-27-37](https://cloud.githubusercontent.com/assets/21235643/24635124/3893a34a-18ef-11e7-8dfb-abc78994cf17.png)
`

**Comment by codeigniterd** [comment]
![screenshot-localhost-2017-04-04-04-27-37](https://cloud.githubusercontent.com/assets/21235643/24635147/5efeec06-18ef-11e7-95e5-8bfc40daf90a.png)

**Comment by codeigniterd** [comment]
error message is not showing in red.. as i have found .has-error does not placing beside form-group class correctly.

**Comment by Arkni** [comment]
I don't know why you closed this issue, but I think this example can help you:
- source code: [`/demo/bootstrap/index.html`](https://github.com/jzaefferer/jquery-validation/blob/master/demo/bootstrap/index.html)
- live demo: https://rawgit.com/Arkni/jquery-validation/demos/demo/bootstrap/index.html
