### ISSUE TITLE
This is the worst document I've ever seen

### ISSUE THREAD

**Issue by konohanaruto** [jquery-validation/jquery-validation#1987]
I do not know how to start using it...

**Comment by nebrot** [comment]
See docs https://jqueryvalidation.org/documentation/ or ask for help at http://stackoverflow.com/

**Comment by Arkni** [comment]
The documentation's source code can be found in [`jquery-validation/validation-content`](https://github.com/jquery-validation/validation-content). Feel free to open a PR to make it documentation more comprehensible and easy to read/use.

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
