### ISSUE TITLE
Number validation Time 00:00 to 23:59 over steps 59.

### ISSUE THREAD

**Issue by weedkiller** [jquery-validation/jquery-validation#1988]
Hi, I setup the textbox validation of type `number` with min and max values, I am unable to create the validation so that the mins do not exceed 59 (since there are 60 mins in an hour).

- What configuration should I set to ensure the time values get `validated between 00:00 to 23:59`
- Is it possible to allow either `.` decimal or `:` as a separator?

Thanks

**Comment by rohittiwarirvt** [comment]
Hi @weedkiller ,
I am able to do what u r trying to do check this
`https://jsfiddle.net/rohittiwarirvt/1jshebge/3/`

you need to use additional `https://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.min.js` for the time method

- [ ]

**Comment by weedkiller** [comment]
Thanks @rohittiwarirvt is it possible to accept either decimal or colon in the rule.

Also, I do want to force the user to end HH:MM ... it would be better if he was simplay able to enter... a number (hours, without the minutes) and then it POST with zeros...

See I am trying to capture the time he worked...

**Comment by rohittiwarirvt** [comment]
@weedkiller can you put an example, i didn't get it ?

**Comment by Arkni** [comment]
You can use the [`time`](https://github.com/jquery-validation/jquery-validation/blob/ddaed1ccb5768478c480e331ff7ca57f19a6197a/src/additional/time.js) method, it's part of the `additional method`.


> Also, I do want to force the user to end HH:MM ... it would be better if he was simplay able to enter... a number (hours, without the minutes) and then it POST with zeros...

You can use the [`normalizer`](https://jqueryvalidation.org/normalizer/) to transform the entered value before hitting the validation.

As for posting with zeros, it's up to you to append them before submitting the form.

**Comment by weedkiller** [comment]
@Arkni `time` is a bad idea - its still not supported in Firefox and IE, plus the behaviors in Chrome and Edge are very different. Thats why I am trying to do something simple

@rohittiwarirvt - I do NOT want to force the user to enter HH:MM ... _I can/want to let user type just the hours as well like a simple number for e.g. 12 or 8_

**Comment by Arkni** [comment]
You got me wrong. I wasn't talking about the HTML `time` element. I was referring to the validation method `time` which is part of the `additional methods`. 

It can be used as follow:
```js
$("form_selector").validate({
  rules: {
    inputName: {
      time: true
    }
  }
})
```


> I do NOT want to force the user to enter HH:MM ... I can/want to let user type just the hours as well like a simple number for e.g. 12 or 8

As I said you can use the [`normalizer`](https://jqueryvalidation.org/normalizer/) layer to transform your input value, and the resulting value will be then used in validation. Something like this:
```js
$("form_selector").validate({
  rules: {
    inputName: {
      time: true,
      normalizer: function(currentValue) {
        var isSimpleNumber = /^([01]\d|2[0-3]|[0-9])$/.test(currentValue);
        // Append ":00" in case the user entered a simple number between 00 and 23
        return isSimpleNumber ? currentValue + ":00" : currentValue;
      }
    }
  }
})
```

**Comment by rohittiwarirvt** [comment]
Cool @Arkni . Thanks, i didn't knew this

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
