### ISSUE TITLE
Add rules to input without name on the fly

### ISSUE THREAD

**Issue by ramiromd** [jquery-validation/jquery-validation#1989]
Hi all !, i found a problem adding a validators to elements without name attribute. In my case, the elements are the credit card number and the card verification code.

Those elements haven't got a name because, i don't want send their values to the server.

To add validators i am using the below code snippet:

```javascript
viewCache.$ccNumber.rules('add', {
   creditCardNumber: true
});

viewCache.$ccCvc.rules('add', {
   creditCardCvc: true
});
```

When add validators on the fly with jQuery Validation plugin, the plugin checks the name of the element to bind the added validator.

So, the full rules for my form was:

```json
{
   // other rules
   ...
   // all rules for no name inputs
   "": {
      "creditCardNumber": true,
      "creditCardCvc": true
   }
}
```

Can i suggets a change to the rules and staticRules methods ? If the element name is  empty, check and use the element id.

**Comment by Arkni** [comment]
Try using HTML attributes to attach validators:
```html
<input type="text"
       data-rule-creditcardnumber="true" data-msg-creditcardnumber="error msg"
       data-rule-creditcardcvc="true" data-msg-creditcardcvc="another error msg">
```

That way, you won't need to add a name to your input

**Comment by ramiromd** [comment]
@Arkni thanks for yout reply, your solution doesn't work form me.

I think because the custom validators are added after plugin initialize.

I override ([changes here](https://github.com/jquery-validation/jquery-validation/files/910948/override.txt)) the plugin to use the element.id if the element.name is empty and works for me.

Rules before override:
![rules-before-override](https://cloud.githubusercontent.com/assets/517140/24874932/b064e610-1dfc-11e7-8bf0-95db78ef3594.png)

Rules after override:
![rules-after-override](https://cloud.githubusercontent.com/assets/517140/24874944/bdeb6a34-1dfc-11e7-82cc-b6213d81378e.png)

**Comment by Arkni** [comment]
> I think because the custom validators are added after plugin initialize.

Nope, it doesn't matter where you added them. The newly added rules will be used when your input is validated.

**Comment by arc95** [comment]
I'd like to add my two cents to this. This issue drove me nuts until I found an SO answer: http://stackoverflow.com/questions/11536271/validate-dynamically-added-input-fields

May I suggest adding a fallback to the validator: if no name attribute, check for ID? Thanks.

**Comment by gotzsys** [comment]
Try changing Line 630 and add this:
var name = this.name || $( this ).attr( "name" ) **|| $( this ).attr( "id" );** // For contenteditable
