### ISSUE TITLE
Use jQuery.extend instead of $.extend for WordPress support

### ISSUE THREAD

**Issue by goldhat** [jquery-validation/jquery-validation#1990]
In WordPress (and other systems) jQuery is loaded in a way that $ is not available, only jQuery is. We'll see an error when loading this plugin because it presume $.extend will work. I'm fairly sure it's a best practice to always use jQuery extend in plugins for this reason.

**Comment by staabm** [comment]
Please show the concrete error message and in whiich file those occur..

Our core module does not rely on `$` beeing defined in the global scope

**Comment by goldhat** [comment]
validation.js?ver=0.9.3:1 Uncaught TypeError: Cannot read property 'extend' of undefined at validation.js?ver=0.9.3:1

(Line 1) - $.extend( $.fn, {

**Comment by goldhat** [comment]
I suppose I was reading the error wrong... it's extend that is unavailable... am I missing a required file? I only included "core.js".

**Comment by hemant1612** [comment]
That may be a reason.

**Comment by staabm** [comment]
Do you include the src files from this git repos or the distributed files from a regular release?

**Comment by goldhat** [comment]
File core.js was included release 1.16.0 at from https://github.com/jquery-validation/jquery-validation/releases/tag/1.16.0

**Comment by Arkni** [comment]
You are the source file. Please use the distribution file which you can found inside the `dist` folder. You can either include `jquery.validate.js` or `jquery.validate.min.js`.

**Comment by Arkni** [comment]
I'm closing this for now, but feel free to ask if you have followup questions.
