### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by pwaring** [jquery-validation/jquery-validation#1991]
Not an issue with the code as such but the documentation website is currently down:

https://jqueryvalidation.org/

**Comment by staabm** [comment]
we are on it, thx for the heads up

**Comment by pwaring** [comment]
Thanks. If anyone else is looking for the documentation the Web Archive has it: http://web.archive.org/web/https://jqueryvalidation.org/documentation/

**Comment by staabm** [comment]
I will close this issue for now as we are already investigation the issue. feel free to comment further if new information gets available.

**Comment by staabm** [comment]
we are back online.
