### ISSUE TITLE
Error 526 Invalid SSL Cert for https://jqueryvalidation.org/min-method/

### ISSUE THREAD

**Issue by WebDragon** [jquery-validation/jquery-validation#1992]
just a note to let you know that your SSL cert appears to be expired? inasmuch as https://support.cloudflare.com/hc/en-us/articles/200721975 (which is where cloudflare sent me when I clicked Additional Troubleshooting) is indicating

1:43pm est

**Comment by hemant1612** [comment]
It surely needs an update

**Comment by staabm** [comment]
our awesome admins from https://www.ballensiefen.net fixed this for us. thanks guys!

also, thank you guys for reporting the issue.

Happy Easter!
