### ISSUE TITLE
Documentation website mixed content

### ISSUE THREAD

**Issue by martijn-dd** [jquery-validation/jquery-validation#1993]
Using Chrome 57.0.2987.133 or Firefox 52.0.2 CSS and JS is not loaded anymore on the documentation page [https://jqueryvalidation.org/documentation/](url) because of mixed content.

`Mixed Content: The page at 'https://jqueryvalidation.org/documentation/' was loaded over HTTPS, but requested an insecure script 'http://jqueryvalidation.org/wp-includes/js/wp-emoji-release.min.js?ver=4.7.3'. This request has been blocked; the content must be served over HTTPS.`

`Mixed Content: The page at 'https://jqueryvalidation.org/documentation/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&subset=latin,latin-ext'. This request has been blocked; the content must be served over HTTPS.`

Etc.

**Comment by staabm** [comment]
redeployed the website and it seems to work now. not sure why actually.. maybe cloudflare cache related..

**Comment by staabm** [comment]
hmm doesnt work again...

**Comment by staabm** [comment]
found some more cache-switches... cleared them and it seems to work now.
