### ISSUE TITLE
Div Contenteditable element can be validated only when it has both id and name attributes

### ISSUE THREAD

**Issue by kmchan** [jquery-validation/jquery-validation#1995]
### Subject of the issue
Refer to the fix of issue #1946, a div contenteditable element should have both `id` and `name` attributes for validation. If it only has `id`, the rules cannot be assigned. If it only has `name` attribute, "TypeError: Cannot read property 'replace' of undefined" occurs. However, there is no `name` attribute for div elements.

### Your environment
* jquery-validate v1.16.0
* Chrome browser v57.0.2987.133 (64-bit)

### Steps to reproduce
1. Create a form with div contenteditable element which has both id and name attributes
2. Validate it with the rules such as required and minlength for it
3. Validation works
4. Now, remove id from the element and keep the name attribute
5. Validate it with the same rules
6. Validation doesn't work
7. Next, remove the name attribute and add the id back
8. Validate again with the same rules
9. "TypeError: Cannot read property 'replace' of undefined" occurs

### Expected behaviour
Suggest to use id only for div contenteditable element

### Actual behaviour
Use both id and name attributes for div contenteditable element

**Comment by Arkni** [comment]
How do you assign the rules to your contenteditable div ?
because AFAIK, the fix you referenced is not yet published.

**Comment by kmchan** [comment]
I modified the code manually according to your fix because i need it in my development. Then, I assign the rules as usual, i.e. $('#form').validate({ rules: { fieldname: { required: true, minlength: 5 }, ... } }).

Moreover, Is it possible to add the flexibility to use other attribute such as custom attribute "data-name" for the element, instead of "name" or "id" only? :)

**Comment by alinearielo** [comment]
I've modified my code manually too with this fix, but now it seems to have this same error on $.validator.escapeCssMeta, using contenteditable.

"jquery.validate.js:1025 Uncaught TypeError: Cannot read property 'replace' of undefined"

Any ideas?

**Comment by kmchan** [comment]
Hi alinearielo,

Have you tried to assign both `id` and `name` attributes for the contenteditable element? 

I got "TypeError: Cannot read property 'replace' of undefined" when it only had `name` attribute. It worked when I assigned both `id` and `name` attributes.

This is my temp solution for the contenteditable div element, although div has no `name` attribute.
