### ISSUE TITLE
Replace andSelf with addBack in unobtrusive for jQuery 3 compatibility

### ISSUE THREAD

**Issue by sergeydgr8** [jquery-validation/jquery-validation#1997]
The method `andSelf` was deprecated back in version 1.8 of jQuery and instead used as an alias for `addBack`. This plugin uses `andSelf` in `parse()` of the unobtrusive version of the validator. It works fine in older versions in jQuery, however, beginning jQuery 3.0, `andSelf` is removed completely: https://api.jquery.com/andSelf/

The fix for this is just to replace `andSelf` with `addBack` in the parse function. The validator then works as it should under jQuery 3.

**Comment by staabm** [comment]
Thx for reporting.

I cannot find any occurence of andSelf in this codebase. I guess you are working with a different plugin?

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.

**Comment by sergeydgr8** [comment]
I'm working with the plugin that I got directly from NuGet: https://www.nuget.org/packages/jQuery.Validation/

It was found on line 211 of jquery.validate.unobtrusive.js.

**Comment by staabm** [comment]
I guess you are using https://github.com/aspnet/jquery-validation-unobtrusive

**Comment by sergeydgr8** [comment]
Oddly enough, that's not the same plugin that I downloaded from NuGet. They seem to be using addBack instead of andSelf.

**Comment by staabm** [comment]
I see. Please open a issue on their repos.

**Comment by sergeydgr8** [comment]
Done. Thank you!
