### ISSUE TITLE
The message is the 'title' attr of the input.

### ISSUE THREAD

**Issue by vrbvillor** [jquery-validation/jquery-validation#2002]
### Subject of the issue
The "message" parameter of `$.validator.addMethod` doesn't make sence. Instead it shows the input's `title` attrubition as the error message.

### Your environment
* version of `jquery-validate` **1.14.0**
* which browser and its version **Chrome**

**Comment by Arkni** [comment]
Use [`ignoreTitle`](https://jqueryvalidation.org/validate/#ignoretitle) option to ignore using the title of the input as the error message:
```js
$("#formID").validate({
  ignoreTitle: true,
  rules: {
    // ...
  }
})
```
