### ISSUE TITLE
NormalizeAtttribute breaks min/max date custom validators

### ISSUE THREAD

**Issue by yoerivdm** [jquery-validation/jquery-validation#2003]
On version 1.16 ... (we upgraded from 1.13)

NormalizeAtttribute converts the attribute value to number when input type is text and the validationMethod contains min, max or step.

We just encountered validation problems on existing software where a jquery datepicker is used on an input type text and custom validation for enforcing dateranges named 'mindate' and 'maxdate'. Dateformats like ddMMyyyy are converted to numbers ... dates with day < 10 cannot be parsed because the first zero is cutoff ...

Why normalizeAttributes for non-default validators? Imho the specific validator is responsible for correct parsing and determining the type.

**Comment by staabm** [comment]
could you provide a jsfiddle or similar reduced example code which shows your issue?

**Comment by yoerivdm** [comment]
https://jsfiddle.net/Yoeri/w6txktdu/
