### ISSUE TITLE
Document use of additional-methods via npm

### ISSUE THREAD

**Issue by lorensr** [jquery-validation/jquery-validation#2004]
### Subject of the issue
I'm getting this error when trying to validate `phoneUS`:

![image](https://cloud.githubusercontent.com/assets/251288/25871995/341e8e0c-34d7-11e7-8a9c-90297e066e18.png)

I'm guessing it's due to not having `additional-methods.js` included in my app. I have `'jquery-validation'` installed via npm and have this line in my code:

```js
import 'jquery-validation'
```

I expected the solution to be something like:

```js
import 'jquery-validation'
import 'jquery-validation/additional-methods'
```

but that didn't work.

### Your environment
* version of `jquery-validate`: 1.16.0

**Comment by dimakTR** [comment]
As a quick workaround you can directly import the file.
`import '/node-modules/jquery-validation/dist/additional-methods'`

Just make sure to have the right path. For me it was like
`require('../../../node_modules/jquery-validation/dist/additional-methods.js');`

**Comment by Arkni** [comment]
It should be:
```js
// Using ESM
import "jquery-validation/dist/additional-methods.js"

// Using commonjs
require("jquery-validation/dist/additional-methods.js")
```
