### ISSUE TITLE
Question: submit buttons for Sign In & Facebook Sign In

### ISSUE THREAD

**Issue by javierbertran** [jquery-validation/jquery-validation#2008]
### Checklist for this issue
If your issue is about the regex used in `email` rule, please note that as of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use (https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.
In case you need to adjust the built-in validation regular expression patterns, please follow the documentation (http://jqueryvalidation.org/jQuery.validator.methods/).

### Subject of the issue
Hi, I have two submit buttons in the same web page one for my application Sign In and one for Facebook Sign In. I only want to perform validation for my application's submit button and not for Facebook Sign In submit button. Is it possible to validate one button and not validate another button?

Thanks beforehand,

Javier
### Your environment
This is a question before we use the control in order to know if it can help us.

### Steps to reproduce
None

### Expected behaviour
One button must be validated and another must not.

### Actual behaviour
No testing yet

**Comment by Arkni** [comment]
See https://jqueryvalidation.org/reference/#link-skipping-validation-on-submit
> #### Skipping validation on submit
>
>To skip validation while still using a submit-button, add the attribte "formnovalidate" to that input:
>
>
>```html
><input type="submit" name="go" value="Submit">
><input type="submit" formnovalidate name="cancel" value="Cancel">
>```
>This used to work by adding class="cancel" to the input, this is now deprecated.
