### ISSUE TITLE
Credit card custom method doesn't allow 19 digit numbers

### ISSUE THREAD

**Issue by bennybee** [jquery-validation/jquery-validation#2020]
Visa will soon begin issuing 19-digit credit card numbers

https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2016/november/prepare-for-19-digit-credit-cards/

The current version of the credit card custom method on your demo page only supports 13 and 16 digit numbers:

https://jqueryvalidation.org/creditcard-method/

**Comment by RobJohnston** [comment]
The code accepts values between 13 and 19 digits already:
https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/creditcard.js#L22

For example, try 6304 2194 4760 7087 665 in the demo on the [creditcard method page](https://jqueryvalidation.org/creditcard-method/).

**Comment by bennybee** [comment]
Ok didn't realise that there

**Comment by RobJohnston** [comment]
For completeness, I should note that the creditcardtypes method does limit Visa to 16 digits:
https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/creditcardtypes.js#L44
