### ISSUE TITLE
errorHandler

### ISSUE THREAD

**Issue by suriyagp** [jquery-validation/jquery-validation#2024]
### Subject of the issue
is there any erroHandler call back is available like the submitHandler?

### Expected behaviour
separate call back to handle error (errorHandler)

### Actual behaviour
It only throws the error on the UI

**Comment by Arkni** [comment]
What type of error handlers are you looking for?

As far as I understand your issue, you can use one of the following handlers:
* [`showErrors()`](https://jqueryvalidation.org/validate/#showerrors): A custom message display handler. Gets the map of errors as the first argument and an array of errors as the second, called in the context of the validator object. The arguments contain only those elements currently validated, which can be a single element when doing validation on focusout or keyup. You can trigger (in addition to your own messages) the default behaviour by calling this.defaultShowErrors().
* [`invalidHandler()`](https://jqueryvalidation.org/validate/#invalidhandler): Callback for custom code when an invalid form is submitted. Called with an event object as the first argument, and the validator as the second.

There are other handlers available, check them out in [`validate()`](https://jqueryvalidation.org/validate) docs.

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
