### ISSUE TITLE
Aria required being added to checkbox

### ISSUE THREAD

**Issue by joshuacronin** [jquery-validation/jquery-validation#2026]
### Subject of the issue
The aria required attribute is being added to checkbox elements which is being flagged as invalid by Google Lighthouse.

### Your environment
* jquery-validate v1.16.0
* Chrome 59.0.3071.115 

### Steps to reproduce
Make a checkbox element required and initiate jQuery validate.
Example: https://output.jsbin.com/ruyodivohu

### Expected behaviour
There shouldn't be an aria required attribute on a checkbox element. 

### Actual behaviour
There is an aria required attribute on required checkbox elements.

**Comment by Arkni** [comment]
Thanks for opening the ticket.
The issue was already fixed in #2012 but not released yet.
