### ISSUE TITLE
Validate reporting error in console when there is input with attribute "form"

### ISSUE THREAD

**Issue by DukeFED** [jquery-validation/jquery-validation#2029]
Validate reporting error in console when there is input with attribute called "form" inside of form being validated. Error is:

Uncaught TypeError: Cannot read property 'nodeName' of null.

**Comment by egpo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  giboni@gmail.com
    Domain egpo.net has exceeded the max emails per hour (510/500 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:32917 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server1.egpo.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dUrHZ-00056L-Mu
	for egpo@egpo.net; Tue, 11 Jul 2017 04:16:37 -0500
Date: Tue, 11 Jul 2017 02:15:56 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1499764556;
	bh=VFwle87exYrSiqD+stW+C3Oj3a0mhMonPlrsRZ6mzC0=;
	h=From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=ytT23bWeqP2aTDDiToio2vmfCpLSCxYO0NjQGjCXuQcevU3ScKEtXEpwk1TVp+ca+
	 xxMDZA2NyvfUrQ+5EAYHb1m12sJHamGJoVJLTV41jaBruQKR1FrRmtwI9aNKAV3u6t
	 yXwZFDPUZ1Gyh1qU1mzRyvH7ehCFpk2sHWfem/vI=

**Comment by hellboy81** [comment]
Hi! I have the same issue.

Is there possible to validate `input`-s with `form`- attribute outside the `form`?

**Comment by staabm** [comment]
Atm this is not supported. Adding support for it would depend on patch size and how good the patch fits into the core

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
