### ISSUE TITLE
Add greaterThan and lessThan methods.

### ISSUE THREAD

**Issue by RobJohnston** [jquery-validation/jquery-validation#2030]
Similar to the [equalTo method,](https://jqueryvalidation.org/equalTo-method/) and the [notEqualTo method](https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/notEqualTo.js), would there be interest in having  `greatherThan `and `lessThan `methods?  Additionally, `greaterThanEqual `and `lessThanEqual `for completeness?  I'm thinking that these can be numeric <ins>and date</ins> comparisons only.

The situation would be two text boxes, one being a "Start" value and the other an "End" value.  The [range method](https://jqueryvalidation.org/range-method/) could be used here as well, but the "End" value must be still be greater than the "Start" value.

**Comment by RobJohnston** [comment]
This is going to be easy... see old PR https://github.com/jquery-validation/jquery-validation/pull/458.

**Comment by RobJohnston** [comment]
Any comments about this method?  If this is acceptable, expect a PR soon:
```js
$.validator.addMethod( "greaterThan", function ( value, element, param ) {
    var target = $( param );

    if ( this.settings.onfocusout && target.not( ".validate-greaterThan-blur" ).length ) {
        target.addClass( "validate-greaterThan-blur" ).on( "blur.validate-greaterThan", function () {
            $(element).valid();
        });
    }

    return value > target.val();
}, "Please enter a greater value.");
```

**Comment by Arkni** [comment]
+1 from me.
