### ISSUE TITLE
normalizeRules Number issue

### ISSUE THREAD

**Issue by Looooooka** [jquery-validation/jquery-validation#2036]
Using globalization on a .NET core problem.
The problem.
Attribute data-val-range-min, max and all the others get their values localized (FINE WITH ME).
So data-val-range-min="0,01" (I'm from Slovenia).
The problem is when normalizeRules is hit it normalizes using javascripts global Number function.
The only way I've been able to fix this is to override all calls with  Number(Globalize.parseNumber(
Pretty sure this should be handled somehow differently.
Perhaps the "parameters" should have been somehow parset from the localized attribute value before that.
Does anyone have any idea what needs to be set to have that happen?

`
    $.validator.normalizeRules = function (rules, element) {

        // Handle dependency check
        $.each(rules, function (prop, val) {

            // Ignore rule when param is explicitly false, eg. required:false
            if (val === false) {
                delete rules[prop];
                return;
            }
            if (val.param || val.depends) {
                var keepRule = true;
                switch (typeof val.depends) {
                    case "string":
                        keepRule = !!$(val.depends, element.form).length;
                        break;
                    case "function":
                        keepRule = val.depends.call(element, element);
                        break;
                }
                if (keepRule) {
                    rules[prop] = val.param !== undefined ? val.param : true;
                } else {
                    $.data(element.form, "validator").resetElements($(element));
                    delete rules[prop];
                }
            }
        });

        // Evaluate parameters
        $.each(rules, function (rule, parameter) {
            rules[rule] = $.isFunction(parameter) && rule !== "normalizer" ? parameter(element) : parameter;
        });

        // Clean number parameters
        $.each(["minlength", "maxlength"], function () {
            if (rules[this]) {
                rules[this] = Number(Globalize.parseNumber(rules[this]));
            }
        });
        $.each(["rangelength", "range"], function () {
            var parts;
            if (rules[this]) {
                if ($.isArray(rules[this])) {
                    rules[this] = [Number(Globalize.parseNumber(rules[this][0])), Number(Globalize.parseNumber(rules[this][1]))];
                } else if (typeof rules[this] === "string") {
                    parts = rules[this].replace(/[\[\]]/g, "").split(/[\s,]+/);
                    rules[this] = [Number(Globalize.parseNumber(parts[0])), Number(Globalize.parseNumber(parts[1]))];
                }
            }
        });

        if ($.validator.autoCreateRanges) {

            // Auto-create ranges
            if (rules.min != null && rules.max != null) {
                rules.range = [rules.min, rules.max];
                delete rules.min;
                delete rules.max;
            }
            if (rules.minlength != null && rules.maxlength != null) {
                rules.rangelength = [rules.minlength, rules.maxlength];
                delete rules.minlength;
                delete rules.maxlength;
            }
        }

        return rules;
    };`

**Comment by staabm** [comment]
As far as I can understand your reported problem this is somehow related to the .NET integration and does not apply for the libray itself.

In case I am missing something please provide a JSFIDDLE which shows your error in a plain/reduced javascript+html example

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
