### ISSUE TITLE
dynamic generation form 

### ISSUE THREAD

**Issue by cunliyizhihua** [jquery-validation/jquery-validation#2038]
### Subject of the issue
use ajax to request some data,
then Rendering it to a Form template with hogan.js(http://twitter.github.io/hogan.js/)
it means that the Form is dynamic generation.
`$('#form-name').validate()`
now it's invalid .

### Your environment
* jquery                  :    1.12.0
* jquery-validate    :    1.16.0
* chorme                :    59.0.3071.115

**Comment by Arkni** [comment]
Are you calling `$('#form-name').validate()` before or after your form was added to the page?
Normally, you should call it after so that the plugin can find your form and initialize it for validation.
