### ISSUE TITLE
missing dist/localization directory in the 1.17.0 release

### ISSUE THREAD

**Issue by tbl0605** [jquery-validation/jquery-validation#2040]
Hi,
in latest 1.17.0 zip and tar.gz files, there is no dist/localization directory.
I could use src/localization but then I don't have the minimized .js files :(

Thierry.

**Comment by staabm** [comment]
just added the missing ZIP which includes this folder.
https://github.com/jquery-validation/jquery-validation/releases/tag/1.17.0

thx for noting.

**Comment by tbl0605** [comment]
Thank you very much Markus ! :)
