### ISSUE TITLE
The 1727 line of code is not reasonable

### ISSUE THREAD

**Issue by liguangzeng** [jquery-validation/jquery-validation#2041]
"required": function (str) {
            return !(|| str.replace(/\s/g,"") == "" || typeof str != "string"  );
        }
Should be changed to

 "required": function (str) {
            return !(typeof str != "string" || str.replace(/\s/g,"") == "" );
        }
Because strings have the replace method but “null” or “undefined”  not have  this method
Therefore, you should first determine whether it is a string

**Comment by Arkni** [comment]
The dist file contains only 1601 lines of code. Can you please link to exact line that contains that code ?
