### ISSUE TITLE
Normalizer can't return array

### ISSUE THREAD

**Issue by YodaDaCoda** [jquery-validation/jquery-validation#2049]
The normaliser function requires a string to be returned - an array, such as you get for a multiselect, is not permitted. This seems wrong to me.

I initially started using the normalizer to prevent blank strings from being permitted, but I'd like to be able to properly validate multiselect picklist values too.

### Your environment
* version of `jquery-validate`: 1.17.0

### Expected behaviour
I expect the validator to just use the value that's returned from the normalizer, not attempt to sanity-check it. That's my responsibility.

### Actual behaviour
A TypeError is thrown and validation stops.

**Comment by Arkni** [comment]
TBH, I don't remember why we required it to return a `string`. Nevertheless, I'll take a look at it soon.

Also, should we allow the `normalizer` to return `undefinded` or `null` ? as not all methods are built to check for them first (including the `required` method).

**Comment by YodaDaCoda** [comment]
I know that older versions of jQuery (e.g. 1.12.4) return `null` for the value of a `select[multiple]` when no options are selected. See fiddle: https://jsfiddle.net/YodaDaCoda/0zb5az6v/

Later versions of jQuery return an empty array, but I'm not sure exactly when that behaviour changed.

Given that the website suggests that this plugin supports jQuery back to 1.7.2 ("tested with 1.7.2, 1.8.3, 1.9.1, 1.11.1, 3.1.1") I suggest allowing the normaliser to return any value, and leaving it up to the author of the normalisation function to catch cases that may return undesirable values.

**Comment by Arkni** [comment]
Thanks for the example and info.

That makes sense to me. I check the code of the required method and it handles both `null` and `array` value of the `SELECT` element, but will not handle a `null` or `undefined` value coming from the `normalizer` which need a fix.

I'll open a PR soon to fix those two issues.
