### ISSUE TITLE
Broken CDN links at https://jqueryvalidation.org/

### ISSUE THREAD

**Issue by MartinKolarik** [jquery-validation/jquery-validation#2056]
First, big congrats - [jquery-validation](https://www.jsdelivr.com/package/npm/jquery-validation) receives more than 500 M requests per month at jsDelivr, which makes it the 7th most popular package we host!

I noticed your website shows some broken links. We switched to a fully automated system in May, and new versions (in your case > 1.15.0) are [available under different URLs]( https://www.jsdelivr.com/package/npm/jquery-validation). The correct links are:
 - https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js
 - https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js
 - https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/additional-methods.js
 - https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/additional-methods.min.js (note: this minified file doesn't seem to be in the npm package, but jsDelivr is able to generate it on-demand)

Feel free to ping me if you have any questions regarding this change.

**Comment by Arkni** [comment]
Hi Martin, thanks for reaching out.

WOW, That's a big number. I never realized or even thought that we will reach a number like that. Thanks for hosting our files and helping delivering it to developers across the glob.

I'm aware of your changes but didn't had the chance to update the links on our website, and it's the right time to do it.

For the minified version of `additional-methods` file, we forgot to add it to the files published on npm https://github.com/jquery-validation/jquery-validation/blob/5482dfd95ff01bb89a4fe5171f67c63d90c12198/package.json#L30-L35

I will fix that in a followup PR and will try to do a patch release soon to fix that.

Thanks again for the heads up.

/cc @staabm

**Comment by Arkni** [comment]
Opened #2057 and jquery-validation/validation-content#40 to fix the mentioned issues

**Comment by staabm** [comment]
thank you guys. just merged the PR. will be deployed when time allows this week.

**Comment by staabm** [comment]
changes deployed
