### ISSUE TITLE
click <select> will trigger validate

### ISSUE THREAD

**Issue by Ahaochan** [jquery-validation/jquery-validation#2058]
I want to validate form only submit。

when I submit without input, it will tip 4 errors, it is right.
after, I click the select tag, it will trigger validate, That is beyond my expectations.
Now I can not submit my form because the select tag always trigger validate.
how to solve this question? thank !

jsbin here:  [https://jsbin.com/liluzat/1/edit?html,output](https://jsbin.com/liluzat/1/edit?html,output)

**Comment by Ahaochan** [comment]
I sovle it,
just append { onclick: false }

**Comment by staabm** [comment]
awesome, thx for the followup.
