### ISSUE TITLE
Subresource integrity

### ISSUE THREAD

**Issue by vanillajonathan** [jquery-validation/jquery-validation#2059]
When doing releases please post the subresource integrity hash.

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
https://www.srihash.org/

**Comment by Arkni** [comment]
Hi @vanillajonathan 

That's a good idea. Do you think we need to provide the hashes of the old versions (before `1.17.0`) or just for the new ones ?

Also, should we only provide `sha384` hashes or we need to also provide `sha256` and `sha512` hashes?

/cc @staabm

**Comment by staabm** [comment]
fait point. is this something we can generate with our release task @Arkni 

IMO sha512 is a must have, sha384 & sha256 should only be added if it takes a resonable amount of code/time to implement

**Comment by vanillajonathan** [comment]
@Arkni, no I don't think it is needed to provide the hashes for old versions before 1.17.0. Since those are already deployed and the link to those are not likely to change without also upgrading the reference to the latest version.

As for variant, I don't know but cdnjs and jsdelivr use sha256.
https://cdnjs.com/libraries/jquery-validate
https://www.jsdelivr.com/package/npm/jquery-validate?tab=collection

While [Bootstrap](http://getbootstrap.com/) use sha384.

sha256 is likely good enough. The disadvantage with sha384 and sha512 is that the SRI string is longer.

sha256 - 51 characters.
sha384 - 71 characters.
sha512 - 96 characters.

Though hashes for all three variants could be provided.

**Comment by Arkni** [comment]
@staabm: I think we can use this `Grunt` plugin: [`grunt-sri`](https://github.com/neftaly/grunt-sri)

@vanillajonathan: Thanks for the info. We will see if we can provide the three variants.

**Comment by staabm** [comment]
sounds great, I will assign it to you.

no high prio though.

**Comment by Arkni** [comment]
OK. I gave it a try and here is the output (json) of the plugin for core file.

```json
{
  "@dist/jquery.validate.js": {
    "hashes": {
      "sha256": "yazfaIh2SXu8rPenyD2f36pKgrkv5XT+DQCDpZ/eDao=",
      "sha384": "Q4rt9UBTpx/3bH0OMmXmmmOSDuT8U2Hh7bSutsYCFsSNq1c0VXj/LGB4r4VWgAwO",
      "sha512": "6c+WFJwS2XYhaRGuzl16pW4BvcHTGc+l0RzWXz92mFRC8NN2OXsTurazY6uOweYoAvovenvmjLDvrg9JOSev8w=="
    },
    "integrity": "sha256-yazfaIh2SXu8rPenyD2f36pKgrkv5XT+DQCDpZ/eDao= sha384-Q4rt9UBTpx/3bH0OMmXmmmOSDuT8U2Hh7bSutsYCFsSNq1c0VXj/LGB4r4VWgAwO sha512-6c+WFJwS2XYhaRGuzl16pW4BvcHTGc+l0RzWXz92mFRC8NN2OXsTurazY6uOweYoAvovenvmjLDvrg9JOSev8w==",
    "path": "dist/jquery.validate.js"
  },
  "@dist/jquery.validate.min.js": {
    "hashes": {
      "sha256": "C6qpCr0Yhet/kWCcur7OiSSKKaEVMXqF7iyi8uveXtg=",
      "sha384": "XShkGAHYdh0K9/PvjuiEQfPHIQ+hTW2FpIS6TssqRfAdfIyrXSht20Nk3zd3CCOR",
      "sha512": "a/ZlWWoxx303QE+/5RHcz2yWlcqagEac64RveFRjymZHrxDps5GErAu8c8BKdu6P5iE0/gzjTdCwxIW6G+paHg=="
    },
    "integrity": "sha256-C6qpCr0Yhet/kWCcur7OiSSKKaEVMXqF7iyi8uveXtg= sha384-XShkGAHYdh0K9/PvjuiEQfPHIQ+hTW2FpIS6TssqRfAdfIyrXSht20Nk3zd3CCOR sha512-a/ZlWWoxx303QE+/5RHcz2yWlcqagEac64RveFRjymZHrxDps5GErAu8c8BKdu6P5iE0/gzjTdCwxIW6G+paHg==",
    "path": "dist/jquery.validate.min.js"
  }
}
```

@vanillajonathan How you want us to share the integrity hashes? as JSON files like above or something else?

**Comment by vanillajonathan** [comment]
@Arkni on the website and/or on GitHub as part of the release announcement.

**Comment by staabm** [comment]
Looks good to me.

**Comment by vanillajonathan** [comment]
I don't know, but browsers do.
http://caniuse.com/#search=Subresource%20Integrity
