### ISSUE TITLE
Document features

### ISSUE THREAD

**Issue by staabm** [jquery-validation/jquery-validation#2077]
Document new features

- [ ] https://github.com/jquery-validation/jquery-validation/pull/2061
- [ ] https://github.com/jquery-validation/jquery-validation/pull/2063

**Comment by Arkni** [comment]
@staabm docs are only needed for #2063 as it is a new option of the `validate()` method. As for the new additional methods, we don't need that as not all additional methods are documented (from [docs](https://jqueryvalidation.org/documentation/#link-list-of-built-in-validation-methods)):

>Some more methods are provided as add-ons, and are currently included in additional-methods.js in the download package. Not all of them are documented here:
>
>[accept – Makes a file upload accept only specified mime-types.][1]
>[creditcard – Makes the element require a credit card number.][2]
>[extension – Makes the element require a certain file extension.][3]
>[phoneUS – Validate for valid US phone number.][4]
>[require_from_group – Ensures a given number of fields in a group are complete.][5]
>
>You can find the source code for all additional methods in the GitHub repository.

[1]: https://jqueryvalidation.org/accept-method
[2]: https://jqueryvalidation.org/creditcard-method
[3]: https://jqueryvalidation.org/extension-method
[4]: https://jqueryvalidation.org/phoneUS-method
[5]: https://jqueryvalidation.org/require_from_group-method
````
