### ISSUE TITLE
jsDelivr CDN links are broken

### ISSUE THREAD

**Issue by sparky672** [jquery-validation/jquery-validation#2081]
Clicking on any of the jsDelivr CDN links posted on [jqueryvalidation.org](https://jqueryvalidation.org) gives the following message:

>  Couldn't find the requested release version 1.17.0.

**Comment by jimaek** [comment]
This is the correct URL https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js

Page https://www.jsdelivr.com/package/npm/jquery-validation

The package also gets 623Million hits per month.

**Comment by sparky672** [comment]
I just figured I'd let the developers know so that somebody can update the website home page.

**Comment by Arkni** [comment]
@sparky672 
Thanks for the heads up. We already fixed it in the docs repository (See #2056 and jquery-validation/validation-content#40) but not deployed yet.

@staabm any chance to deploy the latest changes?

Thanks!

**Comment by staabm** [comment]
thx for the reminder.. just deployed the changes.
