### ISSUE TITLE
Error message "min" in file messages_vi.js.

### ISSUE THREAD

**Issue by tienvd1994** [jquery-validation/jquery-validation#2085]
Error message "min" in file messages_vi.js. 
https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_vi.js

**Comment by staabm** [comment]
Whats the point of this issue?

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.

**Comment by tienvd1994** [comment]
min: $.validator.format( "Hãy nhập từ {1} trở lên." )
Can you change from {1} to {0} in file 
https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_vi.js

**Comment by staabm** [comment]
thx for point that out, fixed by https://github.com/jquery-validation/jquery-validation/commit/2c615e7b9baac4c06e2934418b3d6766fd7fe78d
