### ISSUE TITLE
button trigger instead submit trigger ?

### ISSUE THREAD

**Issue by jochen1727** [jquery-validation/jquery-validation#2086]
Hi everybody .....
I have an issue, I use a button instead submit type trigger, is it possible to trigger through my button form instead submit type?
Thks.

**Comment by staabm** [comment]
Use valid() to trigger the validation via js from any event or element

See https://jqueryvalidation.org/valid/

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
