### ISSUE TITLE
Remote: Can't alter ajax method type attribute from DOM

### ISSUE THREAD

**Issue by eltismerino** [jquery-validation/jquery-validation#2091]
Take

`<input type="text" name="test" data-rule-remote="http://url" data-rule-remote-type="post" />`

I'd expect this to set the "type" parameter of the ajax call to "post" instead of the default "get".

**Comment by staabm** [comment]
@eltismerino is this a bug report, a feature request or a question?

**Comment by Arkni** [comment]
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the question made to them months ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!

**Comment by pannal** [comment]
Sorry, I didn't see the issue in my notifications.

Yes, partly lost interest, but it still is an issue. I'm, not sure whether this is a bug report, but at least it's a design flaw. Currently all attributes that can be used using JavaScript can also be described using HTML data attributes. Just not for data-rule-remote.

**Comment by Arkni** [comment]
Hi @pannal,

As far as I know, `data-rule-*` attributes were never meant to be a drop in replacement of setting rules by passing them to `.validate()` method. They are there for simple rules like `required`, `minlength`, ...

In the case of `remote` method, setting that attribute will be equivalent to setting the rule to string in `.validate()` method. The provided value will be then used as the URL to which the remote method will make calls .

The following three ways are equivalent:

1-
```html
<input type="text" name="remoteEl" data-rule-remote="some url">
```
2-
```js
$("form_selector").validate({
  rules: {
    remoteEl: {
      remote: "some url"
    }
  }
});
```
3-
```js
$("form_selector").validate({
  rules: {
    remoteEl: {
      remote: {
        url: "some url"
      }
    }
  }
});
```

**Comment by pannal** [comment]
I understand that. But only partly supporting those attributes, especially for the remote filter, is weird. The HTML data-attribute feature is barely documented, but referenced often outside of the documentation (forums, stackoverflow etc.), so I was under the impression that this indeed *was* a drop in replacement.

And it would be very nice to have this.

**Comment by Arkni** [comment]
> The HTML data-attribute feature is barely documented, but referenced often outside of the documentation (forums, stackoverflow etc.)

In fact, they are referenced in docs, but not as important as other ways of setting rules.
We welcome any contribution to our docs :) If you are interested, the documentation repository can be found here: [`jquery-validation/validation-content`](https://github.com/jquery-validation/validation-content).


> And it would be very nice to have this.

We are not ready to open that box for now. Adding support for `remote` method will also require us to add support for other additional methods.
If you want this feature, maybe you can test [`jquery-validation-unobtrusive`](https://github.com/aspnet/jquery-validation-unobtrusive/) which I believe does what you want.

We might consider adding support for this if more people are requesting the same in the future.

Thanks!
