### ISSUE TITLE
Make message a function instead of a string

### ISSUE THREAD

**Issue by AmitJoki** [jquery-validation/jquery-validation#2093]
### Subject of the issue
This isn't much of an issue as it is a feature request. But it would be a solid feature to have. Just sample the google queries: https://www.google.co.in/search?q=dynamic+messages+jquery+validation

### Environment
jquery-validate 1.17.0
Chrome Latest

### Steps to reproduce
When checking if a user name exists using remote, I want to display a message like:

```
...
messages: {
    username:{
        remote: $('#username').val() + ' already exists'
    }
}
...

```
### Expected behaviour
The message should have been `example@xyz.com already exists.`
 
### Actual behaviour
The message is ` already exists`

### Proposed Solution
Just make the messages take the function as an argument which should return a string and call it right before appending the error message.

So, the config would be
```
...
messages: {
    username:{
        remote: function(){
            return $('#username').val() + ' already exists'
        }
    }
}
...
```
This makes sure that every time the message is displayed, the function is executed at that time, therefore, `$('#username').val()` actually has some value.

**Comment by Arkni** [comment]
You can use a dynamic message (template with a placeholder):
```js
messages: {
  username: {
    remote: '{0} already exists'
  }
}
```

`{0}` will be replaced with the invalid value by the plugin.

**Comment by plocket** [comment]
You can also use a function as a second argument to `.addMethod()`:
```js
$.validator.addMethod('alreadyexists', function(value, element, params) {
  // return true or false
}, function al_min_message (validity, field) {
  // I assume the ajax request can go in here
  return `${ $(field).val() ) + ' already exists'`;
});
```

Maybe that's newer.
