### ISSUE TITLE
Switching from validationEngine.js

### ISSUE THREAD

**Issue by bartclaeys** [jquery-validation/jquery-validation#2100]
I'm switching from `validationEngine.js` which seems no longer actively maintained. When looking at the documentation I noticed the requirements are defined in JavaScript, rather than using HTML attributes. Is there any reason for this?

Also, is there a way to scroll the form to the field that needs to be fixed when clicking a submit button at the end of the form?

Additionally, is it possible to display the errors differently (bubbles), rather than pushing content under the field (potentially breaking the layout)?

Lastly, any support for AJAX calls? I need to verify whether a username/email address already exists and show an error if already taken.

**Comment by staabm** [comment]
Please see the docs or sewrch stackoverflow.

All of your mentioned points are covered by the lib.

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
