### ISSUE TITLE
Max length validation: line breaks are counted as one character, but should be counted as two in some cases

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [jquery-validation/jquery-validation#2101]
### Subject of the issue
As described in issue #1264 the length calculation counts a line break as one character. Javascript returns / stores  a line break as `\r` instead of the often needed `\r\n` (e.g. in a windows environment). This can cause the validation to succeed e.g. when given a max length of 5 and a value of `ABC{line break}D` as on client side the string has a length of 5 characters but on the server side the line break might be represented by \r\n which results in a length of 6 characters.

### Your environment
* version of `jquery-validate` is `1.17.0´
* Chrome `61.0.3163.100`, english environment
* Windows Server, german environment

### Steps to reproduce
1. create a `<textarea>`
2. add attribute `data-max-length=5`
3. enter `ABC`, press enter (adds a line break), enter `D`
4. submit the form

### Expected behaviour
Validation should fail as the line break should count as 2 characters because on server side the line break representation will be `\r\n`. The string length calculation should return 6.

### Actual behaviour
Validation succeeds as string length calculation returns 5.

### Possible solution
My solution is to override the `getLength()` method to add the line break conversion:

    $.validator.prototype.oldGetLength = $.validator.prototype.getLength;

    $.validator.prototype.getLength = function(value, element) {
      var v = $("<textarea> \r\n </textarea>").val();

      var clientSideLineBreak = v.substr(1, v.length - 2);
      var serverSideLineBreak = this.settings.serverSideLineBreak ? this.settings.serverSideLineBreak : "\r\n";

      value = value.replace(clientSideLineBreak, serverSideLineBreak);

      var l = this.oldGetLength(value, element);

      return l;
    };

Should i provide a PR to incorporate these changes directly?

**Comment by Arkni** [comment]
As per [the HTML5 specification](https://www.w3.org/TR/html5/forms.html#the-textarea-element), textarea uses the `LF` character for new lines (`\n`), but they also understand and internally transform `\r` and `\r\n`.

Quoting below a portion of the spec:

>When a textarea is mutable, its raw value should be editable by the user: the user agent should allow the user to edit, insert, and remove text, and to insert and remove line breaks in the form of "LF" (U+000A) characters.
>
> (...)
>
>For historical reasons, the element's value is normalised in three different ways for three different purposes. The raw value is the value as it was originally set. It is not normalized. The API value is the value used in the value IDL attribute. It is normalized so that line breaks use "LF" (U+000A) characters. Finally, there is the form submission value. It is normalized so that line breaks use U+000D CARRIAGE RETURN "CRLF" (U+000A) character pairs, and in addition, if necessary given the element's wrap attribute, additional line breaks are inserted to wrap the text at the given width.
>
>The element's API value is defined to be the element's raw value with the following transformation applied:
>1. Replace every U+000D CARRIAGE RETURN "CRLF" (U+000A) character pair from the raw value with a single "LF" (U+000A) character.
>2. Replace every remaining U+000D CARRIAGE RETURN character from the raw value with a single "LF" (U+000A) character.
>
>The element's value is defined to be the element's raw value with the following transformation applied:
>1. Replace every occurrence of a "CR" (U+000D) character not followed by a "LF" (U+000A) character, and every occurrence of a "LF" (U+000A) character not preceded by a "CR" (U+000D) character, by a two-character string consisting of a U+000D CARRIAGE RETURN "CRLF" (U+000A) character pair.
>2. If the element's wrap attribute is in the Hard state, insert U+000D CARRIAGE RETURN "CRLF" (U+000A) character pairs into the string using a UA-defined algorithm so that each line has no more than character width characters. For the purposes of this requirement, lines are delimited by the start of the string, the end of the string, and U+000D CARRIAGE RETURN "CRLF" (U+000A) character pairs.

If you want jQuery validate to count for the `CRLF` character pair, you should replace `LF` with `CRLF`, before the element is validated, using the [`normalizer`](https://jqueryvalidation.org/normalizer/):
```js
$("#yourForm").validate({
  rules: {
    inputName: {
      normalizer: function(value) {
        var newV = value.replace(/\n/g, "\r\n");
        return newV;
      }
    }
  }
});
```
