### ISSUE TITLE
add rules in jquery each work only for first element

### ISSUE THREAD

**Issue by itajackass** [jquery-validation/jquery-validation#2102]
I've problem adding rules by class name in a jquery each function: only first element work:
I need use class, cause i need same name for the element cause is an array and it's dinamically created.

see example: http://jsfiddle.net/sw87W/860/

**Comment by Arkni** [comment]
Hi @itajackass 

This plugin doesn't support multiple input with the same name. [It's quoted in our docs](https://jqueryvalidation.org/reference/#link-markup-recommendations):
>Mandated: A 'name' attribute is required for all input elements needing validation, and the plugin will not work without this. **A 'name' attribute must also be unique to the form**, as this is how the plugin keeps track of all input elements. However, each group of radio or checkbox elements will share the same 'name' since the value of this grouping represents a single piece of the form data.

**Comment by itajackass** [comment]
I know, i want to use a CLASS if you see my jsfiddle above.

**Comment by staabm** [comment]
still your name attribute is not unique to the form.
