### ISSUE TITLE
Uncaught TypeError: Cannot read property 'form' of undefined

### ISSUE THREAD

**Issue by giorgi1517** [jquery-validation/jquery-validation#2103]
i am trying to validate one form with 4 stages. I want to  validate some fields when i click on nextbtn but i get this error. 
https://pastebin.com/taK7FqSX -see js here .. ask me anything, what's necessary to understand my problem better

**Comment by Arkni** [comment]
Can you also provide your HTML or try to create a minimal demo on [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/).

Without that, I'm afraid we can't help fixing error that we don't understand its cause.

Thanks!

**Comment by ssadok** [comment]
Same error on sharepoint when i call $("#submit_form") i got :
n.fn.init **{**context: document, selector: "#submit_form"**}**
instead of :
n.fn.init [form#submit_form.form-horizontal, context: document, selector: "#submit_form"]

**Comment by Arkni** [comment]
@ssadok 

Can you please provide your HTML or try to create a minimal demo on [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) ?
