### ISSUE TITLE
Validating with a subset of the form's rules

### ISSUE THREAD

**Issue by xt0rted** [jquery-validation/jquery-validation#2105]
I have a number of forms that need to run both partial validation and full validation. The user doesn't have to enter everything at once so they can either save as a work in progress, or submit the whole thing. When saving an incomplete form I still want to run validation for things like field length, date range, number format etc., but I don't want to run the required rules. Is there an easy way to disable a set of rules when running validation on the form?

The way I'm doing this right now is by adding a class to the form depending on the type of validation being run (partial or full) and then using a custom required rule that checks for the class and either assumes true for partial, or runs for full. It's a little verbose, and means I can't use the `required` attribute on the input controls, but it's gotten the job done.

An example of the rule setup is
```js
var ValidationRules = {
    requiredForFull: {
        depends: function(el) {
            return $(el).closest('form').hasClass('js-form-validating');
        }
    }
};

$('#myForm').validate({
    rules: {
        Age: {
            required: ValidationRules.requiredForFull
        }
    }
});
```

The biggest issue with this setup is it's a lot of duplicate code setting the custom rule for each form field. Something simpler that would let me use the `required` attribute and then validate like `$('#myForm').valid({ rules: { required: false }})` is what I was hoping for.

**Comment by Arkni** [comment]
I think what you are looking for is something like [`jQuery.validator.addClassRules()`](https://jqueryvalidation.org/jQuery.validator.addClassRules/) which adds a compound class method (useful to refactor common combinations of rules into a single class). See examples in linked page.
