### ISSUE TITLE
onsubmit broken docs

### ISSUE THREAD

**Issue by larvanitis** [jquery-validation/jquery-validation#2106]
On page https://jqueryvalidation.org/validate/ `the onsubmit` option description contains two errors.

(1) "Set to a Function to decide for yourself when to run validation."

This is not true. Only boolean is supported - a truthy/falsy value to be exact.

(2) "A boolean true is not a valid value."

`true` is a valid value - any truthy is.

It looks like these are copy-paste left overs.

**Comment by Arkni** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? I'd be more than happy to walk you through the steps involved.

**Comment by larvanitis** [comment]
Sure. Do you want me to fix the docs or add the functionality?

**Comment by staabm** [comment]
as the functionality was not requested by anyone, please just fix the docs
https://github.com/jquery-validation/validation-content

**Comment by larvanitis** [comment]
Relevant pull request https://github.com/jquery-validation/validation-content/pull/42
