### ISSUE TITLE
Need to pass the ID form after successful submitting the form data

### ISSUE THREAD

**Issue by DjonyBastone** [jquery-validation/jquery-validation#2107]
Need help.

I set Google tag Manager, I need to pass the ID form after successful submitting the form data.

How to return the object with ID form?

tried to pass in the object this way:
```
$.validator.setDefaults({
        submitHandler: function(form) {
            var thisForm = $(form);
            ...
            $.ajax({
                type: "POST",
                url: thisForm.attr("action"),
                data: thisForm.serialize(),
                success: function(thisForm) {
                    dataLayer.push({'event': 'formSubmit', 'formId': thisForm.attr('id')});
                    // window.location = "/thank-you.html";
                }
            }).done(function() {
                thisForm.find("input:not([type=hidden], [type=radio])").val("");
                submitBtn.removeAttr('disabled', 'disabled');
            });
            return false;
        }
    });
```
reply - Uncaught TypeError: thisForm.attr is not a function

There is another error, but does not apply to this problem - Uncaught TypeError: e[d].call is not a function

The complete code with validation posted here [jsfiddle](https://jsfiddle.net/DjonyBastone/7g8s6pLn/3/)

Please help to understand!!!

**Comment by Arkni** [comment]
You have an error in your ajax call. The `success` callback doesn't take a jQuery object (in your case the thisForm) as argument. From [`$.ajax`](http://api.jquery.com/jquery.ajax/) docs:
>success:
>Type: Function( Anything data, String textStatus, jqXHR jqXHR )  
>
>A function to be called if the request succeeds. The function gets passed three arguments: The data returned from the server, formatted according to the dataType parameter or the dataFilter callback function, if specified; a string describing the status; and the jqXHR (in jQuery 1.4.x, XMLHttpRequest) object. As of jQuery 1.5, the success setting can accept an array of functions. Each function will be called in turn. This is an Ajax Event.

Also, the parameter `thisForm` that you have on your `success` callback is shadowing the outer `thisForm` variable, so only the inner one will be used.

**Comment by DjonyBastone** [comment]
In this case, we remove all of the `success`.
Code moved to the `done` method.
```
$.validator.setDefaults({
        submitHandler: function(form) {
            var thisForm = $(form);
            ...
            $.ajax({
                type: "POST",
                url: thisForm.attr("action"),
                data: thisForm.serialize(),
                success: function() {
                    // window.location = "/thank-you.html";
                }
            }).done(function() {
                dataLayer.push({'event': 'formSubmit', 'formId': thisForm.attr('id')});    
            });
            return false;
        }
    });
```
The question remains open - How to return the object with ID form?

Form validation is assigned through the class:
```
$('.form').validate({
    ...
});
```
This is necessary because on one page there are several forms.

Or need for each form to create a validation?

**Comment by Arkni** [comment]
> This is necessary because on one page there are several forms.
> 
> Or need for each form to create a validation?

You need to attach the plugin to every form separately (e.g. using `.each` or a loop).

Also, I just noticed it. In your code, you have passed `onfocussout: true` and `onkeyup: true` to `validate` method. But, the only valid values for those options are either `false` or a function.

See https://jqueryvalidation.org/validate/#onfocusout

**Comment by DjonyBastone** [comment]
Thank you!
Error `onfocusout` disappeared.
To solve GTM approached it:
```
    .done(function() {
                dataLayer.push({'event': 'formSubmit', 'formId': thisForm.attr('id')});    
            });
```
