### ISSUE TITLE
Cannot submit form 

### ISSUE THREAD

**Issue by phongbv** [jquery-validation/jquery-validation#2108]
I'm trying to submit form with custom format number. But I got an error: **The field AmountNonChecking must be a number** but when I used jquery to validate it was passed. What's wrong?
![2017-11-24_084724](https://user-images.githubusercontent.com/15614199/33192340-64bd08d6-d0f4-11e7-8a75-e4faec732f5a.png)

**Comment by Matiyeu** [comment]
Because your input is probably a number?

**Comment by Arkni** [comment]
Hi @phongbv,

If you still have this problem, please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a set of reproducible steps and I will look into it as soon as possible.
