### ISSUE TITLE
Email validation accepts domain with no dot

### ISSUE THREAD

**Issue by daerimin** [jquery-validation/jquery-validation#2117]
The plugin accepts email addresses with no dot in the domain.

1.) Go to https://jqueryvalidation.org/email-method/
2.) Enter "anything@something"
3.) Click "Validate!" button

This behavior is also consistent when using the plugin with input type="email" fields.

**Comment by RobJohnston** [comment]
This is by design.  See the README.md:

> **IMPORTANT NOTE ABOUT EMAIL VALIDATION**. As of version 1.12.0 this plugin is using the same regular expression that the [HTML5 specification suggests for browsers to use](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider [using a custom method](https://jqueryvalidation.org/jQuery.validator.addMethod/).
> In case you need to adjust the built-in validation regular expression patterns, please [follow the documentation](https://jqueryvalidation.org/jQuery.validator.methods/).

If you think about it, "admin@localhost" **_is_** a valid e-mail address.

**Comment by staabm** [comment]
Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.

**Comment by raisonon** [comment]
It would be great to have an option to enable the check for this.

For example when using this to register a user with WordPress it is unable to and wp_create_user() function from WP errors (empty_user_login).

Therefore we'll need a way to validate for this (and/or fix WP create user function).

**Comment by staabm** [comment]
since a lot of applications have different requirements we would only get a huge list of options.

simplest solution for you and us is that you write a custom method (as quoted in above comments) and let it do exactly what you need.

**Comment by raisonon** [comment]
Ok, final note just to say that the expected email format includes a .com or .org tld

so
1. name@domain.com is going to be nearly 100% use case
2. name@domain, although possible per HTML5 specs is not going to be used.

So, it would be good to check/validate for this.

Thanks and sorry for pestering!

**Comment by staabm** [comment]
all I can say was already cited in the https://github.com/jquery-validation/jquery-validation/issues/2117#issuecomment-350558717

**Comment by incodemode** [comment]
The Idea of using a library and not html5 is because html5 sometimes do not comply with reality, a custom function would also break localization.

**Comment by YoomiAB** [comment]
Thanks RobJohnston for pointing out an alternative solution! 
"name..surname@domain" (note the double dots) was accepted - which presented some problems in my application. 
 
This simple script below did the trick for me. 
```
jQuery.validator.addMethod("myEmail", function(value, element) {
  var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{
  return this.optional(element) || re.test(String(value).toLowerCase());
}, "Please enter email");
```
