### ISSUE TITLE
Confirm Password

### ISSUE THREAD

**Issue by BMK91** [jquery-validation/jquery-validation#2118]
```
$("#register-form").validate({
    rules: {
        password: {
            required: true,
            minlength: 6,
        },
        confirm_password: {
            required: true,
            equalTo: {
                param: "#password",
                depends: function (element) {
                    //console.log($('#password').valid());
                    return $('#password').valid();
                }
            }
        }
    }
});
```

I'm having an issue with the confirm password, may be in the plugin itself.
Having the following step: (Also found issue with vice versa)
1. Enter password.
2. Enter confirm-password with error. (Leave as it is)
3. Enter password which match with confirm password.

Now try to match both. The confirm password still have error, though both same.

I also trying to validate it manually $('#confirm_password').valid()
Still it returns true. (Because it matches with the previous value that matched)

Posted on stackoverflow too.
https://stackoverflow.com/questions/47739546/jquery-validator-for-password

Help me around the same.

**Comment by Matiyeu** [comment]
Hey,
Shows the html and what version do you use ?
