### ISSUE TITLE
showErrors breaks on non-existing field

### ISSUE THREAD

**Issue by paulscheltema** [jquery-validation/jquery-validation#212]
When using the showErrors() method and sending a field that does not exist (at that point) causes the plugin to break with:
Uncaught TypeError: Cannot read property 'name' of undefined

reproduce

<form id="form">
<input type="text" name="test1">
</form>

<script>
var valid_form = $(#'form').validate();
valid_form.showErrors({"test2":"required"});
</script>

here the field that has an error, test2, doesnt exist in the form and passing this rule to the showErrors call will break the script

fix:
in function idOrName add the following line
if (!element) return;

**Comment by szelga** [comment]
this could be quite annoying when validation (at least, partly) is done on server side, and backend returns error for non-existing field. in that case, backend, obviously, needs to be fixed, but the exception message ("the element is not found" or something) is not helpful at all.
