### ISSUE TITLE
jquery validate plugin with bootstrap selectpicker - ignore not visible inputs, but submit dont work

### ISSUE THREAD

**Issue by rediasa** [jquery-validation/jquery-validation#2124]
Please help me.
I use boostrap selectpicker and jquery validate.
Jquery validate could not validate selectpicker, to validate selectpicker I have to include this in my code:
`$('#myform').validate().settings.ignore = ':not(select:hidden, input:visible, textarea:visible)';`

Then jquery validate started validating the selectpicker, but it's as if it does not recognize if the item is filled, it continues to require the item, and the form's submit button does not work.

If anyone has had this problem, please help me. 
Thank you so much for your attention!

**Comment by rediasa** [comment]
UPDATE: **SOLVED**! I put **minlength**: 2 for a validation of the field selectpicker, so I removed the minlength and the validation worked correctly.

**Comment by Arkni** [comment]
Closing this as the OP have already solved their issue as mentioned in the previous comment.
