### ISSUE TITLE
option to disable attribute validation.

### ISSUE THREAD

**Issue by susheel61** [jquery-validation/jquery-validation#2125]
### Subject of the issue
I feel attribute validations should be disabled by default and enabled as per need.

### Environment
* v1.12.0
* all browsers

### Steps to reproduce
Type email field will have ootb error message without adding any rule. "Email not valid error"

### Expected behaviour
Default attribute validations should be disabled. Should be enabled as per need.
This is because I created a authoring interface where i can added multiple validations on same field using authoring. Even If I remove all the validations still its showing the default error message.

### Actual behaviour
Shows error message without even adding any rule for attribute type email.
$.validator.attributeRules( element ).
Happening due to this code a 179 line core js.

**Comment by Arkni** [comment]
Hi @susheel61,

The plugin is reading the rules from the attributes by default, and we don't have an option to disable that. Disabling the default behavior will be considered a BC break, so we are avoiding it in the meantime.

For now, if you want to disable reading the rules from attributes, set `$.validator.attributeRules` to a new function that returns an empty object:
```js
$.validator.attributeRules = function() {
  return {};
};
```

Will close for now and revisit in case someone else requested the same.

Thanks!

**Comment by susheel61** [comment]
Thanks for responding.. I used text field for time being. But I can try what you suggested.

**Comment by Arkni** [comment]
@susheel61 
In case you want to still use the `email` input type, then disable the `email` validator:
```js
$("form_selector").validate({
  rules: {
    "email_input_name": {
      // ...
      email: false  // <-- Set it to `false`
    }
  }
});

**Comment by susheel61** [comment]
got it thanks :)
