### ISSUE TITLE
Bootstrap 4 support needs to be tested

### ISSUE THREAD

**Issue by vairamsvsjdo** [jquery-validation/jquery-validation#2130]
### Checklist for this issue
If your issue is about the regex used in `email` rule, please note that as of version 1.12.0 this plugin is using the same regular expression that the HTML5 specification suggests for browsers to use (https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider using a custom method.
In case you need to adjust the built-in validation regular expression patterns, please follow the documentation (http://jqueryvalidation.org/jQuery.validator.methods/).

### Subject of the issue
Bootstrap 4 support needs to be tested

### Your environment
1.17.0
* Chrome

### Steps to reproduce
jquery-validation/demo/bootstrap/index.html 
needs to use Bootstrap 4.0.0 to test for bootstrap 4 support

### Expected behaviour
jquery-validation/demo/bootstrap/index.html 
needs to use Bootstrap 4.0.0 to test for bootstrap 4 support

### Actual behaviour
jquery-validation/demo/bootstrap/index.html 
uses Bootstrap 3

**Comment by tech19** [comment]
asdfa

**Comment by Arkni** [comment]
Fixed by #2173
