### ISSUE TITLE
Adding Khmer language

### ISSUE THREAD

**Issue by DFF-fred** [jquery-validation/jquery-validation#2135]
Hi!
I'd like to add Khmer language as a supported language but I am not sure how to get the source message_ISO.js file in English to translate. Can someone help me out?
Thank you.

**Comment by Arkni** [comment]
Hi @DFF-fred 

Thanks for your interest.

The format of the file is the same as others in [`src/localization`](https://github.com/jquery-validation/jquery-validation/blob/master/src/localization) folder. You can use the following template as a starting point and change the texts with their corresponding translation in Khmer language:

```js
/*
 * Translated default messages for the jQuery validation plugin.
 * Locale: KM (Central Khmer ; ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ)
 */
$.extend( $.validator.messages, {
	required: "This field is required.",
	remote: "Please fix this field.",
	email: "Please enter a valid email address.",
	url: "Please enter a valid URL.",
	date: "Please enter a valid date.",
	dateISO: "Please enter a valid date (ISO).",
	number: "Please enter a valid number.",
	digits: "Please enter only digits.",
	equalTo: "Please enter the same value again.",
	maxlength: $.validator.format( "Please enter no more than {0} characters." ),
	minlength: $.validator.format( "Please enter at least {0} characters." ),
	rangelength: $.validator.format( "Please enter a value between {0} and {1} characters long." ),
	range: $.validator.format( "Please enter a value between {0} and {1}." ),
	max: $.validator.format( "Please enter a value less than or equal to {0}." ),
	min: $.validator.format( "Please enter a value greater than or equal to {0}." ),
	step: $.validator.format( "Please enter a multiple of {0}." )
} );
```

The file name should be `messages_km.js`

After that, you're welcome to send us a pull request and we will be happy to merge it :)

_NOTE:_ I got the language code and native name from wikipedia. If they are wrong, please change them to the correct ones.

**Comment by staabm** [comment]
I will close this issue for now.

feel free to ask further question or provide a Pull Request with the localized files.

thank you.

**Comment by DFF-fred** [comment]
Hi! Thank you for the reply. I actually made a file from the French translation but still have the same issue. Your language code is right by the way. Is there a need to add km as another available translation somewhere else in the file such as jquery.validate.min.js? I get TypeError: j is undefined for Khmer which I don't get for other languages.

**Comment by Arkni** [comment]
@DFF-fred 

Can you share with us what you have done so far?
I would like to take a look and suggest changes if required.

**Comment by DFF-fred** [comment]
Sure. I just added the function before the above localized text and } )); at the bottom into a messages_km.js . Then I created a minified version which I added next to it into messages_km.min.js. Both files are placed together with the other localized versions of the same files into the localization folder.

**Comment by Arkni** [comment]
@DFF-fred 

Can you please share with us the file you created? you can either put its content in a comment or use gists.github.com to create a new gist and share with us the link.

Without that, I'm afraid I can't help you as I don't clearly understand your problem.

Thanks.

**Comment by DFF-fred** [comment]
Sure. There are 2 files: the messages_km.js and the messages_km.min.js . This is the non-minified version below:
(function( factory ) {
	if ( typeof define === "function" && define.amd ) {
		define( ["jquery", "../jquery.validate"], factory );
	} else {
		factory( jQuery );
	}
}(function( $ ) {


/*
 * Translated default messages for the jQuery validation plugin.
 * Locale: KM (Central Khmer ; ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ)
 */
$.extend( $.validator.messages, {
	required: "This field is required.",
	remote: "Please fix this field.",
	email: "Please enter a valid email address.",
	url: "Please enter a valid URL.",
	date: "Please enter a valid date.",
	dateISO: "Please enter a valid date (ISO).",
	number: "Please enter a valid number.",
	digits: "Please enter only digits.",
	equalTo: "Please enter the same value again.",
	maxlength: $.validator.format( "Please enter no more than {0} characters." ),
	minlength: $.validator.format( "Please enter at least {0} characters." ),
	rangelength: $.validator.format( "Please enter a value between {0} and {1} characters long." ),
	range: $.validator.format( "Please enter a value between {0} and {1}." ),
	max: $.validator.format( "Please enter a value less than or equal to {0}." ),
	min: $.validator.format( "Please enter a value greater than or equal to {0}." ),
	step: $.validator.format( "Please enter a multiple of {0}." )
} );

} ));

**Comment by Arkni** [comment]
You file looks good in case you want to use it with `requirejs` or directly by simply importing the file in you HTML.

If you want to use it with, say webpack, you should also add the `module` part to you file:
```js
if ( typeof define === "function" && define.amd ) {
	define( ["jquery"], factory );

// <<<
} else if (typeof module === "object" && module.exports) {
	module.exports = factory( require( "jquery" ) );
// >>>

} else {
	factory( jQuery );
}
```

**Comment by DFF-fred** [comment]
Thank you very much for the support I really appreciate. I just don't know much in JS so I followed how the other languages files were structure. Where/how am I supposed to add this to the file, at the top, after the existing code? Also will that help me to get rid of this TypeError: j is undefined which I believe is creating the menu to be doubled? As I previously mentioned everything works well in Japanese and Korean.

**Comment by DFF-fred** [comment]
Thank you very much for the support I really appreciate. I just don't know much in JS so I followed how the other languages files were structured. Where/how am I supposed to add this to the file, at the top, after the existing code? Also will that help me to get rid of this TypeError: j is undefined which I believe is creating the menu to be doubled? As I previously mentioned everything works well in Japanese and Korean.
