### ISSUE TITLE
Can't Call Validate Twice With Different Options

### ISSUE THREAD

**Issue by haacked** [jquery-validation/jquery-validation#214]
I notice that if you call validate twice, the second time with different options, you'll get the same behavior both times because jQuery caches the validator for the form:

```
var validator = $.data(this[0], '
if ( validator ) {
return validator;
 }
```

I have a situation where I need to call validate twice on the same form, once with one set of options. The other time with another. I'd like to suggest adding a second optional parameter to validate called `nocache` or `reset`. If set to true, it would not check the cache for the validator object.

I'd be happy to submit a pull request if you think this is a good idea. :)

**Comment by zhangdimelody** [comment]
I am also the same problem,but there's no solution?
