### ISSUE TITLE
pickadate

### ISSUE THREAD

**Issue by qxygene** [jquery-validation/jquery-validation#2140]
http://amsul.ca/pickadate.js/

i cant validate this, readonly input issue.

is there a way to mark as valid ?

**Comment by staabm** [comment]
could you provide a jsfiddle/jsbin or similar to reproduce the issue you are seeing... could you describe what exactly the problem is, what you expected and what actually happened?

**Comment by aodysseos** [comment]
Just a wild guess. Your issue might be related to the date format? similar to this issue here: [1063](https://github.com/jquery-validation/jquery-validation/issues/1063).
