### ISSUE TITLE
Object doesn't support property or method 'hasAttribute' error appears on old IE browsers

### ISSUE THREAD

**Issue by lopezcjf** [jquery-validation/jquery-validation#2141]
I'm experiencing some issues with users that are working with old versions of IE (version 10 and below or 11 with enabled compatibility mode)
I have a really basic login page and using version 1.17.0 but this was happening also on previous versions.

The error appears when focusing out from a required field. The following error is displayed on the console:

**Object doesn't support property or method 'hasAttribute'**

The error is thrown on line 705

```
if ( element.hasAttribute( "contenteditable" ) ) {
	val = $element.text();
} else {
	val = $element.val();
}
```

Somehow on old versios of IE the element object doesn't contain that method.
I was able to fix this by changing that line to the jquery function hasOwnProperty instead.

` $element.hasOwnProperty( "contenteditable" )`

The same can be found on line 152 and the same error should appear there.

This is my validation setup:

```
$('.login-form').validate({
    errorElement: 'span', 
    errorClass: 'help-block', 
    focusInvalid: false, 
    rules: {
        UserName: {
            required: true
        },
        Password: {
            required: true
        }
    },
    messages: {
        UserName: {
            required: resources.IngresarUsuario
        },
        Password: {
            required: resources.IngresarPWD
        }
    },
    invalidHandler: function (event, validator) {
        $('.alert-danger', $('.login-form')).show();
    },
    highlight: function(element) { 
        $(element).closest('.form-group').addClass('has-error');
    },
    success: function (label) {
        $(label).closest('.form-group').removeClass('has-error');
        $(label).remove();
    },
    errorPlacement: function (error, element) {
        $(error).insertAfter($(element).closest('.input-icon'));
    },
});
```

**Comment by Arkni** [comment]
Thanks a lot for filling this issue!

From mdn docs, [`hasAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/hasAttribute) is supported as of IE8. And because we still support down to jQuery 1.7.2 which in its own support IE 7, we have to replace all the 4 occurences of `hasAttribute` with their equivalent in jQuery using [`.attr()`](https://api.jquery.com/attr/).

Would you like to write a patch for this? I'd be more than happy to walk you through the steps involved.

**Comment by lopezcjf** [comment]
Hi Arkni,
I'm not experienced as a contributor in github, but if you can point me some useful resources to do this in the right way, I would gladly work on this.
