### ISSUE TITLE
Popover ID is changed when calling $(el).show()

### ISSUE THREAD

**Issue by adrianstas** [jquery-validation/jquery-validation#2144]
I'm not sure if this can be treated as error but when popover is hidden and showed the ID of the popover (and of course aria-describedBy property in target element) is changed. Don't know why

Demo: https://codepen.io/gtdc/pen/NyBaoR

If this is a feature - please for close.

**Comment by Arkni** [comment]
Based on the code on the provided codepen, I see that this issue has nothing to do with this plugin.

I will close this for now.

Please feel free to ask if you have any further question about this plugin.

Thanks!
