### ISSUE TITLE
How to show multiple errors of one field

### ISSUE THREAD

**Issue by abdellatif05** [jquery-validation/jquery-validation#2146]
### How to show multiple errors of one field in the same time
For example, I have a password field and i have 4 rules : 
 1-One uppercase
 2-One lowercase
 3-One number
 4-At least 8 characters
So I want to show all the errors not one,
->if I write "Azerty"  => it should be show rule 3 and 4
->if I write "azerty" => it should be show rule 1, 3 and 4
->if i wirte "azertyazerty" => it should be show rule 1 and 3 

### All environments
* jquery-validate v1.15.0
* all browser

**Comment by Arkni** [comment]
Hi @abdellatif05 

Thanks for opening this issue. Unfortunately, it's not implemented currently, and I don't think it will happen in the near future. This plugin only shows you the message of the first failling rule.
