### ISSUE TITLE
Validation on select element with Selectize.js plugin not working on other bootstrap tab panel

### ISSUE THREAD

**Issue by nirav2410** [jquery-validation/jquery-validation#2151]
### Subject of the issue
I am using selectize jquery plugin ( https://selectize.github.io/selectize.js/ ) on select elements. and using 
jQuery Validation Plugin v1.16.0 to validate. I am having bootstrap tab panel.

I have used selectized select element in all 4 tab panels but validation works only for 1st active tab panel and not validating other select elements in other tab panels.

Please draw me to the solution.

**Comment by Arkni** [comment]
By default, this plugin will ignore hidden fields. You have to set [`ignore`](https://jqueryvalidation.org/validate/#ignore) option to empty string `""` if you want your fields to be validated:

```js
$("your_form_selector").validate({
  ignore: "",
  // ...
});
```

If that's not the issue, please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) to help us reproduce the issue.
