### ISSUE TITLE
Translate custom method message

### ISSUE THREAD

**Issue by waspinator** [jquery-validation/jquery-validation#2152]
### Subject of the issue
Translate custom method message

### Your environment
* version of `jquery-validate`: 1.17.0
* which browser and its version: Firefox 57

### Steps to reproduce
```
$.validator.addMethod("my_custom_method", function(value, element, parameters) {
    return true;
}, 'the message');
```

In messages_fr.js

```
$.extend( $.validator.messages, {
    my_custom_method: "the message, but in French"
});
```

if I remove `'the message`', then it gets translated into french, but the default produces an error.

```
Warning: No message defined for field
```

Can I create a `messages_default.js` or `messages_en.js` or something similar to add custom messages without modifying the actual library? https://github.com/jquery-validation/jquery-validation/blob/a355a0fe2970c92b801bf6d7621c6b90f412fa3d/src/core.js#L344

### Expected behaviour
The message should be translated

### Actual behaviour
The message isn't translated

All default messages are translated as expected, but I'm not sure how to add custom method messages.

**Comment by RobJohnston** [comment]
I think that you're just missing one little thing.  Replace `'the message'` in your custom method with `$.validator.messages.my_custom_method`.

```js
$.validator.addMethod("my_custom_method", function(value, element, parameters) {
    return true;
}, $.validator.messages.my_custom_method);
```

And ensure that you create that "messages_en.js" file too.

```js
$.extend( $.validator.messages, {
    my_custom_method: "the message"
});
```
