### ISSUE TITLE
No dist folder inclded in your plugin

### ISSUE THREAD

**Issue by nevergiveup777** [jquery-validation/jquery-validation#2153]
### Subject of the issue
No dist folder included in your plugin

### Your environment
WordPress

### Steps to reproduce
I have downloaded the zip file and after decompressing the file, I tried to run the demo but they are not working because there is not actual dist folder and jquery.validate.js

### Expected behavior
Example file should work as normal

### Actual behavior
 jquery.validate.js file is not being loaded

**Comment by Arkni** [comment]
Hi @nevergiveup777

Thanks for opening this issue.

We don't include the `dist` folder in `master` branch, but instead we include it in the tagged release. If you selected a tag from the dropdown, say `1.17.0`, you will see the `dist` folder there. So, you should download the zip of the tag not of `master` branch.

You can also download the zip `jquery-validation-${version}.zip` included in every release. See release [`1.17.0`](https://github.com/jquery-validation/jquery-validation/releases/tag/1.17.0) for example.
