### ISSUE TITLE
No option to disable default error labels

### ISSUE THREAD

**Issue by scssyworks** [jquery-validation/jquery-validation#2157]
There is no option to disable default error labels and use the existing ones present in forms.

**Issue 1:**
If I change errorElement to span, it does not pick existing error elements that are already there in form. For example: If I already have a span error label like below:
```
<input type="text" name="someName" />
<span class="error"></span>
```
In validate configuration:
```js
$(form).validate({
    ...
    errorElement: 'span'
});
```
It only works if errorElement is <code>\<label></code> and the one present in DOM has a <code>for=</code> attribute.
```
<input type="text" name="someName" />
<label for="someName" class="error"></span>
```
In validate configuration:
```js
$(form).validate({
    ...
    errorElement: 'label' // <-- This is default in plugin and works as expected
});
```

**Issue 2**
**Alternatively**, i would like to disable the default error labels feature, and toggle existing labels with the help of <code>highlight</code> and <code>unhighlight</code> callbacks. The only option that worked for me was to pass <code>errorPlacement</code> option with an empty function which again didn't work properly when existing error elements were <code>\<label></code>s with <code>for=</code> attribute.
```js
$(form).validate({
    ...
    errorPlacement: function () {}  // Seems like a hack to me
});
```
I hope I have made the descriptions clear to understand.

Thanks in Advance!
Sachin

**Comment by scssyworks** [comment]
Can please someone address to this thread?

**Comment by Arkni** [comment]
Hi @scssyworks,

Sorry about that. I will reopen the issue and come back to you when I get some free time.
