### ISSUE TITLE
Uncaught TypeError: Cannot read property 'settings' of undefined

### ISSUE THREAD

**Issue by tanvan81** [jquery-validation/jquery-validation#2158]
I have code

`   function initValidateQuestion() {
            var submitSettings = $.data($("#frmQuestion").get(0), 'validator').settings;

            submitSettings.messages = {
                Content: {
                    required: "....."
                },
                FullName: {
                    required: "xxxx"
                },
                Email: {
                    required: "xxxxx"
                },
            };
        }
`

This code run on Jquery 2.x. But when I upgrapde jquery 3.3.1, I run this code, get error

> jQuery.Deferred exception: Cannot read property 'settings' of undefined TypeError: Cannot read property 'settings' of undefined

> Uncaught TypeError: Cannot read property 'settings' of undefined

How do I fix this bug ???

**Comment by HassanGulzar** [comment]
Same issue here.

**Comment by Arkni** [comment]
Hi @tanvan81 & @HassanGulzar 

I think we have this fixed in master, but not released yet. Could you please test with the version in master and see if the issue persist. You can grab the dist file from this gist: https://gist.github.com/Arkni/495730a47b52b570b150d4375bfbb7c7

Thanks!

**Comment by mprandot** [comment]
same problem here, I changed the code, but it did not work.

**Comment by Chealer** [comment]
This is similar to issue #1267 .

**Comment by Chealer** [comment]
I am seeing this error with 1.13:
jquery.validate.js:1278 Uncaught TypeError: Cannot read property 'settings' of undefined
    at Function.staticRules (jquery.validate.js:1278)
    at jQuery.fn.init.rules (jquery.validate.js:196)
    at HTMLInputElement.<anonymous> (jquery.validate.js:665)
    at jquery.js:2816
    at Function.grep (jquery.js:424)
    at winnow (jquery.js:2815)
    at jQuery.fn.init.filter (jquery.js:2879)
    at $.validator.elements (jquery.validate.js:647)
    at $.validator.checkForm (jquery.validate.js:464)
    at $.validator.form (jquery.validate.js:452)


staticRules | @ | jquery.validate.js:1278
  | rules | @ | jquery.validate.js:196
  | (anonymous) | @ | jquery.validate.js:665
  | (anonymous) | @ | jquery.js:2816
  | grep | @ | jquery.js:424
  | winnow | @ | jquery.js:2815
  | filter | @ | jquery.js:2879
  | elements | @ | jquery.validate.js:647
  | checkForm | @ | jquery.validate.js:464
  | form | @ | jquery.validate.js:452
  | (anonymous) | @ | jquery.validate.js:105
  | dispatch | @ | jquery.js:5183
  | elemData.handle | @ | jquery.js:4991
  | trigger | @ | jquery.js:8288
  | (anonymous) | @ | jquery.js:8327
  | each | @ | jquery.js:354
  | each | @ | jquery.js:189
  | trigger | @ | jquery.js:8326
  | jQuery.fn.(anonymous function) | @ | jquery.js:10212
  | (anonymous) | @ | tiki-jquery.js:3310
  | dispatch | @ | jquery.js:5183
  | elemData.handle | @ | jquery.js:4991



The error still occurs with the file offered by Arkni.

**Comment by Matthewsre** [comment]
I upgraded jquery to 3.3.1 and started getting this same error. I tried the 1.17.1-pre file and the issue persists.

Happens from calling the following:

`$("#contacts-validation").rules("add", "primaryContact");`

Loaded up the non-minified version of 1.17.0 and generated to get the line number:

Uncaught TypeError: Cannot read property 'settings' of undefined
    at jQuery.fn.init.rules (jquery.validate.js:162)

Looks like the offending line for me is here:

`settings = $.data( element.form, "validator" ).settings;`

**Comment by tanvan81** [comment]
Still error

I've jquery.validate.1.19.min.js.

**Comment by tanvan81** [comment]
Still error

**Comment by Lefthandmedia** [comment]
me too still error

**Comment by nivle** [comment]
For some reason, a form with no fields to validate(empty form), gives this error...

**Comment by edika99** [comment]
Same here. 

Uncaught TypeError: Cannot read property 'settings' of undefined
    at init.rules (jquery.validate.js:164)
    at HTMLInputElement.<anonymous> (buyshares.js:22)
    at HTMLInputElement.dispatch (jquery-1.10.2.min.js:5)
    at HTMLInputElement.v.handle (jquery-1.10.2.min.js:5)

when trying to add a simple
