### ISSUE TITLE
Max Word count with French Accented Character Wrong

### ISSUE THREAD

**Issue by bozzit** [jquery-validation/jquery-validation#2161]
### Subject of the issue
Using the maxWord Additional Method with French accented characters cause 2 words to be counted for each accented characters.

### Your environment
* version of `jquery-validate`:  * jQuery Validation Plugin v1.17.1-pre
* which browser and its version: Firefox Quantum 59.0.1

### Steps to reproduce
```js
QUnit.test(` "maxWords", function( assert ) {
        var method = methodTest( "maxWords" ),
                maxWords = 6;

        assert.ok( method( "I Sélectionner am a sentence Sélectionner", maxWords ), "Max Words" );
      
} );
```
### Expected behaviour
Should PASS it is exactly 6 Words

### Actual behaviour
Test Fails

### Potential Solution:

Instead of Matching on regex  /\b\w+\b/g 

Use this one:  /[a-zA-ZàâäèéêëîïôœùûüÿçÀÂÄÈÉÊËÎÏÔŒÙÛÜŸÇ0-9]+/g

This may and will probably break Asian Character and other similar character sets.

I'm not familiar enough with the inner workings  of this plugin to know if this will have adverse affect somewhere else.  Using this pattern All the Unit Tests pass.

**Comment by RobJohnston** [comment]
We've seen the exact same behaviour in the WET-BOEW project (which uses jQuery Validation):  https://github.com/wet-boew/wet-boew/issues/8242

I think a better solution would be to count the number of spaces to determine word count.  You'll never get all characters for all languages in a regex.

**Comment by bozzit** [comment]
The following article may be of use:  
https://www.thecodedeveloper.com/count-word-contain-utf-8-character-in-javascript/
