### ISSUE TITLE
Re-validate on submit even when field values haven't changed

### ISSUE THREAD

**Issue by Swennet** [jquery-validation/jquery-validation#2168]
I have a form which validates just fine. When the submit button is clicked, it validates the fields, and proceeds if there are no errors. The form submit time is logged, and a next submit is supposed to show a validation error saying "You can only submit this form every 15 minutes".

However, when the submit button is clicked, it does not re-validate the form, because no changes have been made to any of the fields.

Is there a setting to force a validation each time? Even if no fields have changed?

### Your environment
* Version: 1.17.0
* Latest Chrome & Firefox

### Steps to reproduce
* Submit form. (Through AJAX, no page reload!)
* Custom validation passes, form hasn't been submitted in the last 15 minutes.
* Re-submit the form. (Still same page, no reload)
* No validation is done because fields haven't changed value since last submit.

### Expected behaviour
* On second submit I would like to re-validate a field, even if the input value hasn't changed.

### Actual behaviour
* No validation is done because input value hasn't changed. (I'm not actually sure if this is how jQuery validate works, but from my tests it does look this way.)

**Comment by thelastinuit** [comment]
For me, even if i change one of the fields (it was validated already and then I changed a field), it says is validate.

**Comment by Arkni** [comment]
Hi @SwenneT 

Could you please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/). I pretty sure the plugin will revalidate all your fields on submit. If it's not, maybe it's a bug that needs to be fixed.

**Comment by Arkni** [comment]
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the question or request made to them a month ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!

**Comment by Abdulmanan0315** [comment]
Use the following in the success function of ajax OR after submiting the form;

`$('#Your-form').validate().resetForm()`;
