### ISSUE TITLE
Custom HTML on error element

### ISSUE THREAD

**Issue by TioLancaster** [jquery-validation/jquery-validation#2170]
### Subject of the issue
I'm trying to write very specific HTML for our validation error messages, in this specific case it's a few nested spans tags.

### Your environment
* jQuery Validation Plugin v1.17.0
* The browser does not really matter

### Steps to reproduce
This is the HTML I'm trying to achieve:
```
<span class="invalid-feedback d-block">
    <span class="mb-0 d-block">
        <span class="initialism form-error-icon badge badge-danger">Error</span>
        <span class="form-error-message">This field is required</span>
    </span>
</span>
```

Can I do this with jQuery Validation? I've been trying with `errorPlacement`, and `showErrors`, but I wasn't able to make it work.

Because `errorPlacement` is only called once ( the first time the element is validated ), and from that point on, it just replaces the value.

For now I solved it, by simple putting the HTML around the error message, which for me isn't a very pretty solution.

If you would like, I could try to make a PR for this, creating a new option called template, which will be used to build the HTML for the error.

Thanks and best regards.

**Comment by Arkni** [comment]
> Can I do this with jQuery Validation? I've been trying with errorPlacement, and showErrors, but I wasn't able to make it work.

Yes! you can use `errorPlacement` as you said. You can build your custom HTML inside it and insert it after your validated element. Example:

```js
$("form_selector").validate({
  // ...
  errorPlacement: function(error, element) {
    var customError = $([
      '<span class="invalid-feedback d-block">',
      '  <span class="mb-0 d-block">',
      '    <span class="initialism form-error-icon badge badge-danger">Error</span>',
      '  </span>',
      '</span>'
    ].join(""));

    // Add `form-error-message` class to the error element
    error.addClass("form-error-message");

    // Insert it inside the span that has `mb-0` class
    error.appendTo(customError.find("span.mb-0"));

    // Insert your custom error
    customError.insertAfter( element );
  },
  // ...
});
```

**Comment by Rikijs** [comment]
Hello, @Arkni !
I am facing the same problem as @TioLancaster .
I usded the code sample that you provided.
It shows an error fine, but **it fails** to remove/hide _custom error element_.
(please see the screenshot: 1 = an eror message, 2 = part of an error still stays behind)

![field](https://user-images.githubusercontent.com/18629166/109315045-c1435980-7852-11eb-8c42-7aeff0c3c40a.png)

Addapted the code a little bit (but things are essentialy as in your example)
```
export function validationLocale()
{
    let $app_locale = $('html')[0].lang;

    jQuery.validator.setDefaults(
    {
        lang: $app_locale,
        errorElement: 'span',
        errorPlacement: function(error, element)
        {
            let customError = $([
                '<span class="invalid-feedback mt-0 mb-2 d-block">',
                '  <span class="error-box mb-0 d-block">',
                '    <span class="form-error-icon badge badge-danger text-uppercase">Error</span>',
                '  </span>',
                '</span>'
            ].join(""));

            // Add `form-error-message` class to the error element
            error.addClass("form-error-message");

            // Insert it inside the span that has `mb-0` class
            error.appendTo(customError.find('.error-box'));

            // Insert your custom error
            customError.insertBefore(element);
        },
        highlight: function (element, errorClass, validClass)
        {
            $(element).addClass('is-invalid');
            $(element).closest('.invalid-feedback').toggle();
        },
        unhighlight: function (element, errorClass, validClass)
        {
            $(element).removeClass('is-invalid');
            $(element).closest('.invalid-feedback').toggle();
        }
    });
}
```

**Comment by Rikijs** [comment]
https://jsfiddle.net/onrc9de1/36/
Created `jsfiddle` that shows te problem.
Check by writing a name that is less than 3 or more than 25 long.

**Comment by Rikijs** [comment]
Created a [question on StackOverflow](https://stackoverflow.com/questions/66398043/input-validation-with-jquery-validaton-bootstrap-v4-6-symfony-v5-2)

**Comment by Rikijs** [comment]
Sorry, had an error in my modifications.

**Comment by fadlysafyuddinmaulana** [comment]
> Hello, @Arkni, @TioLancaster ! I am facing the same problem. I used the provided code sample. It shows an error fine, but **it fails** to remove/hide _custom error element_. (please see the screenshot: 1 = an eror message, 2 = part of an error still stays behind)
> 
> ![field](https://user-images.githubusercontent.com/18629166/109315045-c1435980-7852-11eb-8c42-7aeff0c3c40a.png)
> 
> Addapted the code a little bit (but things are essentialy as in example above)
> 
> ```
> export function validationLocale()
> {
>     let $app_locale = $('html')[0].lang;
> 
>     jQuery.validator.setDefaults(
>     {
>         lang: $app_locale,
>         errorElement: 'span',
>         errorPlacement: function(error, element)
>         {
>             let customError = $([
>                 '<span class="invalid-feedback mt-0 mb-2 d-block">',
>                 '  <span class="error-box mb-0 d-block">',
>                 '    <span class="form-error-icon badge badge-danger text-uppercase">Error</span>',
>                 '  </span>',
>                 '</span>'
>             ].join(""));
> 
>             // Add `form-error-message` class to the error element
>             error.addClass("form-error-message");
> 
>             // Insert it inside the span that has `mb-0` class
>             error.appendTo(customError.find('.error-box'));
> 
>             // Insert your custom error
>             customError.insertBefore(element);
>         },
>         highlight: function (element, errorClass, validClass)
>         {
>             $(element).addClass('is-invalid');
>             $(element).closest('.invalid-feedback').toggle();
>         },
>         unhighlight: function (element, errorClass, validClass)
>         {
>             $(element).removeClass('is-invalid');
>             $(element).closest('.invalid-feedback').toggle();
>         }
>     });
> }
> ```



> Hello, @Arkni, @TioLancaster ! I am facing the same problem. I used the provided code sample. It shows an error fine, but **it fails** to remove/hide _custom error element_. (please see the screenshot: 1 = an eror message, 2 = part of an error still stays behind)
> 
> ![field](https://user-images.githubusercontent.com/18629166/109315045-c1435980-7852-11eb-8c42-7aeff0c3c40a.png)
> 
> Addapted the code a little bit (but things are essentialy as in example above)
> 
> ```
> export function validationLocale()
> {
>     let $app_locale = $('html')[0].lang;
> 
>     jQuery.validator.setDefaults(
>     {
>         lang: $app_locale,
>         errorElement: 'span',
>         errorPlacement: function(error, element)
>         {
>             let customError = $([
>                 '<span class="invalid-feedback mt-0 mb-2 d-block">',
>                 '  <span class="error-box mb-0 d-block">',
>                 '    <span class="form-error-icon badge badge-danger text-uppercase">Error</span>',
>                 '  </span>',
>                 '</span>'
>             ].join(""));
> 
>             // Add `form-error-message` class to the error element
>             error.addClass("form-error-message");
> 
>             // Insert it inside the span that has `mb-0` class
>             error.appendTo(customError.find('.error-box'));
> 
>             // Insert your custom error
>             customError.insertBefore(element);
>         },
>         highlight: function (element, errorClass, validClass)
>         {
>             $(element).addClass('is-invalid');
>             $(element).closest('.invalid-feedback').toggle();
>         },
>         unhighlight: function (element, errorClass, validClass)
>         {
>             $(element).removeClass('is-invalid');
>             $(element).closest('.invalid-feedback').toggle();
>         }
>     });
> }
> ```

hello @Rikijs excus me can you example to custom validate in under input or everywhere
you can?

**Comment by fadlysafyuddinmaulana** [comment]
@Rikijs actualy default in jquery validate in under input text no  top input text can some example in under input text?

**Comment by Valentino-parkway** [comment]
> > Can I do this with jQuery Validation? I've been trying with errorPlacement, and showErrors, but I wasn't able to make it work.
> 
> Yes! you can use `errorPlacement` as you said. You can build your custom HTML inside it and insert it after your validated element. Example:
> 
> $("form_selector").validate({
>   // ...
>   errorPlacement: function(error, element) {
>     var customError = $([
>       '<span class="invalid-feedback d-block">',
>       '  <span class="mb-0 d-block">',
>       '    <span class="initialism form-error-icon badge badge-danger">Error</span>',
>       '  </span>',
>       '</span>'
>     ].join(""));
> 
>     // Add `form-error-message` class to the error element
>     error.addClass("form-error-message");
> 
>     // Insert it inside the span that has `mb-0` class
>     error.appendTo(customError.find("span.mb-0"));
> 
>     // Insert your custom error
>     customError.insertAfter( element );
>   },
>   // ...
> });
> I hope this helps!





https://jquerys.space/questions/what-is-the-best-way-to-create-a-toggle-function-for-a-specific-span-element-that-switches-between-showing-more-or
