### ISSUE TITLE
Soft fail on validation

### ISSUE THREAD

**Issue by jacobalberty** [jquery-validation/jquery-validation#2171]
### Subject of the issue
I have a validation that I would like to warn the user that their input doesn't meet criteria but allow them to proceed. 

### Your environment
* version of `jquery-validate`: 1.17.0

### Expected behaviour
I would like to allow a user to fill out a textarea with as many lines as they want but warn them if they exceed a certain number of calculated lines since their input may not fit on the label.
Code for the method would look something like the following:
```js
$.validator.addMethod("scriptlabel", function(value, element) {
        rows = $(element).data('rows');
        if (!rows)
            return true;
        cols = $(element).data('cols');
        var lines = value.split("\n");
        var lineCounter = 0;

        if (cols) {
            lines.forEach(function(line) {
                lineCounter+=Math.floor(line.length/cols);
            });
        }

        lineCounter += lines.length;

        return lines.length <= rows; 
}, "There may be too many lines for this to fit on a label.");
```

I just need some way for it to warn the user but still allow the form to submit (there are also other fields on the form that must block submission if validation fails) some way of adding another rule that says it can fail.
### Actual behaviour
Always blocks submission

**Comment by Arkni** [comment]
Hi @jacobalberty,

You don't need to create a validation method to do that, in fact you don't even need the plugin for that.

What you can do is to add the warning to your HTML as a `span` element (or anything else) and hide it by default. You only need to show it when the number of lines input by the user exceed the number of rows. To do so, we will use the `input` event (or `keyup`) to show or hide the warning.

Lets say you have the following HTML code:
```html
<div>
    <textarea name="labelContent"></textarea>
    <span class="label_content_warning hide">There may be too many lines for this to fit on a label.</span>
</div>
```

The JS code will look like this
```js
$("textarea[name='labelContent']").on("input", function() {
  var value = this.value;
  var rows = $(element).data('rows');
  
  if (!rows) {
    return;
  }

  var lines = value.split("\n");

  var warningSpan = $("span.label_content_warning");

  // Show the warning
  if (lines.length > rows && warningSpan.hasClass("hide")) {
    warningSpan.removeClass("hide").addClass("show");
  }

  // Hide it
  if (lines.length <= rows && warningSpan.hasClass("show")) {
    warningSpan.removeClass("show").addClass("hide");
  }
});
```
CSS:
```css
.show {
  display: block;
}

.hide {
  display: none;
}
```
