### ISSUE TITLE
DOC: provide an example for .ajaxSubmit

### ISSUE THREAD

**Issue by KES777** [jquery-validation/jquery-validation#2181]
### Subject of the issue
The example for `.ajaxSubmit` from the section 
https://jqueryvalidation.org/validate/#submithandler

just does normal submit. It is not clean should I use parameters in same ways as I did for `.ajax` or `.ajaxSubmit` provide some defaults?

Also over Internet examples recommends:

> return false to prevent normal browser submit and page navigation  

will be glad to see `.ajaxSubmit` example in documentation

Thanks

**Comment by KES777** [comment]
I do not know what I am doing wrong: even after include required scripts

[1234.html.txt](https://github.com/jquery-validation/jquery-validation/files/2087868/1234.html.txt)

I got the error:
```
XML Parsing Error: junk after document element Location: file:///home/kes/work/projects/safevpn/repo2/1234.html Line Number 2, Column 1:
```

**Comment by Arkni** [comment]
Hi @KES777,

`ajaxSubmit` is part of jQuery Form plugin (http://jquery.malsup.com/form/#api), and as such you should include that plugin too. Maybe we should include that as a comment in the docs.

**Comment by Arkni** [comment]
jquery-validation/validation-conten#48 should fix this
