### ISSUE TITLE
Fix typo in DOC

### ISSUE THREAD

**Issue by KES777** [jquery-validation/jquery-validation#2185]
>success
Type: String or Function()
If specified, the error label is displayed to show a valid element.

Do you mean **`success`**` label`?

**Comment by KES777** [comment]
Also success is passed two arguments, but they are not documented

**Comment by staabm** [comment]
Feel free to provide a pull request
https://github.com/jquery-validation/validation-content

**Comment by wewhite** [comment]
This is not an issue, formatting for user readability is not great.
 Current documentation shows:

> success
> Type: [String](http://api.jquery.com/Types/#String) or [Function](http://api.jquery.com/Types/#Function)()
> If specified, the error label is displayed to show a valid element.
> If a String is given, it is added as a class to the label. 
> If a Function is given, it is called with the label (as a jQuery object) and the validated input (as a DOM element).
> The label can be used to add a text like "ok!".

Which means that if `success`, you can use the `error` label to display `OK!`
Next paragraph shows two arguments passed, named `label` and `element`:

The callback gets passed two arguments:

> `label`
> Type: [jQuery](http://api.jquery.com/Types/#jQuery)
> The error label. Use to add a class or replace the text content.
>
> `element`
> Type: [Element](http://api.jquery.com/Types/#Element)
> The element currently being validated, as a DOMElement.
