### ISSUE TITLE
No message board

### ISSUE THREAD

**Issue by Chealer** [jquery-validation/jquery-validation#2198]
Please provide a place to discuss jquery-validation, at least development of jquery-validation. Either as a mailing list or as an Internet forum.

If there is already one, please document it on the website.

**Comment by Arkni** [comment]
Hi @Chealer,

I really appreciate your concerns.

Unfortunatelly, we don't have such a thing. Currently, we only rely on issues and provided PR from the comunity. And we don't always have enough time to work on a lot of improvements (suggested by some of the maintainers or by the comunity), nor we do to work on opened issues and PR.

Also, sometimes I ask the OPs to help fixing the raised issues, but rarely we receive PRs from them (of course, it's their own free time and no one is imposing anything on someone).

Overall, any suggestion is welcome :)

Thanks!

**Comment by staabm** [comment]
I cannot add more. @Arkni already mentioned all the relevant parts.

In case someone has a question it should be raised in our issue tracker.
I dont want to create a separate community channel, as our resources are already very limited. if - for whatever reason - someone needs to get in contact with us, please open a issue.
