### ISSUE TITLE
normalizer demo not working

### ISSUE THREAD

**Issue by jonycse** [jquery-validation/jquery-validation#2200]
### Subject of the issue

[normalizer demo(Using a global normalizer in conjunction with a local one) not working][1]

### Your environment
* version of `jquery-validate`: 1.16.0
* which browser and its version: 68.0.3440.106 (Official Build) (64-bit)

### Steps to reproduce

insert space on required filed

### Expected behaviour

Should not validate as success

### Actual behaviour

validate as success

[1]: https://jqueryvalidation.org/normalizer/#example:-using-a-global-normalizer-in-conjunction-with-a-local-one

**Comment by Arkni** [comment]
Hi @jonycse,

Thanks for opening this issue. It's our fault that we didn't change the demos to use the latest version of this plugin, as defining a global normalizer was only available as of the version `v1.17.0`. Will try to fix in the following days.

Thanks!

**Comment by jonycse** [comment]
thanks @Arkni, it is working perfectly on version v1.17.0

**Comment by Arkni** [comment]
Yes!

**Comment by techievickyr** [comment]
Hi @Arkni,

Using global normalizer with data attribute rules is not working while it's working perfectly when I'm using using validation via plugins settings (option rules).

Help me out where I'm doing wrong (Plugin - v1.15.1).

Thanks!

**Comment by Arkni** [comment]
Hi @techievickyr,

The global normalizer is only available as of the version 1.17.0. Also, using the normalizer through data attributes is not supported currently.

**Comment by techievickyr** [comment]
The global normalizer is working fine in plugin v1.15.1 when using via settings option, only have issue with data attributes.

Using the normalizer through data attributes is not supported currently.
<<< Is there any alternate through which I could achieve such functionality?

**Comment by Arkni** [comment]
Hi @techievickyr,

As I said in my previous comment, the global normalizer is only supported as of version 1.17.0 (because I implemented it myself). But the per element normalizer is supported as of version `1.15.0`.

See #1905 for usage example of combining the global and the per elements normalizers.

> Is there any alternate through which I could achieve such functionality?

You can set the global normalizer using `$.validator.setDefaults()`:
```js
$.validator.setDefaults({
  normalizer: function(value) {
    // ...
  }
});
```

**Comment by bytestream** [comment]
Please transfer / reopen in [validation-content](https://github.com/jquery-validation/validation-content) repository.
