### ISSUE TITLE
Don't work on SAFARI

### ISSUE THREAD

**Issue by marksumoto** [jquery-validation/jquery-validation#2201]
the script work on all browsers but NO on SAFARI

Can you help me pls?

**Comment by Arkni** [comment]
Hi @marksumoto,

Can you elaborate please? What doesn't work in Safari? 
Could you please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a set of reproducible steps?

Thanks!
