### ISSUE TITLE
Error message + error class not removed when form select is valid

### ISSUE THREAD

**Issue by romain-granai** [jquery-validation/jquery-validation#2202]
### Subject of the issue

After the first validation (all fields empty), the validation work properly (validation message showing and error class added to all fields), so now if I fill all the field the error message and the error class disappear/appear as expected for all fields apart for one select field.

here is the code: 
`      
$.validator.setDefaults({ ignore: ':hidden:not(select)' });
        jQuery.validator.addMethod("notEqual", function(value, element, param) {
            return this.optional(element) || value != param;
          }, "Please specify a different (non-default) value");

 $.validator.setDefaults({ ignore: ':hidden:not(select)' });
        jQuery.validator.addMethod("notEqual", function(value, element, param) {
            return this.optional(element) || value != param;
          }, "Please specify a different (non-default) value");

        $("#contact-message-main-contact-form-form").validate({
            rules: {
                'field_your_name[0][value]': 'required',
                'field_your_e_mail_address[0][value]': {
                    required: true,
                    email: true
                },
                'field_subject[0][value]': 'required',
                'field_category': { notEqual: 'choose-a-category' },
                'field_message[0][value]': 'required'
            },
            messages: {
                'field_your_name[0][value]': 'Please enter your name',
                'field_your_e_mail_address[0][value]': {
                    required: 'Please enter your email address',
                    email: 'Please enter a valid email address'
                },
                'field_subject[0][value]': 'What s the subject of your message?',
                'field_category': { notEqual: 'Please select a Category' },
                'field_message[0][value]': 'Please enter your Message'
            },
            errorPlacement: function(error, element) {
                if (element.attr('name') == 'field_category') {
                  error.insertAfter("#edit_field_category_chosen");
                } else {
                  error.insertAfter(element);
                }
              },
            submitHandler: function(form) {
                // do other things for a valid form
                $(form).find('.btn').addClass('sending');
                console.log($(form).find('.btn'));
                $.ajax({
                    url: form.action,
                    type: form.method,
                    data: $(form).serialize(),
                    success: function(response) {
                        
                        $(form).trigger("reset");
                        
                        $("<p class='feedback feedback--success'>Your message has been send successfully. We'll be in touch with you shortly</p>").appendTo('.form-actions');

                        setTimeout(function(){ 
                            $('.form-actions').find('.feedback').fadeOut( "slow", function() {
                                $('.form-actions').find('.feedback').remove();
                              });
                            
                        }, 1000);
                        
                    }            
                });
            }
        });` 

So the field that's not working is the field_category.

### Your environment
* version of `jquery-validate`: 1.17.0
* which browser and its version: Chrome last version

### Expected behaviour

By changing the value of the field_category field (select), this field should revalidate, if a correct value is selected the error class and the message should disappear, if a invalid value is selected, the error message and error class should show like all the other fields.

### Actual behaviour

on blur, on focus or on change, nothing happen. If a correct value is entered the select field is not revalidated, same if an invalid value is selected.

**Comment by xiaoyueyue165** [comment]
@romain-granai You can use it like this.

```javascript
  $("#contact-message-main-contact-form-form").validate({
        rules: {
          field_category: {
            notEqual: true,
          }
        },
        messages: {
          field_category: {
            notEqual: "Error prompt message",
          }
        }
      });
    });
```
