### ISSUE TITLE
v1.17.0 - mvc bundles minifying the file is causing issues.

### ISSUE THREAD

**Issue by Seabizkit** [jquery-validation/jquery-validation#2205]
Version: jQuery Validation Plugin v1.17.0
Error in browser console window:  Cannot read property 'parse' of undefined

**The below javascript works** when not minifyed but gives error on parse as when minifyed 
The file is being minified with mvc bundles mvc version 5.2.6 

java-script:
```
  var form = $("form:not(#file_upload):not(#logoutForm)");
                if (form.length > 1) {
                    alert("web form cannot be identified.");
                } else {
                    form.unbind();
                    form.data("validator", null);
                    $.validator.unobtrusive.parse(document);
                    form.validate(form.data("unobtrusiveValidation").options);
                }
```

**Comment by Arkni** [comment]
Hi @Seabizkit,

We don't have any property with the name `unobtrusive` in this plugin. I think you're using [`jquery-validation-unobtrusive`](https://github.com/aspnet/jquery-validation-unobtrusive) which uses this plugin under the hood.

You may need to open the issue in their issue tracker (https://github.com/aspnet/jquery-validation-unobtrusive/issues/new).

Thanks!

**Comment by Seabizkit** [comment]
FYI - i have narrowed this down... 
The MVC bundle include syntax... includes the unobtrusive with the usage of the *
```
var jqueryVal = new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"
```
Where as i thought was just  jQuery Validation Plugin
