### ISSUE TITLE
custom method always returns false value

### ISSUE THREAD

**Issue by tamizh1991** [jquery-validation/jquery-validation#2208]
The below code always returns false even if else blocks are working fine.

jQuery.validator.addMethod("Isexiting",function(value,element,param)
{
   
    //var inputElem = $('#Domain_ID').val();
    var request = $.ajax(
        {
            
            url: "/edit_asset_list/GetDomainID",
            type: "POST",
            data: {"Domain_ID":$('#Domain_ID').val().toLowerCase()},
            dataType: "json",
            
        });
        request.fail(function(err)
        {
            //return false
            console.log(err)
        });
        request.done(function(result)
        {
            
            if(result.existing==true)
            {
               return false                
            }   
            else
            {
                return true
            }   
            
        });
   
},"already exiting");

**Comment by Arkni** [comment]
Please open support issues on Stackoverflow and tag your question with `jquery-validate` tag. We only accept feature suggestions or bug reports.

Thanks!
