### ISSUE TITLE
Is there a way to validate a field outside of a form?

### ISSUE THREAD

**Issue by ppetree** [jquery-validation/jquery-validation#2209]
### Subject of the issue
Validating a field without that field being inside a form.

### Your environment
* version of `jquery-validate`: 1.17.0
* which browser and its version: all - mostly mobile

### Steps to reproduce
<input type=password id=pw1>

### Expected behaviour
I would like to call validate(element, rule_obj);

I'm working on an onboarding process.  I have a number of divs on a page, only the active div is visible. I want to validate the input fields on the active div before hiding that div and unhiding the next div in the onboarding sequence.

This would be a snap I could specify a single field to validate without using building 6-8 forms on a single page.  I don't want the data submitted until I have collected all the data from each div (screen) in the onboarding process.

Is there a way to do this that I can't find in the documentation?

**Comment by Arkni** [comment]
Hi @ppetree,

Sorry for taking so long to respond. Unfortunately, validating a input outside of a form is not supported and it was already requested in #2156. But you can work around this by using only one form and your onboarding will be inside it. That way you can use [`.valid()`](https://jqueryvalidation.org/valid/) or [`validator.element(element)`](https://jqueryvalidation.org/Validator.element/) to validate an element.

**Comment by ppetree** [comment]
No worries on the slow response, we all have day jobs. 

As you and I discussed earlier, there's a number of problems with using forms in mobile apps.  There are DOM limits, form action= is unnecessary and unwanted (I spent two full days chasing my tail on this the last time).

In mobile apps there are just so many one-off fields that one needs to validate that it would just be soooo nice to do something like:

```
$("#someid").validate(function(result) {
.
.
.},   { rules: {someid: { required: true, 
             errorPlacement: function(error, element) {
                $(element).parent().css('border-color', "red").attr("placeholder", error);
             },
             messages: { someid: " (requires a valid xyz)" },
             }}                                                    
  });

```

**Comment by SimonHeimberg** [comment]
Issue mentioned in https://github.com/jquery-validation/jquery-validation/issues/2209#issuecomment-427613626 is about form elements outside of a form, but belonging to the form (linked with the attribute `form="formName"`).
This issue is about elements not belonging to any form.

**Comment by DreamTear** [comment]
I found a way,work in DIV
```javascript
$('#commentForm input[type="submit"]').click(function() {
	setTimeout(function() {
		$('#commentForm').trigger('submit.validate')
	}, 500)
})
$('#commentForm input').each(function() {
	// this.form = $('#commentForm')
	Object.defineProperty(this, 'form', {get: function(){return $('#commentForm')[0]}})
})
```
