### ISSUE TITLE
regression after fix for bug #2141 (jquery-validation 1.18.0 doesn't work anymore with IE11)

### ISSUE THREAD

**Issue by tbl0605** [jquery-validation/jquery-validation#2211]
Hi,
I've tried latest 1.18.0 release, sadly the patch #2142 for bug #2141 introduced a bad regression on (at least) IE11, because validation doesn't work anymore!

The culprit is following code path in jquery.validate.js:

			if ( element.isContentEditable ) {
				val = $element.text();
			} else {
				val = $element.val();
			}

When you try my code example at https://liveweave.com/N6xRPw using latest Chrome or Firefox, validation works correctly because element.isContentEditable is false.
But when you use IE11, element.isContentEditable seems to be always true and jquery-validation "sees" a blank field because the variable "val" is always set to "". On the other side, element.hasAttribute( "contenteditable" ) correctly returns false on IE11.

Reverting the patch #2142 solves the problem for me, and everything seems to work again like it did in 1.17.0

Please could you have a look at this problem and confirm me that you can reproduce it on an other IE11 installation?
It would be then great to have a 1.18.1 release, because it's a very nasty regression ;)

Thank you!

**Comment by KuriosCurious** [comment]
I can confirm this is an issue with all 5 IE11 machines tested. Reversed to 1.17 until a fix is released.

**Comment by InsaLili** [comment]
Same issue here

**Comment by shapeshifta78** [comment]
same here :\

**Comment by Jesperanza** [comment]
Also having this issue

**Comment by staabm** [comment]
We are aware of the problem and will take action when time allows.

Thanks for your patience

**Comment by Rickimer** [comment]
Also having this issue(in mcmullon related). Stand also on problem - reqired error always fired. Reverting to v1.17.0 of jquery.validate fixed the problem fixed problem. I think problem in unobtrusive library. 
Pack of problem libraries: "jquery.validation": "1.18.0", "jquery-validation-unobtrusive": "3.2.11"

**Comment by staabm** [comment]
In case anyone is getting to this before we do: a PR for this problem is welcomd

**Comment by Arkni** [comment]
Could anyone of you test the fix and see if it fixes your issues? You can download the latest build file here: https://gist.githubusercontent.com/Arkni/103027bdde5a7ca9d4aedad455d49a30/raw/eba46f570e04d62eafbd4fb6a4e0bdb430a04f34/jquery-validation-contenteditable-fix.js

Thanks!

**Comment by HaciCayci** [comment]
Confirming 1.18.1-pre validation now works in my forms within internet explorer 11.

**Comment by InsaLili** [comment]
Version 1.18.1-pre now works for me on IE 11. Thanks for the fix

**Comment by tbl0605** [comment]
Version 1.18.1-pre also works for me on IE11. Thank you very much! Hope it will be merged soon ;)

**Comment by ngocdaothanh** [comment]
I'm having the same problem. Can you please release a new official version soon?

**Comment by staabm** [comment]
just published 1.19.0 with a fix for this issue.

sorry the any inconvenience this bug has caused for you guys.
