### ISSUE TITLE
Minifier settings

### ISSUE THREAD

**Issue by ltdeta** [jquery-validation/jquery-validation#2215]
### Subject of the issue
which options are used when minimizing `jquery.validate.js`
I tried to minimize the original file again with https://skalman.github.io/UglifyJS-online/
The result is not valid.

### Your environment
* version of `jquery-validate`: 1.18.0
* which browser and its version: ie11.09600

**Comment by staabm** [comment]
please find our build setup in https://github.com/jquery-validation/jquery-validation/blob/3a7e59365429598ef8612e8d57580870178c5a52/Gruntfile.js#L72

usually minifying an already minified lib is not supported by those minify tools and therefore can lead to errors.

Will close for now. Feel free to ask further questions regarding this topic here. We can re-open if required.
