### ISSUE TITLE
Cannot add custom selector

### ISSUE THREAD

**Issue by M3ssman** [jquery-validation/jquery-validation#2219]
### Subject of the issue
Can one enable custom selectors? The Docs mention three additions : ":blank", ":filled" and ":unchecked", but what if others are required? I need to check if a selected value is not empty, but is not a specific default Value coming from the backend. Therefore, setting the value = "" (like the Docs suggest https://jqueryvalidation.org/required-method/ ) is not an option.

### Your environment
* jquery-validate 1.18.0

### Steps to reproduce
```
<!-- form -->
<form class="form" id="aForm" method="get" action="">
    <select id="s1" name="s1" class="form-control" size="1" 
       data-msg-required="Selection missing!">
         <option value="000">Please choose</option>
         <option value="001">apples</option>
         <option value="002">pies</option>
     </select>
     <p><input class="submit" type="submit" value="Submit"></p>
</form>

<script>
  // extend jQuery
        $.extend( $.expr.pseudos || $.expr[ ":" ], {
            unselected000: function(a) {
                let val = $(a).val();
                return "000" === val;
            }
        });

 let options = { rules: {
                    s1: {
                        required: "select#Stg1:unselected000",
                    }
                   ...
                   }
$("#aForm").validate(options);
</script>
```

JQuery Selector itself works as expected:
https://jsfiddle.net/M3ssman/xpvt214o/851013/

but, unfortunately , I don't get it along with the jquery-validator 

### Expected behaviour
Signal missing Selection.

### Actual behaviour
Custom selector is not applied. Somewhere down in jquery-validation it get swallowed inside `prototype.depend`. Looks like it ain't used at this point.

**Comment by Arkni** [comment]
Thanks a lot for filling this issue! We'll triage and take a look at it as soon as possible!

**Comment by sunny-shu** [comment]
The latest version has been able to make it.
When you configure “required”, you have three ways：
1.boolean
for example,required:true;it means the input element is required,You should enter something。
2.string
for example,required: "#other:checked";it means if this element exists($("#other:checked").length >0), the input element is required.
3.function 
for example ,
required: function(element) {
        return $("#age").val() < 13;
      }
it means whether it is required depends on the return value of this function。

as for your question,i think you can use method 3.
