### ISSUE TITLE
WYSIWYG plugins causes "TypeError: string is undefined"

### ISSUE THREAD

**Issue by SceLPI** [jquery-validation/jquery-validation#2229]
### Subject of the issue
WYSIWYG plugins causes "TypeError: string is undefined"

### Your environment
* version of `jquery-validate`: 1.18.0
* which browser and its version: Chrome 70.0.3538.67 x64 and Firefox 62.0.3 x64

### Steps to reproduce
Using WYSIWYG (tested with Gijgo and TinyMCE) type anything on text field.
Click outside.

### Expected behaviour
Just no Errors

### Actual behaviour
Logging Error: TypeError: string is undefined
Line 1023

### Fix suggestion
Just force variable string to be string everytime on line 1023:
Replace:
> 1023 `return string.replace..`
To:
> 1023 `return (string+"").replace..`

**Comment by mateusz-michalik** [comment]
I can reproduce this issue exactly as per @SceLPI's issue with jQuery Validation Plugin v1.17.0 and Summernote WYSIWYG v0.8.10 on Firefox 64.0.2 on OSX.

Error: TypeError: string is undefined
Line: 1032

**Comment by ilyas-oirraq** [comment]
thank you man!

**Comment by KoalaBear84** [comment]
Another PR just got merged which is like the other PR.

#2154
