### ISSUE TITLE
jQuery Migrate 3.0.1 - outdated focus() event shorthand is deprecated

### ISSUE THREAD

**Issue by sassquad** [jquery-validation/jquery-validation#2238]
While using v1.18.0 of the jQuery Validation plugin, alongside jQuery Migrate 3.0.1, I got a console warning concerning the following line using deprecated markup:

https://github.com/jquery-validation/jquery-validation/blob/dd187b016a1b4eef22ae93500eb37a44bf2ecd0d/src/core.js#L605

Looking through the rest of the code, the up to date on()/off()/trigger() event handlers are used, so it's entirely possible this is the only instance of the code which is deprecated?

It only needs changing from:

`focus()`

to

`trigger('focus')`

The Migrate plugin doesn't appear to complain about anything else, but would be grateful if anyone can confirm this?

Many thanks

Stephen Scott

**Comment by staabm** [comment]
Thx for the report. I guess this is an oversight on our end. 

Are you willing to provide a PR to fix the warning?

Thx

**Comment by sassquad** [comment]
@staabm - I can certainly have a go.

**Comment by Arkni** [comment]
Fixed by #2243
