### ISSUE TITLE
[DOCS] Update website home page

### ISSUE THREAD

**Issue by Arkni** [jquery-validation/jquery-validation#2240]
### Subject of the issue

The website needs update. We should update the home page to point out that we have a new release.

### Your environment
* version of `jquery-validate`: n/a
* which browser and its version: n/a

### Expected behaviour

Should have the latest version 1.18.0

### Actual behaviour

It still shows the version 1.17.0

**Comment by staabm** [comment]
We should tag 1.18.1 for the recent regression and move ahead

**Comment by Arkni** [comment]
It should not be a patch, but rather a minor bump as we also have some new validation rules added.

**Comment by staabm** [comment]
ok cool. we should it get out of the door quickly though.

anything open which should be part of 1.19 as well?

**Comment by Arkni** [comment]
Nothing for now. We are good to go.

As for the changelog, you can find it here: https://gist.github.com/Arkni/fc52dc8e4f5ca1ccc7ea1198b0b659a3#file-jquery-validation-changelog-1-19-0-md

Thanks and sorry for any inconvenience from my part!

**Comment by staabm** [comment]
no worries, you are doing a great job. thank you!

**Comment by staabm** [comment]
thx for the changelog - here we go https://github.com/jquery-validation/jquery-validation/releases/tag/1.19.0

**Comment by staabm** [comment]
@Arkni do you have an npm account? I would love to give you the permissions one need to do releases - just in case I dont have time to.

**Comment by staabm** [comment]
website updated to 1.19.0.

the cdn provides will catch up soon.
I also informed my microsoft contact to update the ms-cdn

**Comment by Arkni** [comment]
Yay!

Thanks a lot @staabm :)

Yes I do have an account on npm. My handle is @arkni on there too (https://www.npmjs.com/~arkni).
