### ISSUE TITLE
Crowdin contributor's version of Serbian (Latin) translation of PrestaShopop V1.5.0 and the one displayed on GitHub are extremely different 

### ISSUE THREAD

**Issue by Zoran23** [jquery-validation/jquery-validation#2244]
To Whom It May Concern  

### PrestaShop language Serbian latin on Crowdin and GitHub dev don't use the same variant

My name is Zoran and I took a project to translate PrestaShopop V1.5.0 on Serbian Latin language. 
Language In prestaShop has a Language code: sr-cs and ISO code : sr 
Serbian has two type of languages. 
1. Serbian cirilic 
2. Serbian Latin
On crowdin website there is only one type and this is Serbian (Latin) translation. 
This Latin is more popular and I am happy that this one is there.  This language is already translated 62 % and rest of it will come soon. Problem is that someone who started this translation translated one minor part in Cyrillic. 
I have found these several wrong translated words and have changed them to correct ones.  Unfortunate everything that I corrected never came with new prestaShop installation. Even some new words that I have translated never showed up on new PrestaShop 1.5.0beta version
I asked prestashop developers for help and this is what they told me: “
“Wen I make the comparison between the Crowdin contributor's version and the one displayed on GitHub, it is extremely different. In fact, I think that there are two variants of this language, Serbian. It seems that the Crowdin contributor and the GitHub dev don't use the same variant.
So I think the Crowdin contributor needs to do a pull request himself because he will probably have to talk to the guys from jquery-validate about that.
Perhaps it will be needed not to MODIFY this file but to ADD a file in order to have the two Serbian translations available (even if there are two variants of this language). In short, I think he needs to check with the concerned and then more skilled people about this topic.
I see two solutions:
- the easy solution is to open an issue > https://github.com/jquery-validation/jquery-validation/issues/new
- he is motivated and creates a pull request if he knows how to do it, but I don't know when the plugin will be updated
And then, we at PrestaShop will have to download this plugin new version and use it to get the "right translation" within the next version of the software.

Please help me to get this great program on Serbian latin language.
Kind regards 
Zoran

### Your environment
* version of `jquery-validate`:
* which browser and its version:

**Comment by Arkni** [comment]
Hi @Zoran23,

I would like to help but I don't understand the issue very well. What is the variant used by PrestaShop and how it is deffirent from the one we have in this plugin?

Also, if you would like to contribute the changes, we welcome your contribution and I would be happy to walk you through the steps.

Thanks :)

**Comment by matks** [comment]
Hi,

If I can help, I am a PrestaShop developer and I had a look at this issue 😄 

Current translation file for Serbian is https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_sr.js

@Zoran23 suggested to modify this and replace it with this instead:
```
/*
 * Translated default messages for the jQuery validation plugin.
 * Locale: SR (Serbian; Srpski jezik)
 */
(function ($) {
	$.extend($.validator.messages, {
		required: "Polje je obavezno.",
		remote: "Sredite ovo polje.",
		email: "Unesite ispravnu E-mail adresu",
		url: "Unesite ispravan URL.",
		date: "Unesite ispravan datum.",
		dateISO: "Unesite ispravna datum (ISO).",
		number: "Unesite ispravan broj.",
		digits: "Unesite samo brojeve.",
		creditcard: "Unesite ispravan borj kreditne kartice.",
		equalTo: "Unesite istu vrednost ponovo.",
		accept: "Unesite vrednost sa odgovarajućom ekstenzijom.",
		maxlength: $.validator.format("Maksimalan broj znakova je {0} ."),
		minlength: $.validator.format("Minimalan broj znakova je {0} ."),
		rangelength: $.validator.format("Unesite vrednost izmedju {0} i {1} znakova."),
		range: $.validator.format("Unesite vrednost izmedju {0} i {1}."),
		max: $.validator.format("Unesite vrednost manju ili jednaku {0}."),
		min: $.validator.format("Unesite vrednost veću ili jednaku {0}.")
	});
}(jQuery));
```

As you can see it is very different, and the reason why is there are 2 variants of Serbian: cirilic and latin.
Is there a way to provide users the capability to choose which variant they want ?

**Comment by Arkni** [comment]
Hi @matks,

I got the gist of the issue now, thanks a lot for the explanation.

There is something I didn't check last time and I totally forgot about it. In fact, we have two files for Serbian language, one in cirlic which is the file you refered in your comment, and one in latin named [`messages_sr_lat.js`](https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_sr_lat.js). So, as far as I can tell, you want to use the latin version as the default one.

If we did the change, that will be considered a breaking change and we will have to postpone it untill we have an ETA for version `2.0.0`.

What do you think?

**Comment by Zoran23** [comment]
I gave up from this, and i translated presta shop 1.7.5 manually file by file on my computer (I used Latin 100%).  Adding currency in prestashop 1.7.5 with serbian language did not work because of some problem with locale. 1.7.5. Serbian was massy and I was just waiting for new version.

Now when prestashop 17.6 beta is up, I have tested it and translated online everything 100%. (Only Latin)

Now in 1.7.6 currency is working fine but new big problem came. It is not possible to translate Serbian language in BO. Error that is coming is following: The provided locale `sr-CS` is invalid.
Yes I have translated it 100% online, but still maybe someone want to change something through back office. 
If someone can check up why this error, “The provided locale `sr-CS` is invalid”, coming up when try to translate Serbian language on BO. 

Thanks in advance. 
Zoran

**Comment by seedsgallery** [comment]
Zorane how did you translate? I have a problem with 1.7.6 and can not translate custom theme because of this issue. 

Prestashop should be ashamed because they haven't fixed the mistake yet !!!

Pozdrav Igor

**Comment by Zoran23** [comment]
Pozdrav Igore. 
Lokale ne treba da bude sr-cs nego sr-rs. To treba zameniti na nekoliko mesta. Sad sam trenutno na odmoru na Mauricijusu pa ne mogu da ti opisujem gde sve treba izmeniti. Ako me potsetis sledece sedmice poslacu ti kompletnu instrukciju. Podseti me na mejl zorantejic@ hotmail.com
