### ISSUE TITLE
Email validation of blank not required input

### ISSUE THREAD

**Issue by jadamec** [jquery-validation/jquery-validation#2250]
### Your environment
* version of `jquery-validate`: 1.19.0
* which browser and its version: Google Chrome (latest in 19.12.2018)

### Expected behaviour

In case of blank `<input type="email" name="email">` I want to disable validation. It's not required, so I need a validation only in case of filling this input. Thanks.

### Actual behaviour

Even I haven't email input as required, it shows me an error of wrong email format in case of blank input.

HTML part:
```
<input class="form-control m-input" type="email" placeholder="Zadajte emailovú adresu" name="email" autocomplete="off">
```
JS part:
```
var handleNewPostSubmit = function() {
  $('#m_post_submit').click(function(e) {
    e.preventDefault();
    var btn = $(this);
    var form = $(this).closest('form');
    form.validate({
      rules: {
        email: {
          email: true
        }
      }
    });

    if (!form.valid()) {
      return;
    }
    console.log('preslo');
    btn.addClass('m-loader m-loader--right m-loader--light').attr('disabled', true);

    form.ajaxSubmit({
      type: 'post',
      url: form.attr('action'),
      data: form.serialize(),
      success: function() {
        btn.removeClass('m-loader m-loader--right m-loader--light').attr('disabled', false);
        location.reload();
      }
    });
  });
}
```

**Comment by jadamec** [comment]
Oh well, problem was in the main settings of used site template [Metronic][1]. There's a `validator.addMethod` for `type="email"` by default and looks like this. After removing it works correctly!

**/theme/default/src/js/framework/components/plugins/forms/jquery-validation.init.js**

    jQuery.validator.addMethod("email", function(value, element) {
        if (/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(value)) {
            return true;
        } else {
            return false;
        }
    }, "Please enter a valid Email.");


  [1]: https://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469

**Comment by Arkni** [comment]
Thanks a lot for your confirmation :)

I'm going to close this for now, but please feel free to ask if you have folloup questions.

Thanks!

**Comment by Vizz85** [comment]
I have the same issue and think removing the email method itself is not the solution...

I tried with `data-rule-email="false"` but it doesn't work, the rule is always set to `true`.
Is someone facing the same issue?
