### ISSUE TITLE
file validation causes no validation at all on any other field

### ISSUE THREAD

**Issue by dnsBlah** [jquery-validation/jquery-validation#2252]
### Subject of the issue
Unable to validate file

### Your environment
* version of `jquery-validate`: v1.19.0 minimized
* which browser and its version: FireFox 64.0, Safari 12.0.2

### Steps to reproduce
add a extension: "png|jp?eg|gif" to an file input

### Expected behaviour
Validating the file extension

### Actual behaviour
Other validations are not being processed, (even if ALL fields are empty) and submits form with default behaviour (even though I have $('#myform').on('submit', function(e) { e.preventDefault(); });

The complete script gets killed. I don't see an error in console.

Will do a quick test on the not-minified version tonight.

**Comment by Arkni** [comment]
Hi @dnsBlah,

Please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a reproducible example and I will look at it as soon as I got some free time.

Thanks!
