### ISSUE TITLE
Additional: Machine Readable Travel Documents

### ISSUE THREAD

**Issue by RobJohnston** [jquery-validation/jquery-validation#2253]
I'm wondering if there is any interest to include validation for [Machine Readable Travel Documents](https://www.icao.int/publications/pages/publication.aspx?docnum=9303), such as passports and visas, as published by [ICAO](https://www.icao.int).

I have a Gist available with the code and unit tests already in it here:  https://gist.github.com/RobJohnston/60b49b0303f6557cfc0789a426b2155a

I haven't included it as a pull request because we are not using this method in production, but I think it may be of interest to others.  Thoughts?

**Comment by Arkni** [comment]
Hi @RobJohnston,

Thanks a lot for opening this issue and sorry about the lack of response from us.

That's a good idea and I'm +1 to adding it to the plugin. Please feel free to create a pull request and I will review it as soon as I got some free time.

Thanks a lot for your suggestion and for working on this, I really appreciate it :)
