### ISSUE TITLE
Update NuGet to version 1.19.0

### ISSUE THREAD

**Issue by ddelella** [jquery-validation/jquery-validation#2254]
It looks like this project is not responsible for maintaining the version in NuGet however it lists it as a download source on the homepage.  Current version is showing 1.17.0 in NuGet but the website shows 1.19.0.  Can someone please update NuGet?

**Comment by RobJohnston** [comment]
Are you referring to the package found at  https://www.nuget.org/packages/jQuery.Validation/?  I'd try the "Contact owners" link.  Seems to be somebody with the handle "outercurve".

**Comment by staabm** [comment]
thx for raising this issue.

this package is not managed by us. please contact the package owner as @RobJohnston suggested.

**Comment by jerone** [comment]
Did anyone contacted them and got an response?

Just in case, I contacted them also
> Please update NuGet to the latest version 1.19.0. 
> See https://github.com/jquery-validation/jquery-validation/issues/2254
