### ISSUE TITLE
Incorrect Email validation 

### ISSUE THREAD

**Issue by ketan32** [jquery-validation/jquery-validation#2270]
### Your environment
* version of `jquery-validate`: 1.16.0
* which browser and its version: Google Chrome Version 73.0.3683.86 (Official Build) (32-bit)

### Steps to reproduce

- Go to this demo URL: https://jqueryvalidation.org/files/demo/
- Type "john@gmail" as value of email field.
- Now tab to next field or click on submit
- Validate js is not considering it as incorrect email

### Expected behaviour

- It should throw message that its invalid email

### Actual behaviour

- Its considering the entered value as valid email

**Comment by staabm** [comment]
See the README.md for details.

> **IMPORTANT NOTE ABOUT EMAIL VALIDATION**. As of version 1.12.0 this plugin is using the same regular expression that the [HTML5 specification suggests for browsers to use](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider [using a custom method](http://jqueryvalidation.org/jQuery.validator.addMethod/).
In case you need to adjust the built-in validation regular expression patterns, please [follow the documentation](http://jqueryvalidation.org/jQuery.validator.methods/).
