### ISSUE TITLE
Custom Validation message not being returned

### ISSUE THREAD

**Issue by terzo-genito** [jquery-validation/jquery-validation#2274]
jquery-validate ver: 1.19.0
Browser: Latest Chrome

I have the following custom validation method:
`$.validator.addMethod('switchRequire', function(value, element) {`
`  if ($('#' + element.id + 'Check').bootstrapSwitch('state')){`
 `   if((parseInt(value)) > 0){`
 `     return true;`
 `   }`
 `   else {`
 `     return false;`
 `   }`
 ` }`
 ` else {`
 `   return true;`
 ` }`
`}, 'ErrorMsg');`

The method works but returns "0" as the error message, which is the value, not the error.

Calling method from .validate:

`fieldName: {
  switchRequire: true
}`

**Comment by TamaKun89** [comment]
I struggled with the custom method and message myself until I realized that i had the title attribute of my input fields set and it showed that instead of the message, maybe this helps?
