### ISSUE TITLE
less than -6 step in number input works wrong

### ISSUE THREAD

**Issue by JoungPark** [jquery-validation/jquery-validation#2276]
### Subject of the issue
less than -6 step in number input works wrong

### Your environment
* version of `jquery-validate`: 1.19.0
* which browser and its version: Chrome Version 74.0.3729.157 (Official Build) (64-bit)

### Steps to reproduce
1. html: `<input type="number" step="0.0000001">`
1. javascript: `$("#commentForm").validate();`

### Expected behaviour
1. It should pass if number value is 1.2345678 (decimal places: -7)
1. It should fail if number value is 1.23456789 (decimal places: -8)

### Actual behaviour
1. It failed when number value is 1.2345678 and its message is `Please enter a multiple of 1e-7.`
1. It failed when number value is 1.23456789 and its message is `Please enter a multiple of 1e-7.`
1. Every number value cannot be valid.

**Comment by JoungPark** [comment]
So we change the step to 'any' rather than exact number and check it manually.

**Comment by amigian74** [comment]
Hi

When will this be fixed, because it's still not working with version 1.19.3?
