### ISSUE TITLE
**messages_ar.js**  file Suggested update for Arabic vocab 

### ISSUE THREAD

**Issue by tamerkamal** [jquery-validation/jquery-validation#2292]
### **messages_ar.js** file Suggested update for Arabic vocab to be more relevant to Arabic native expressions:
        required: "هذه الخانة إلزامية"
        remote: "يرجى تصحيح القيمة المدخلة للمتابعة"      
        equalTo: "رجاء تكرار القيمة المدخلة سابقا"
        extension: "رجاء إدخال ملف من نوع مناسب"
![image of file after updating arabic vocab](https://user-images.githubusercontent.com/25005540/62694955-9e81f380-b9d5-11e9-8f2c-0a0a77b2cc34.png)

**Comment by Arkni** [comment]
Hi @tamerkamal,

Thanks a lot for filing this issue! Would you like to write a patch for this?
