### ISSUE TITLE
Nothing to repeat error at additional method

### ISSUE THREAD

**Issue by jadeja-rajdeep** [jquery-validation/jquery-validation#2293]
### Subject of the issue
Getting Nothing to repeat error at additional method file line no - 103

### Your environment
v1.19.1
firefox 69.0b11 (64-bit)

### Steps to reproduce
1) in input file i added accept tag like this
accept="*.jpg,*.jpeg,*.png,image/jpg,image/jpeg,image/png"

2) when validation is occured its give error

3) if i remove "*.jpg,*.jpeg,*.png," from accept tag its work fine

**Comment by Arkni** [comment]
Hi @jadeja-rajdeep,

Thanks a lot for filling this issue! I'll triage and take a look at it as soon as possible!

Can't promise I can look at it anytime soon, but if you have some time, could you please debug it and see if you can find anything that will help us fix the issue?

**Comment by sunny-shu** [comment]
This is not a problem, it's just about how to specify the file type.
i read the code,you should use 'image/jpg,image/jpeg,image/png',Other content will not work。
Maybe You can make some comments on the format of the parameter and Let's see what the author thinks 。
