### ISSUE TITLE
additional-methods.min.js is missing when using npm i jquery-validation

### ISSUE THREAD

**Issue by jjkayani** [jquery-validation/jquery-validation#2295]
additional-methods.min.js is missing when using npm i jquery-validation

I have downloaded the jquery-validation from npm and inside my code I am using min version of both validation and additional methods, but the additional-methods.min is not there when I checked inside the folder.

Angular
* version of 1.17.0:
chrome

![image](https://user-images.githubusercontent.com/25216840/63771056-79ebae00-c8e7-11e9-9a20-84efb628d068.png)

**Comment by Arkni** [comment]
Hi @jjkayani,

The issue you described has been fixed in #2057 and was released as of 1.18.0.

See changelog for more information: https://github.com/jquery-validation/jquery-validation/blob/master/changelog.md#1180--2018-09-09
