### ISSUE TITLE
How to add more classes to error element?

### ISSUE THREAD

**Issue by dpDesignz** [jquery-validation/jquery-validation#2296]
### Subject of the issue
I'm wanting to style my error element more, but I would like to target it with a second class. Is this at all possible, and if so, how please?

### Your environment
* version of `jquery-validate`: 1.19.1
* which browser and its version: Firefox Developer Edition 69.0b16 (64-bit)

### Steps to reproduce
I currently have my code as follows

```javascript
jQuery.validator.setDefaults({
  focusCleanup: true,
  errorClass: "invalid",
  errorElement: "span",
  highlight: function ( element, errorClass, validClass ) {
    $( element ).next( "span" ).addClass( "csc-helper-text" );
  }
});
```

### Expected behaviour/Actual behaviour
The issue is that it doesn't actually apply the class right away, only once the field loses focus. The other issue I have is for some reason now the errorClass isn't being applied to the input, it just stays as valid for some reason.

**Comment by Arkni** [comment]
Hi @dpDesignz,

When you override `highlight` method, it will on you to add the error class and remove the valid class inside the new implementation.

It's normal that the class will only be applied if the element was validated (by default after losing focus and then once the element was validated it will be on keydown).

For inspiration on how to add more classes or adding more styling, see this example for integrating this plugin with Bootstrap: https://github.com/jquery-validation/jquery-validation/blob/25a0f146dc860e8de69d16cd95d0f5987f86e51c/demo/bootstrap/index.html#L221-L226 and https://github.com/jquery-validation/jquery-validation/blob/25a0f146dc860e8de69d16cd95d0f5987f86e51c/demo/bootstrap/index.html#L297-L304

Demo: https://jqueryvalidation.org/files/demo/bootstrap/index.html
Source code: https://github.com/jquery-validation/jquery-validation/blob/master/demo/bootstrap/index.html

**Comment by dpDesignz** [comment]
@Arkni thank you very much. This has fixed the valid/invalid issue. 😄 

My code is now as follows:

```javascript
// Set default jQuery validator settings
jQuery.validator.setDefaults({
  errorClass: "invalid",
  errorElement: "span",
  highlight: function ( element, errorClass, validClass ) {
    $( element ).addClass( errorClass ).removeClass( validClass );
    $( element ).next( "span" ).addClass( "csc-helper-text" );
  },
  unhighlight: function ( element, errorClass, validClass ) {
    $( element ).addClass( validClass ).removeClass( errorClass );
    $( element ).next( "span" ).addClass( "csc-helper-text" );
  }
});
```

However, my code still isn't adding the class `csc-helper-text` as soon as it triggers for some reason? The error message displays, but I have to click out of the field and then back into it for it to apply the class. Any ideas why this might be?

**Comment by Arkni** [comment]
Now I understand the second part of your question. The `highlight/unhighlight` are not the best solution for adding custom classes to error elements. You have to use [`errorPlacement`](https://jqueryvalidation.org/validate/#errorplacement) setting:

```js
errorPlacement: function ( error, element ) {
	// Add the `csc-helper-text` class to the error element
	error.addClass( "csc-helper-text" );
	if ( element.prop( "type" ) === "checkbox" ) {
		error.insertAfter( element.parent( "label" ) );
	} else {
		error.insertAfter( element );
	}
},
```

This will add your custom class before the plugin append it to your form.

Now that the overrided `highlight/unhighlight` settings are only used to do the default behaviour, you can remove them and let the plugin add/remove the valid/invalid class.

**Comment by dpDesignz** [comment]
@Arkni sorry, I wasn't sure how to explain it. Thanks for you help.

Ok I've updated my code as follows:

```javascript
// Set default jQuery validator settings
jQuery.validator.setDefaults({
  errorClass: "invalid",
  errorElement: "span",
  errorPlacement: function ( error, element ) {
    // Add the `csc-helper-text` class to the error element
    error.addClass( "csc-helper-text" );
    if ( element.prop( "type" ) === "checkbox" ) {
      error.insertAfter( element.parent( "label" ) );
    } else {
      error.insertAfter( element );
    }
  }
});
```

But my console log is giving me an error that it's broken, but isn't saying how. Can you what I may have done wrong here?

**Comment by Arkni** [comment]
The code looks good to me and I have no idea what can go wrong. Could you please share the error? and if possible, please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/).

**Comment by dpDesignz** [comment]
> 
> 
> The code looks good to me and I have no idea what can go wrong. Could you please share the error? and if possible, please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/).

Bizzare, removed the code and re-added it, did a refresh with CTRL+F5 and it's now working.
It's been a long day of coding, my browser musn't have loaded the new code properly. Thanks for all your help! Much appreciated. 😄

**Comment by Arkni** [comment]
It happens sometimes :)

I'm going to close this issue. Feel free to ask if you have followup questions!
