### ISSUE TITLE
Debug built-in Validation handler

### ISSUE THREAD

**Issue by Legends** [jquery-validation/jquery-validation#2305]
I am doing attribute validation using ASP.NET MVC (incl. jquery unobstrusive).

` [Range(typeof(bool), "true", "true", ErrorMessage = "You must accept the Terms")]
        public bool TermsAccepted { get; set; }`

The thing is it will not submit the form while the checkbox above is checked.
If I uncheck it the form gets submitted.

**Question:**
Where can I see the validation function to see what is going wrong, means: How to debug this?

**Comment by sunny-shu** [comment]
google how to debugger js in chrome.
by the way, you sholud build the project and repalce source file in html with it.
because the source code published on internet is uglified  and is not convenient for debugging
