### ISSUE TITLE
Alpha and Alphanumeric Only

### ISSUE THREAD

**Issue by a2zwebtech** [jquery-validation/jquery-validation#2318]
Hi!
I am looking for Allow only character like A-Z in my First Name field and in one filed I want only A-Z and 0-9. I am not able to find any demo for same, Let me know if someone can help me for do it.
I am using this demo
https://jqueryvalidation.org/files/demo/bootstrap/index.html
Thanks!

**Comment by RobJohnston** [comment]
I think that you are looking for these two validation methods:
* [lettersonly](https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/lettersonly.js)
* [alphanumeric](https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/alphanumeric.js)
