### ISSUE TITLE
Wrong Email validation detected!!!

### ISSUE THREAD

**Issue by jodyshop** [jquery-validation/jquery-validation#2321]
### Subject of the issue
The validation only checks for `user@example` - and it should check for a complete email address like `user@example.com`.

### Your environment
* version of `jquery-validate`: v1.15.1
* which browser and its version: Firefox

### Steps to reproduce

When trying to validate the entered email address the validation plugin only checks for user@example - and this is wrong, the validation should check for a complete email address like user@example.com.

### Expected behavior
I have edited the `jquery.validate.min.js` as follow:
- Search for **email:function** and replace the code as shown below:

From:
`/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test(a)}`

### Actual behaviour

To:
`/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)***(\.[A-z]{2,4})**$/.test(a)}`

**Comment by staabm** [comment]
thank you for taking the time to report a issue.

Unfortunately this topic was discussed already before. See the README.md for details:

> **IMPORTANT NOTE ABOUT EMAIL VALIDATION**. As of version 1.12.0 this plugin is using the same regular expression that the [HTML5 specification suggests for browsers to use](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider [using a custom method](http://jqueryvalidation.org/jQuery.validator.addMethod/).
In case you need to adjust the built-in validation regular expression patterns, please [follow the documentation](http://jqueryvalidation.org/jQuery.validator.methods/).
