### ISSUE TITLE
jquery.validate.unobtrusive uses the parseJSON() method, which is deprecated in jQuery 3.0

### ISSUE THREAD

**Issue by dav1dc-cam** [jquery-validation/jquery-validation#2322]
### Subject of the issue
Calls to deprecated jQuery.parseJSON() method

### Your environment
jquery-validate version 1.19.1
jquery version 3.4.1
jquery-migrate version 3.0.0
Chrome version 80.0.3987.149

### Steps to reproduce
Call either the onSuccess or onError methods of jquery.validate.unobtrusive.

### Expected behaviour
No errors/warning reported by the jQuery migration tool

### Actual behaviour
The jQuery Migration tool reports that parseJSON() has been deprecated and advises that the native JSON.parse() method should now be used.

**Comment by bytestream** [comment]
This should be resolved in the latest release.
