### ISSUE TITLE
Error in not validating array's of inputs correctly.

### ISSUE THREAD

**Issue by thejoker-dev** [jquery-validation/jquery-validation#2326]
### Subject of the issue
The error occurs in the instance of validating a form with array's of equal inputs, it only validates the first element found within the form.

### Your environment
* version of `jquery-validate`: 1.19.1
* version of `jquery`: 3.4.1
* which browser and its version: Google Chrome v81.0.4044.122 (Build oficial) (64 bits)

### Steps to reproduce
http://jsfiddle.net/thejoker_dev/p6zs51v8/

### Expected behaviour
It should validate all types of inputs, including those that are arrays of themselves.

### Actual behaviour
Validates only the first input of the array with the same name, leaving the rest unvalidated.

Attached jquery-validate.js file modified on line 465 (checkForm function) which I leave below and it works without problems!

`checkForm: function() {
		    this.prepareForm();
		    for ( var i = 0, elements = (this.currentElements = this.elements()); elements[i]; i++ ) {
		        var checkingElements = this.findByName( elements[i].name ).not(this.settings.ignore);
		        if (checkingElements.length !== undefined && checkingElements.length > 1) {
		            for (var cnt = 0; cnt < checkingElements.length; cnt++) {
		                this.check( checkingElements[cnt] );
		            }
		        } else {
		            this.check( elements[i] );
		        }
		    }
		    return this.valid();
		}`

Attached jquery-validate.js file modified on line 465 (checkForm function) which I leave below and it works without problems!

[jquery.validate.zip](https://github.com/jquery-validation/jquery-validation/files/4553991/jquery.validate.zip)

**Comment by bytestream** [comment]
The is a long standing issue and linked to many in the past - https://github.com/jquery-validation/jquery-validation/issues/2046 https://github.com/jquery-validation/jquery-validation/issues/2102 https://github.com/jquery-validation/jquery-validation/issues/1226

Linked PR https://github.com/jquery-validation/jquery-validation/pull/2000

**Comment by Aaadi** [comment]
JqueryValidation filtering same name elements under rules cache, I just comment the rulesCache. It works for me.
https://stackoverflow.com/a/69452906/1939258

**Comment by shibin-pb** [comment]
How to add remote method validation to array of inputs using class name
`

> input type="text" id="ApplyAuthTCSCDT1" name="ApplyAuthTCSCDT[1]" class="form-control scdDateTime formPadding scdDataDT" required=""
> input type="text" id="ApplyAuthTCSCDT2" name="ApplyAuthTCSCDT[2]" class="form-control scdDateTime formPadding scdDataDT" required=""
> 
> input type="text" id="ApplyConfirmpnSCTCDT1" name="ApplyConfirmpnSCTCDT[1]" class="form-control scdDateTime formPadding scdDataDT" required=""
> input type="text" id="ApplyConfirmpnSCTCDT2" name="ApplyConfirmpnSCTCDT[2]" class="form-control scdDateTime formPadding scdDataDT" required=""
> 
> input type="text" id="RemoveAuthTCSCDT1" name="RemoveAuthTCSCDT[1]" class="form-control scdDateTime formPadding scdDataDT" required=""
> input type="text" id="RemoveAuthTCSCDT2" name="RemoveAuthTCSCDT[2]" class="form-control scdDateTime formPadding scdDataDT" required=""

`

Have tried to use the following jquery validation rule function but getting error **Uncaught TypeError: e.nodeName is undefined.  Exception occurred when checking element ApplyConfirmpnSCTCDT1, check the 'remote' method.** . 

The following are the jquery code.

`

> $(".scdDataDT").each(function() {  
>                             $(this).rules('add', {
>                                 required: true,
>                                 remote: {
>                                     url: "url.php",
>                                     type: "POST",
>                                     async: false,
>                                     data: {  
>                                       scdDT: function() {
>                                         console.log($(this).val()) ;  
>                                         //return $( "#"+$(this).attr("id")).val();
>                                       },  
>                                       pbId: function() {
>                                         return $( "#SCDApplyRemovePBId" ).val();
>                                       },
>                                       pbNo: function() {
>                                         return $( "#SCDApplyRemovePBNo" ).val();
>                                       }
>                                     }
>                                   },
>                                 messages: {
>                                     required: "*",
>                                     remote:"#"
>                                 }
>                             });
>                         });`
