### ISSUE TITLE
$.trim deprecated in jQuery 3.5.0

### ISSUE THREAD

**Issue by mmw** [jquery-validation/jquery-validation#2327]
# Subject of the issue
jQuery 3.5.0 has depreacted `$.trim` and should use `String.prototype.trim` instead

### Your environment
* version of `jquery-validate`: 1.19.1
* which browser and its version: N/A

### Steps to reproduce
See [jQuery 3.5.0 release notes](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/)

**Comment by gurpreetKaur-UI** [comment]
Adding below polyfill will fix the issue:(as per jquery documentation)
Running the following code before any other code will create trim() if it's not natively available.

if (!String.prototype.trim) {
  String.prototype.trim = function () {
    return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g, '');
  };
}
