### ISSUE TITLE
why add "novalidate" to the form?

### ISSUE THREAD

**Issue by alex-jitbit** [jquery-validation/jquery-validation#2333]
I would like to combine jquery.validation with HTML5 validation (use HTML5 for basic stuff and jquery.validation for complex things like checking upload file sizes etc).

But jquery.validation has **silently** (!) added `novalidate` attibute to my form, I had to spend 20 minutes debugging why my `pattern` attributes have stopped working.

Please consider removing, otherwise this is obtrusive, non-obvious "easter-egg" behavior.

Thanks for considering.

**Comment by bytestream** [comment]
See https://github.com/jquery-validation/jquery-validation/pull/7 for context
