### ISSUE TITLE
Google Recaptcha v2

### ISSUE THREAD

**Issue by tuqqo** [jquery-validation/jquery-validation#2334]
hello! can anybody please help me how i can insert recaptcha v2 into this whole validation thing?
the code on the template i use looks like this:

> $(".form .btn[type='submit']").on("click", function(e){
>         var button = $(this);
>         var form = $(this).closest("form");
>         button.prepend("`<div class='status'></div>`");
>         form.validate({
>             submitHandler: function() {
>                 $.post("assets/php/email.php", form.serialize(),  function(response) {
>                     button.find(".status").append(response);
>                     form.addClass("submitted");
>                 });
>                 return false;
>             }
>         });
>     });

thanks in advance!

**Comment by RobJohnston** [comment]
Don't know if you saw these or if they help, but for reference:
* https://github.com/jquery-validation/jquery-validation/issues/1600
* https://github.com/jquery-validation/jquery-validation/issues/1980

**Comment by tuqqo** [comment]
hello. yes i saw those posts, but they did not help me.

**Comment by RobJohnston** [comment]
How about the example in the docs https://jqueryvalidation.org/documentation/#link-using-remote-validation-to-help-with-captchas. Does that get you further, or is it an outdated example?

Specifically, look at the `captcha.js` file in the source code of the page.

**Comment by tuqqo** [comment]
hey, that looks promising :-) 
thank you! 

i gonna mess with it later today and will share outcome.

**Comment by tuqqo** [comment]
ok, i figured out that i should seperate the recpatcha process from the validation process. 
having 1 php file for the recaptcha check and 1 for the validation and sendmail.
so i made it like this: hide the html send button until the capctha box is checked, in the button click function of the jquery validation process i added the seperate check for recaptcha before the validation/form submit.
and only if the recaptcha resonse is valid then continue with validation and form submit.
