### ISSUE TITLE
How can i use custom container for warnings??

### ISSUE THREAD

**Issue by ClaudioRowe** [jquery-validation/jquery-validation#2336]
### Subject of the issue
How can i use a custom markup where to deliver the warning?

### Your environment
Last version.
I'm on chrome.

### Expected behaviour
I would like to use a custom div to deliver the answers, or maybe if there is a css file where to get it.

### Actual behaviour
My container box expands and the warnings deform the style.

**Comment by bytestream** [comment]
Please check over https://jqueryvalidation.org/reference/ specifically for error message display.

**Comment by ClaudioRowe** [comment]
Thanks!

**Comment by staabm** [comment]
I will close the issue now. 

Feel free to ask further questions if there are any.
