### ISSUE TITLE
Documentation hosting? Site is unusable...

### ISSUE THREAD

**Issue by shieldsjared** [jquery-validation/jquery-validation#2339]
Been attempting to review documentation for this plugin since last week, and wherever its being hosted, the content hardly ever loads, and often just fails to load due to timeout...

Any chance anybody can look into this? Was hoping I could find the source for the docs here in the repository, but only seeing examples.  Thoughts?

Thanks all!

**Comment by staabm** [comment]
It seems to work for me ok.

Could you give more details steps to repro the issue and how it looks like?

**Comment by staabm** [comment]
In the meantime, you can have a look at the sources/content of the website at https://github.com/jquery-validation/validation-content

**Comment by shieldsjared** [comment]
@staabm On pretty much all of the various documentation links, I eventually land on a page like this, or my browser eventually gives up (or my patience do, hehe).  I've tested from various internet access methods, all with the same result.

![image](https://user-images.githubusercontent.com/600643/89226602-3646fd00-d5aa-11ea-8537-eaa80d0464f1.png)

**Comment by staabm** [comment]
@jzaefferer could you give the hoster a ping?

**Comment by shieldsjared** [comment]
> In the meantime, you can have a look at the sources/content of the website at https://github.com/jquery-validation/validation-content

Appreciate it! Not sure why I didn't even think to check for other repo's in the org, whoops!

**Comment by acguglielmo** [comment]
I'm facing another problem trying to check the documentation:

![image](https://user-images.githubusercontent.com/7442816/91178672-dd0b4e80-e6bb-11ea-8aa0-d1b911c505f3.png).

In the meantime I'm looking at the sources...

**Comment by shieldsjared** [comment]
I'm not sure what the traffic to the site is like... but if custom (costly) hosting is being used to host the docs via wordpress (and maintenance is an issue) - maybe a good solution would be to convert the documentation site into a github pages site? Its free and reliable?  I'm not sure if there are any dynamic features being used w/in the wordpress site (cant get to it to check) or if its just being used for static content hosting.  Just throwing out the idea...

**Comment by staabm** [comment]
I just found the contact data to the hoster again and wroten an email.

sorry for the inconvenience and problems resulting from that.

the contents itself somehow work together with a wordpress installation and its API.
I guess its a bit more then just "dump" markdown files.

I dont know all the details though.

**Comment by staabm** [comment]
it seems there was some blacklisting of cloudflare IPs going on, because of flooding protections.

should work again

**Comment by RobJohnston** [comment]
While we're on the subject, I had thought to send in pull requests for the web site in the past, but I could never get a local copy set-up correctly with WordPress.  I would support the move to a static site generator, whether hosted on github or elsewhere.

**Comment by staabm** [comment]
> While we're on the subject, I had thought to send in pull requests for the web site in the past, but I could never get a local copy set-up correctly with WordPress.

I never had a local Wordpress install running for it. It should work to make textual changes in the files without it.

the wordpress is mostly required to get it built for production deployment.



>  I would support the move to a static site generator, whether hosted on github or elsewhere.

I agree, that this would be a good step. if anyone is open to do the work, I would love it.
maybe even get the https://github.com/jquery-validation/validation-content repos's content running on github pages in parallel would work

**Comment by MelonCola** [comment]
I previously was able to access the website, but now I'm actually getting that same Error 522 timed out problem.
