### ISSUE TITLE
$('form').validate().settings; not working Using jquery -v3.5.1

### ISSUE THREAD

**Issue by Tandulje** [jquery-validation/jquery-validation#2341]
Hi...i'am using jquery -v3.5.1 and jquery.validate -v1.9.2

My code is 
**var settings = $('form').validate().settings;
settings.rules['UserPrincipalName'].required = true;**

it gives error
**VM155:294 Uncaught TypeError: Cannot set property 'required' of undefined**

When i was on older version jquey -v2.1.4 then it was working fine **_but now not working with jquey- v3.5.1_**

Please give some solution on it.
I go through lots of link but not getting related to this.
Please let me know how can i fix this issue.

_Originally posted by @Tandulje in https://github.com/jquery-validation/jquery-validation/pull/2328#issuecomment-673062441_

**Comment by sunny-shu** [comment]
When you create a validator, without passing any parameters, rules is an empty object('{}')。
so ‘settings.rules['UserPrincipalName'].required = true’ will get a exception。
you can  pass your custom parameters when create the validator。like this：
var settings = $('form').validate({
rules:{
    'UserPrincipalName':{
        'required':true
    }
}
)
