### ISSUE TITLE
Form inputs inside of a details are ignored if the details element is closed

### ISSUE THREAD

**Issue by MelonCola** [jquery-validation/jquery-validation#2342]
### Subject of the issue
Validating a form setup like Form > Details > Input ignores any Inputs inside of a closed Details element.

### Your environment
* version of `jquery-validate`: 1.19.2
* which browser and its version: Chrome 84

### Steps to reproduce
Place an input inside of a details element, inside of a form. Place an invalid input into the input, close the details element, and validate the form. https://jsfiddle.net/c7s8xo06/

### Expected behaviour
Any elements inside of the details should be evaluated as normal.

### Actual behaviour
All elements inside the details are completely ignored, and made "valid".
I'm unsure of if this is a feature or a bug, but in my opinion, it should be configurable which way it works.

**Comment by RobJohnston** [comment]
You could resolve this by simply adding `ignore: []`, as noted in https://github.com/jquery-validation/jquery-validation/issues/2358.

The closed details element must be setting the input as `hidden` (or disabled?), and that is ignored by default:  https://jqueryvalidation.org/validate/#ignore
