### ISSUE TITLE
Field with dynamic required is not unhighlighted correctly

### ISSUE THREAD

**Issue by pouki06** [jquery-validation/jquery-validation#2344]
### Subject of the issue

When I define a dynamic rule like below, the "unhighlight" is not called (on "email") if I set a value on the field "name", validate  
 then remove the value of the field "name" and validate again.

```
        rules: {
            "name": {
                required: true
            },
            "email": {
                required: function(){ return $("#name").val().length > 0 }
            }
        }
```

### Your environment
* version of `jquery-validate`: 1.17.0, but the issue is still there on the last version 1.19.2
* which browser and its version: Chrome Version 84.0.4147.135

### Steps to reproduce

Please open the fiddle : http://jsfiddle.net/pq6tycu4/

Insert a value in the first field "name" and click on Submit => The second field "email" should be invalid
Remove the value in the field "name" and click on Submit => The message on the second field "email" disappear, but the border stays until I focus it... It should disappearas well.

### Expected behaviour

The message and the border on the second field "email" should disappear.

### Actual behaviour

The message on the second field "email" disappear, but the border stays until I focus it...

**Comment by sunny-shu** [comment]
I can reproduce it, this is indeed a problem. I will try to figure it out。

**Comment by sunny-shu** [comment]
I found the problem, and there is a quick solution. But this method is not very elegant, this project did not consider the dependency problem, so this bug appeared. I see if this problem can be solved more elegantly

fast fix like this:
![截图](https://user-images.githubusercontent.com/55616357/97842999-848fa780-1d23-11eb-9786-cad687b5214d.PNG)

**Comment by sunny-shu** [comment]
i‘ve fix it. but my last PR is still not merged by the author. so i cannot push current pr to fix this issue.
@staabm  @Arkni 
Is this project still maintained?No one review my previous PR. and This PR is blocked。
