### ISSUE TITLE
Is it possible to add a validation method after document.ready has fired?

### ISSUE THREAD

**Issue by IanKemp** [jquery-validation/jquery-validation#2351]
I have a script that calls `$.validator.addMethod` after `document.ready` has been invoked. This plugin doesn't appear to pick up the method added in this way. Is there any way to get this to work? Is there some sort of "rebind" method I can call to force this plugin to wire itself up again after I've added my validation method?

**Comment by sunny-shu** [comment]
@IanKemp 
Can you upload a simple and reproducible code？that maybe help.
Did you turn on asynchronous loading, so your code was loaded earlier than the jquery-validation, and the registration failed。
