### ISSUE TITLE
Validation method bankaccountNL.js is outdated and incorrect.

### ISSUE THREAD

**Issue by StonehengeCreations** [jquery-validation/jquery-validation#2354]
The validation method bankaccountNL.js has not been updated since 2015-10-30. The available script validates for 11 digits. 
This is incorrect. 

Since 2014-08-01 (a year earlier) all Dutch bank accounts have 18 characters and are formatted as IBAN. 
- 2 Letter Country Code (Alpha-2)
- 2 Digit check number (varies, even at the same bank)
- 4 characters from the bank's SWIFT/BIC
- 10 digit code for the bank account number

Allowed formatting: NL91ABNA0417164300 or NL91 ABNA 0417 1643 00
The latter is the most commonly used. 

The file is located here: https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/bankaccountNL.js

Would someone please be so kind to either update the file to a valid validation method or remove it from the official release?

**Comment by sunny-shu** [comment]
you can use addMethod to override the the official method with same name.
i am happy to update the file,but i don't know the author's suggestion.

**Comment by RobJohnston** [comment]
@sunny-shu My suggestion would be to update the file with a deprecation notice that points to the IBAN validation here:
https://github.com/jquery-validation/jquery-validation/blob/master/src/additional/iban.js
