### ISSUE TITLE
Input with no name is validated

### ISSUE THREAD

**Issue by aperez987** [jquery-validation/jquery-validation#2361]
### Subject of the issue
An input with no `name` but with `required` attribute gets validated.
My actual issue is with the `maxlength` , but I can't reproduce it on jsfiddle.

### Your environment
jquery `3.5.1`
jquery.validate `1.19.2`

### Steps to reproduce

[https://jsfiddle.net/18j0rfpo/4/](https://jsfiddle.net/18j0rfpo/4/)

### Expected behavior
`email` input should not be validated.

### Actual behaviour
`email` input is validated.

As a workarround I added `ignore: ":not([name])"`.

**Comment by aijazbinqasim** [comment]
@aperez987 i am also experience same issue with asp.net MVC model's [Required] attribute.
