### ISSUE TITLE
Detect system/browser language

### ISSUE THREAD

**Issue by daviddebie** [jquery-validation/jquery-validation#2372]
### Subject of the issue
Not sure if it's an issue, change request or my own mistake, but I'm wondering if it's possible to use jQuery validation on a multilingual website. I have a form in both Dutch and English, and wish to present te validation messages in the proper language, depending on the OS or browser language that the user has setup. 
The CMS I'm using makes it impossible to load different scripts for a different language version of a page, hence the need to detect the preferred language in a different way.

**Comment by RobJohnston** [comment]
Does your CMS set the html "lang" attriubte as per https://www.w3.org/International/questions/qa-html-language-declarations?
E.g.
```html
<html lang="nl">
```

**Comment by daviddebie** [comment]
Yes, it sets the lang attribute in regional code, so
`<html lang="nl-NL">` or `<html lang="en-GB">`

**Comment by RobJohnston** [comment]
I think you could use the `lang` attribute and the [jQuery.getScript()](https://api.jquery.com/jQuery.getScript/) method to selectively load the required JS files.  There may be better ways... I'll let others give their opinions.

**Comment by daviddebie** [comment]
> I think you could use the `lang` attribute and the [jQuery.getScript()](https://api.jquery.com/jQuery.getScript/) method to selectively load the required JS files. There may be better ways... I'll let others give their opinions.

Thanks for the lang attribute suggestion. I added a condition in the language messages file (localization/messages_nl.js) to only extend validation with the localized messages in case the lang attribute returns "nl-NL", and seems to work properly!
