### ISSUE TITLE
https://jqueryvalidation.org/ 522 Errors for CSS/JS in Chrome & FireFox

### ISSUE THREAD

**Issue by Grimlek** [jquery-validation/jquery-validation#2374]
### Subject of the issue
When navigating to https://jqueryvalidation.org/ Http Status Code 522 errors appear in Chrome & Firefox. 

### Your environment
Note an issue with the plugin itself but the documentation of the plugin, its inaccessible. 
- Windows 10 
Chrome v87
Chrome Incognito v87
FireFox v83

### Steps to reproduce
Navigate to https://jqueryvalidation.org/ in Chrome or Firefox

### Expected behaviour
Webpage should load without any JS or CSS errors

### Actual behaviour
The browser spends a minute loading but eventually displays the web page with 522 errors for CSS/JS within the dev console. The displayed webpage is just the html of the website.

**Comment by staabm** [comment]
It works for me. Do you still see problems?

**Comment by Grimlek** [comment]
Yeah, same problem after retrying. Good to know that its working for you. 

It appears to be isolated to my network or computer. It would be the only site if it is anti virus software or something along those lines.

**Comment by staabm** [comment]
https://downforeveryoneorjustme.com/jqueryvalidation.org?proto=https

:-)
