### ISSUE TITLE
v1.19.3 not available from cdnjs/Cloudflare

### ISSUE THREAD

**Issue by sassquad** [jquery-validation/jquery-validation#2378]
### Subject of the issue

The latest version of the jQuery Validation plugin is *not* available from cdnjs.com, as per the links on the homepage. See steps to reproduce below.

As a result of this issue, I am unable to use the latest version from cdnjs.com, and make use of the SRI hashes at https://cdnjs.com/libraries/jquery-validate

Since v1.19.3 was released in mid-January, and 2 months have passed, this is worth highlighting, particularly as this version addresses a vulnerability.

### Your environment
* v1.19.3
* all browsers

### Steps to reproduce

1. Go to [jQuery Validation homepage](https://jqueryvalidation.org/) 
2. Scroll down page to section 'Latest files on cdnjs CDN (hotlinking welcome):'
3. Click any of the URLs within this section.

### Expected behaviour

You should be able to load v1.19.3 of any of the 4 scripts from cdnjs.com

### Actual behaviour

A 404 error is produced.

**Comment by sassquad** [comment]
I got in touch with one of the maintainers, and was pointed to this [comment](https://github.com/cdnjs/packages/issues/602#issuecomment-787444395). Essentially, until a new version is released, cdnjs won't be able to link to this particular version. In the meantime, hosting the library or using an alternative CDN are the only other options.

**Comment by Welteam** [comment]
Cdnjs does currently deliver 1.19.3 as the latest version

**Comment by staabm** [comment]
Great, so this seems to be fixed. Thanks
