### ISSUE TITLE
Broken links on homepage

### ISSUE THREAD

**Issue by daveh** [jquery-validation/jquery-validation#2383]
### Broken CDN links
[The links](https://jqueryvalidation.org/#latest-files-on-cdnjs-cdn-(hotlinking-welcome):) on the jQuery Validation homepage for the cdnjs Cloudflare CDN are broken.

### Your environment
* version of `jquery-validate`: 1.19.3
* which browser and its version: Chrome latest

### Steps to reproduce

Click on any of the links in this section, for example:
[https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js](https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js)
and it returns a 404.

### Expected behaviour
The link should link to the latest version of the library on that CDN.

### Actual behaviour
A 404 is returned.

**Comment by sassquad** [comment]
@daveh - this is a duplicate of [issue 2378](https://github.com/jquery-validation/jquery-validation/issues/2378). Might be worth closing this one (not that there has been any movement on this)

**Comment by daveh** [comment]
Ah ok @sassquad - thank you for letting me know!
