### ISSUE TITLE
Required validation not enforced at first page load

### ISSUE THREAD

**Issue by lscorcia** [jquery-validation/jquery-validation#2389]
### Subject of the issue

I'm opening this issue to revive #1975 which has been closed as stale, but it's still present as of v1.19.3.

Required error message not showing when:

* Page initially loads with a field that's already filled in
* User clears the field (backspace or del key)
* User tabs to next field -> no error message
* User tabs to previous field -> still no error message
* User fills in something, leaves the field, goes back and empties the field -> now the required error message pops up

### Your environment
* version of `jquery-validate`: 1.19.3
* which browser and its version: Chrome 91, Firefox 89

### Steps to reproduce
http://jsfiddle.net/rvtj8zhL/

### Expected behaviour
Error message should be displayed on first 'empty'

### Actual behaviour
No error message is shown

**Comment by allpassos** [comment]
i'm confirm the issue present as of v1.19.3. and the solution gave by https://github.com/jquery-validation/jquery-validation/issues/1975#issuecomment-360350493 fix my error. i dont know the consequences and ill go throught with care, my app is huge and for now i detect this issue at this point.
In my case the issue occurs when you have the field already validated and then focusout and focusin the input field. I figureout that not only focusout and focusin reproduce the error, also keybords shortcuts. 
If this thread grows , ill still reporting
