### ISSUE TITLE
jqueryvalidation.org is down - full documentation missing from Git?

### ISSUE THREAD

**Issue by zagarskas** [jquery-validation/jquery-validation#2391]
### Subject of the issue
https://jqueryvalidation.org website is down

### Your environment
N/A

### Steps to reproduce
Visit https://jqueryvalidation.org
Note https://github.com/jquery-validation/jquery-validation/tree/master/demo 
contains great examples, alas, the documentation on the ORG site also included great examples such as how to use the data attributes like this: data-rule-required="true" data-msg-required="blah" - ect...

### Expected behavior
The same or text versions of the documentation from jqueryvalidation.org should be represented here within the GIT

Have to dig through the code for examples, which is not too bad, but alas, some very important things are missing, for example, what are the options for type="url", or how can we set up type="date" to be within 2000-2021 instead of range from year 0 to year 999999 (which seems to be the default)

### Actual behavior
Have to dig through the JS file to determine how to set all the options.

**Comment by staabm** [comment]
The website docs are contained in https://github.com/jquery-validation/validation-content

**Comment by staabm** [comment]
> https://jqueryvalidation.org website is down

the website works for me? Is it still down for you?

**Comment by jeffgreendesign** [comment]
Initially jqueryvalidation.org will load o.k. for me but then I start to get Cloudflare 522 (connection timed out) errors.

**Comment by staabm** [comment]
PRs welcome to bring the contents of the docs repo to github pages
