### ISSUE TITLE
jquery free version?  anyone find something suitable/similar that they like?

### ISSUE THREAD

**Issue by morrow95** [jquery-validation/jquery-validation#2394]
Just wondering if anyone has switched from jquery-validation to something else that is jquery free - that they like and does a similar job?  With the newest bootstrap going jquery free most plugins seem to be following suite.  I've done some searching of course and everything I've come across doesn't seem to be maintained, doesn't have a lot of features, etc.  Any information would be appreciated.

**Comment by x753951** [comment]
Yes, I found some, but that library charges, https://formvalidation.io/ , although jQuery is no longer used in bootstrap, I prefer the operation mode of jQuery. It is an excellent encapsulated library,

**Comment by staabm** [comment]
feel free to discuss this further. will close the issue as there is no todo for our lib.
