### ISSUE TITLE
Upgrade from 1.10 to latest

### ISSUE THREAD

**Issue by LingeshK11** [jquery-validation/jquery-validation#2395]
What are the things that need to be check before upgrading from the old version to the current version?
Replacing my old jquery.validate.js file into a new one is that enough or else need some other changes ?
 
Currently am using `v1.10.0` I need to go with `v1.19.3`

**Comment by staabm** [comment]
Have a look at the changelog to grasp what you get: https://github.com/jquery-validation/jquery-validation/blob/master/changelog.md

AFAIR there are not intentional breaking changes in the core.

You should also check whether you are using additional plugins which also need to be updated

**Comment by LingeshK11** [comment]
Hi,
jquery(#id).valid() function return a string value in v1.19.3 is there any way to get it in a boolean type.
