### ISSUE TITLE
Validator does not ignore fields contained in display:none elements

### ISSUE THREAD

**Issue by kakra** [jquery-validation/jquery-validation#240]
According to the HTML spec, browsers a supposed to never send fields of a form that are not displayed (read style="display:none") to the server, browsers should just ignore such fields. The validator should do the same and ignore these fields.

**Comment by steveharrison** [comment]
@kakra Where is that in the spec? I couldn't find anything in [4.10.22.4 Constructing the form data set](https://www.w3.org/TR/html5/forms.html#constructing-form-data-set) checking whether an element is visible or not...

**Comment by kakra** [comment]
@steveharrison Sorry, it's a long time ago, I do not remember where I found it. But given your link, it's probably because a field in a "display:none" context may be implicitly disabled - which promotes it to not being submitted according to your link.

At the time of writing, and that's probably still the case, multiple HTML guide sites also suggest that "display:hidden" fields won't be sent to the server. I always relied on that behavior.
