### ISSUE TITLE
Number Method issue

### ISSUE THREAD

**Issue by Hatead1** [jquery-validation/jquery-validation#2412]
![image](https://user-images.githubusercontent.com/41296890/143138917-351a1e91-e28b-4337-ab52-b8f4937e4630.png)

comma in input, works with 3 digits after comma.

**Comment by eden-jh** [comment]
The screenshot shows the `number` method working correctly. "123,456" _is_ valid because the `number` method allows comma separators in addition to decimals. Can you please clarify how the expected behavior diverged from the actual behavior?

**Comment by Hatead1** [comment]
Look correctly, but 
![image](https://user-images.githubusercontent.com/41296890/144508285-e095013e-a257-4a57-89e9-d37b9fd6ea0c.png)
I was planning to enter a number 123.456, but enter 123,456. I am a regular inexperienced user, what is my mistake? :)

**Comment by Hatead1** [comment]
I think the expected behavior would be to show a warning message about the ambiguous meaning.
