### ISSUE TITLE
Not working on dynamically added elements with name array name="date[]"

### ISSUE THREAD

**Issue by ateequrrahman97** [jquery-validation/jquery-validation#2413]
### Subject of the issue

When we add elements through js. The validator could not apply on it and the form is submitted.
These elements are with the array name like this name="event_date[]".
I have added rules
`'event_date[]': {
                        required: true,
                    },`
### Your environment
* version of `jquery-validate`:
* which browser and its version:

**Comment by nikmauro** [comment]
i have the same problem my fields name is 'item_row[theID][]'
