### ISSUE TITLE
Incorrect date of 1.19.5 release

### ISSUE THREAD

**Issue by ASungailaBA** [jquery-validation/jquery-validation#2432]
Hello.

I was waiting for this **1.19.5** release. Got a notification that it was released today. Yet it seems that release date of version should actually be **2022-07-01**, but in [Releases](https://github.com/jquery-validation/jquery-validation/releases) and [changelog.md](https://github.com/jquery-validation/jquery-validation/blob/master/changelog.md) I find **2022-06-01**.

Is this intentional?

**Comment by bytestream** [comment]
No it was not intentional, thanks for pointing it out!

Updated in https://github.com/jquery-validation/jquery-validation/commit/24f2e277f1cb2c4d0dfcd97ae35997d43136dfbe
