### ISSUE TITLE
Asset  jquery-validation-1.19.5.zip

### ISSUE THREAD

**Issue by ltdeta** [jquery-validation/jquery-validation#2433]
Hello,
why was no build released for version 1.19.5

**Comment by bytestream** [comment]
What do you mean?

**Comment by nebrot** [comment]
See https://github.com/jquery-validation/jquery-validation/releases, this file is missing in list "Assets": https://github.com/jquery-validation/jquery-validation/releases/download/1.19.5/jquery-validation-1.19.5.zip

**Comment by bytestream** [comment]
Thanks for clarifying. I've added it to the GitHub release.
