### ISSUE TITLE
Jquery Validation V1.19.5 : Prev version Fix will be missing in Latest 

### ISSUE THREAD

**Issue by LingeshK11** [jquery-validation/jquery-validation#2437]
## Your environment
* Version of `jquery-validate`: v1.19.5

if maxlength is empty,The maxlength parameter is converted to 0. then I won’t compare maxlength and input value.. 
Fix for the above mentioned issue will be provided in the below link but it will be missing in the Latest Version v1.19.5. 
We have to add the fix manually for every upgrade ?

https://github.com/jquery-validation/jquery-validation/pull/2355/commits/b928fbb82b88ef395a217c911d52ed755102dd55

**Comment by bytestream** [comment]
why is maxlength empty? if you don't want to validate, don't add the rule?

**Comment by LingeshK11** [comment]
In our tool Maxlength property will be added via common component as of now we can't change the existing component change hance raised for a request.. 

https://github.com/jquery-validation/jquery-validation/commit/b928fbb82b88ef395a217c911d52ed755102dd55
Kndly clarify, Above mentioned changeset is a Workaround solution or else a Common change for overall jquery validation.
If it is overall change then i can't find the above mentioned solution in the latest v1.19.5

**Comment by bytestream** [comment]
I think this would change the behaviour of the `maxlength` rule i.e. people may currently expect `max:0` to block input. It's best if you change your code.
