### ISSUE TITLE
Input with no name attribute validated as name undefined

### ISSUE THREAD

**Issue by hongyan6012** [jquery-validation/jquery-validation#2438]
## Your environment
* Version of `jquery-validate`: 1.19.5
* Browser name and version: Edge 103.0.1264.77

## Current behavior

While validating a form which includes multi inputs with `type="number"` and no name attribute, the first number input will be validated and others will be not validated.

## Expected behavior

All inputs with no name attribute should not be validated.
In the function `elements`, it shoud return false if name is undefined.

**Comment by bytestream** [comment]
Please follow the issue template and provide a live demo.
