### ISSUE TITLE
Licensing Missing from NuGet

### ISSUE THREAD

**Issue by 0-0-1-0-1-0-1-0** [jquery-validation/jquery-validation#2440]
## Your environment
* Version of `jquery-validate`:1.19.5

## Current behavior

Packages published to NuGet are missing the licensing property, which should be MIT according to this repository.

My understanding is that the .csproj files are missing a licensing definition as defined in NuGet documentation ([here](https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#package-metadata) and [here](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg)). Example below.

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
</Project>
```

## Expected behavior

I expect the MIT license to be listed on each package listed on NuGet.

## Live demo

1. Navigate to NuGet (any version of any of the packages published by this repository).
    a. Example: https://www.nuget.org/packages/jquery.validation
No license is listed for the package.

## Environment details (development & target environment)
SDK version: 1.19.5
OS: WIndows 10
Framework: .NET 6
Browser(s): Chrome v104
Tooling: Visual Studio 2022
Additional details: This is reproducible from any platform/tooling from what I can tell

## Additional context
I'm working in a space where all third-party dependencies are scanned by a tool called `Sonatype Nexus Lifecycle OSS`. Any packages that are missing licensing are rejected with a critical legal warning. `jquery.validation` was flagged by this system.

**Comment by bytestream** [comment]
It seems to say:
>    NOTE: This package is maintained on behalf of the library owners by the NuGet Community Packages project at https://nugetpackages.codeplex.com/

Seems like it should be reported there
