### ISSUE TITLE
validator with .addMethod custom class on errors makes the inputs colors red for normal methods and green for custom methods

### ISSUE THREAD

**Issue by gethminar** [jquery-validation/jquery-validation#2441]
## Environment
Mozilla Firefox (but also other browsers like Google Crome) and Bootstrap

## Behavior

<b>First thing, tnks to you that you made that. It's a code that anyone has to use doing forms validations.</b>

In custom methods validator with .addMethod makes on errors the inputs colors red for normal methods and green for custom methods. It have to be or red for all, or absent for all

Also, if you edit the inputs, the custom method works when the input is changed (keyup or keydown, I don't know), but the normal method works only on submit. So, sometimes labels are displayed (custom) and sometimes not (normal).

Here my code where is bugging
```
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/additional-methods.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<style>form * { text-align:center; }</style>


<form method="POST" class="needs-validation" id="formAA" novalidate="novalidate">

<div class="mb-3">
  <label for="a" class="form-label">A</label>
  <input type="text" class="form-control form-control-lg text-center" id="a" name="a" maxlength="100" required="">
</div>
<div class="divdropdowncolor mb-3 text-center">
  <label for="selectcolor" class="form-label">B</label><br>
  <input class="form-control form-control-lg" type="color" id="selectcolor" name="selectcolor" value="#0AF000" style="display:inline-block; width:48%; vertical-align: middle; float:left;">
  <input type="text" class="form-control form-control-lg text-center error" id="selectcolorB" name="selectcolorB" placeholder="#FFFFFF" maxlength="7" style="display:inline-block; width:48%; vertical-align: middle; float:right;" col="7" aria-invalid="true">
</div>
<div class="mb-3" style="clear:both;"></div>
<button type="submit" class="btn btn-primary form-control-lg" style="width:100%;">Submit</button>
</form>
<!-- scripts -->
<script>
function isValidColor(str) { return str.match(/^#[a-f0-9]{6}$/i) !== null; }
$(document).ready(function() {
    $('#selectcolorB').val($('#selectcolor').val());
});
$('#selectcolor').on('change', function (event) { $('#selectcolorB').val($('#selectcolor').val()); });
$('#selectcolorB').on('change', function (event) { if( isValidColor($('#selectcolorB').val()) ) { $('#selectcolor').val($('#selectcolorB').val()); } });
</script>

<script>
jQuery.validator.setDefaults({
  debug: true,
  success: "valid"
});

jQuery.validator.addMethod("isvalidhex", function(value, element) {
    return this.optional(element) || value.match(/^#[a-f0-9]{6}$/i) !== null;
}, "Must be a valid hex");

$('#formAA').validate({

  rules: {
    selectcolorB : { isvalidhex : true },
    bgcolor : { isvalidhex : true }
  },
  submitHandler: function(form, e) {
    console.log('The form is valid and would have been submitted successfully');
  }
});
</script>

<script>
(function () {
  'use strict'
  var forms = document.querySelectorAll('.needs-validation')
  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
            //form.classList.remove('was-validated')
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
})()
</script>
```

So listen a time. Here an example of my problem.

If you click over the submit button on the live demo you can see that the errors are recognized (normal and customs)

1) This field is required.
2) Must be a valid hex

In this method for checking hex validity (optional) the `.was-validated` form class generates problems.

There's also a question over [stackoverflow.com](https://stackoverflow.com/questions/73718612/jquery-validator-with-custom-addmethod-over-bootstrap-gives-problems-when-was-v) but none answered.

I wanna underline also that if label is valid generate anyway a space with his height becouse is in `display: inline-block`.
If the label it's valid I think that or you put it in`display:none`, or you delete completally the label withouth show it with `.error.valid` css class

An other little thing.
The elemen id must be unique for each element of the page.
So, when you do
```
.attr( "id", elementID + "-error" )
```
on line n° 968 you place the 

## See this Live demo 
https://jsfiddle.net/qmsjo3L7/

**Comment by bytestream** [comment]
I've replied to your SO - https://stackoverflow.com/a/73749992/2653593

**Comment by gethminar** [comment]
Tnks. I've replyed also @ the same answer [https://stackoverflow.com/a/73749992/2653593](https://stackoverflow.com/a/73749992/2653593) in comments.

Obviusly you're the best answer.

Just an other little thing.

After the $_REQUEST ($_GET or $_POST) the php server gives back the same page, but "input filled" with previous values.

So, after that the error messages are not displayed and the input checkmarks (the V on the right side or the exclamative point) the same.

There's a way (like a function) to restart the validator after the request?

Something like putting a <? if($theformwasnotvalid) { ?><script>revalidatedbyusingthejqueryvalidator();</script><? } ?>

Tnx
