### ISSUE TITLE
Add ability to require at least one of multiple validation methods

### ISSUE THREAD

**Issue by rodrigoaguilera** [jquery-validation/jquery-validation#2457]
## New feature motivation

I have an input that accepts Spanish nie and Spanish nif. Specifiying one of the formats is enough to pass validation.

## New feature description

Have a new "metamethod" that allows for defining this kind of behavior

## New feature implementation

Right now the format for rules "ands" all the rules as far as I know like 
```
  rules: {
    // simple rule, converted to {required:true}
    name: "required",
    // compound rule
    email: {
      required: true,
      email: true
    }
  }
```
The email needs to pass `required` AND `email` methods.

A suggestion on how it could look like in the configuration:
```
  rules: {
    nifcif: {
      oneof: {
        nifES: true,
        nieES: true
      }
    }
  }
```
Maybe there is already a way to define this but I'm not aware of it.

**Comment by rodrigoaguilera** [comment]
My current workaround is to a have a new method like this
```js
jQuery.validator.addMethod( "nifnieES", function( value, element ) {
  "use strict";

  return jQuery.validator.methods.nifES.call(this, value, element) || jQuery.validator.methods.nieES.call(this, value, element);

}, "Please specify a valid NIF/NIE number." );

```

**Comment by rodrigoaguilera** [comment]
If this project is maintained I would like to get a comment on the feature

**Comment by bytestream** [comment]
The suggested workaround is how this should be implemented.

**Comment by rodrigoaguilera** [comment]
Ok. Is it possible to suggest this as an addition to the documentation? I'm sure my future self will face this problem again and will forget how to do it.

**Comment by rodrigoaguilera** [comment]
I proposed the doc changes
https://github.com/jquery-validation/validation-content/pull/57

**Comment by bytestream** [comment]
I'm going to close this now that the PR has been created and linked.
