### ISSUE TITLE
Form not from HTML element

### ISSUE THREAD

**Issue by stbuccia** [jquery-validation/jquery-validation#2464]
## Your environment
* Version of `jquery-validate`:  1.19.5
* Browser name and version: Firefox 110.0

## Current behavior

I am trying to use jQuery validation on a form which is a DOM element created directly in JavaScript, without having it on an HTML page, but every time I call the `valid()` function it returns `true` value, no matter that the form is valid.

## Expected behavior

When calling the `valid()` function, I expect that it behaves as the DOM element is got from HTML form. 

## Live demo

In the example below, I created an invalid form which is considered valid:

[https://jsfiddle.net/yaL4x1fs](https://jsfiddle.net/yaL4x1fs)

**Comment by bytestream** [comment]
I don't think jquery-validate is intended to run on elements which are not present in the DOM. If you add `$('#app').append(form)` it works as intended. If you don't want the form to be visible, then use CSS.

**Comment by stbuccia** [comment]
Ok, thanks for the clarification
