### ISSUE TITLE
NuGet jQuery version dependency incorrect

### ISSUE THREAD

**Issue by austindorsey** [jquery-validation/jquery-validation#2465]
## Your environment
* Version of `jquery-validate`: v1.19.5
* Browser name and version: Chrome 112.0.5615.138

## Current behavior

The jQuery version dependency that NuGet has is `>= 1.4.4` instead of `>= 1.7.2` which is listed in `bower.json`.
https://www.nuget.org/packages/jquery.validation#dependencies-body-tab

Error caused:
`Uncaught TypeError: $(...).on is not a function`

## Expected behavior

jQuery version dependency in NuGet should be at least `>= 1.7` as `$(...).on` was added in jQuery 1.7 - https://api.jquery.com/on/

## Live demo

https://jsbin.com/wofivuheze/edit?html,console,output

**Comment by bytestream** [comment]
I'm not sure what can be done here. https://github.com/jquery-validation/jquery-validation/blob/master/bower.json is correct. Presumably one of the people listed as owners needs to manually correct it.

**Comment by RobJohnston** [comment]
I concur, and I'd add that it's odd to use Nugget for a JavaScript library. The better tool in that case is https://github.com/aspnet/LibraryManager.

**Comment by austindorsey** [comment]
Yeah, I hear you. It's a legacy application and NuGet is what it was using. I was just updating dependencies and everything broke because it didn't update jQuery as well, so thought I would mention it.

**Comment by bytestream** [comment]
Having reviewed some old issues, the nuget package is maintained by a third party so there's nothing we can do. Any issue with nuget should be sent to the nuget package owners using the [Contact Owners](https://www.nuget.org/packages/jQuery.Validation/1.21.0/ContactOwners) link
