### ISSUE TITLE
Validation behaviour

### ISSUE THREAD

**Issue by muling** [jquery-validation/jquery-validation#2466]
## Your environment
* Version of `jquery-validate`:
* Browser name and version:
-- All browsers and versions

## Current behavior

After the first failed attempt of filling out a form, an error message would re-appear while trying to type in valid data. 

## Expected behavior

The error message should only re-appear at end (focus off) of entry if/when the data is invalid.

## Live demo 
https://louise-gancz.nimbusweb.me/share/8577898/zn9kr2f2f282n3xub5e9

**Comment by bytestream** [comment]
@muling please provide a JS Fiddle to demonstrate/replicate the issue.

**Comment by muling** [comment]
https://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html

Can be seen here.
