### ISSUE TITLE
Focus on last focused field causes problems in accessibility

### ISSUE THREAD

**Issue by terohotti** [jquery-validation/jquery-validation#2477]
## New feature motivation

Better accessibility

## New feature description

If there are several required fields, the focus after submit will be on the last focused field, which usually is the last field for keyboard users.

![image](https://github.com/jquery-validation/jquery-validation/assets/4482090/def22e13-983b-4fc3-9bb5-a3fa4d2406bb)

## New feature implementation

Visually impaired people using screen readers and keyboards would be served better if the first empty required field would be focused rather than the last focused field.

**Comment by bugnumber9** [comment]
I could not reproduce this behavior. Probably something else is moving the focus to the last field in your case?
