### ISSUE TITLE
Cannot read properties of undefined (reading 'call').  Exception occurred when checking element , check the 'messages' method

### ISSUE THREAD

**Issue by shumskigorilla** [jquery-validation/jquery-validation#2478]
When having a custom message on some element you will get an error.
This happens when the "command" parameter is undefined so the "messages" rule won't be deleted [here](https://github.com/jquery-validation/jquery-validation/blob/6c5e8525f87c92261154877ad2379c645eeab590/dist/jquery.validate.js#L172)

Better to move "messages" rule deletion back to normalizeRules method as it was in v 1.10

**Comment by bytestream** [comment]
Please follow the issue template and provide steps to replicate.
