### ISSUE TITLE
Remote validation not working in last release

### ISSUE THREAD

**Issue by aloayzab88** [jquery-validation/jquery-validation#2479]
## Your environment
* Version of `jquery-validate`:  1.20.0
* Browser name and version: Chrome, last update

## Current behavior

Remote validation cancels last petition on keyup and fails 
![image](https://github.com/jquery-validation/jquery-validation/assets/5360255/946f61c1-6471-4c4d-8aea-9621b08f2ce2)

## Expected behavior

Remote validation should validate on last entered digit without canceling petition.
![image](https://github.com/jquery-validation/jquery-validation/assets/5360255/5ea805a0-a235-4169-886a-095a1466fa05)

## Live demo 

Can't provide live demo because romote validation is custom made for a bussines

**Comment by bytestream** [comment]
Without a demo we cannot help you.

**Comment by bytestream** [comment]
Sounds related to https://github.com/jquery-validation/jquery-validation/pull/2435

@bidord any ideas?
