### ISSUE TITLE
Using data-rule attributes for validation rules

### ISSUE THREAD

**Issue by sgdowney** [jquery-validation/jquery-validation#2482]
## Your environment
* Version of `jquery-validate`:  current version
* Browser name and version:  

Not so much a bug as a suggestion.

## Current behavior
When using attributes to specify the require_from_groups or skip_or_fill_minimum validations, the attribute names contain underscores.
`data-rule-require_from_groups=`
`data-rule-skip_or_fill_minimum=`
I believe there is a recommendation to avoid using underscores in attribute names and use dashes instead.

## Expected behavior
The suggested attribute names would change to
`data-rule-require-from-groups=`
`data-rule-skip-or-fill-minimum=`

**Comment by bytestream** [comment]
I don't believe this is correct, underscores are permitted. https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

> The attribute name begins with data-. It can contain only letters, numbers, dashes (-), periods (.), colons (:), and underscores (_). Any [ASCII](https://developer.mozilla.org/en-US/docs/Glossary/ASCII) capital letters (A to Z) are converted to lowercase.
