### ISSUE TITLE
File Upload validation breaks with extra characters in name

### ISSUE THREAD

**Issue by aaronrobb** [jquery-validation/jquery-validation#2489]
## Your environment
* Version of `jquery-validate`: 1.19.2
* Browser name and version: Chrome 125.0.6422.142

## Current behavior

When using a simple validation on a file upload, if the file name contains characters like "-" or "&", it shows as invalid, but with no message. It just (for some reason) shows the field's title as the error message.

## Expected behavior

Allow special characters in the file name OR show a message based on file name error.

Here's my base code:

`
                                <div class="css-grid__item css-grid__item--photo">
                                     <div class="file__fake-label">{{ _tt("Photo") }}<span>*</span></div>
                                    {{ formKit.file(htmlKit.svg('upload') ~ _tt("Upload Photo"), {
                                        'name'     : 'garden_photo',
                                        'class'    : 'form__control form__file',
                                    }, {
                                        'rules'    : {
                                            'required' : true
                                        },
                                        'messages' : {
                                            'required' : _tt("Please upload a photo"),
                                        }
                                   }) }}
                                    <label id="photo__name"></label>
                                </div>`

**Comment by bytestream** [comment]
Please can you provide a fiddle which demonstrates the issue.
