### ISSUE TITLE
v1.20.1 not available from cdnjs

### ISSUE THREAD

**Issue by dviry** [jquery-validation/jquery-validation#2491]
Similiar to #2378 but now version 1.20.1 is not available and shows no assets:

https://cdnjs.com/libraries/jquery-validate/1.20.1

**Comment by bytestream** [comment]
Looks like I didn't push the tag and GitHub created it automatically with the release, so it was missing the `dist/` directory which cdnjs looks for. I've recreated the tag + GitHub release so it should get picked up now.

**Comment by dviry** [comment]
FYI it's still empty

**Comment by rhousham** [comment]
Same is for the nuget packages as well https://www.nuget.org/packages/jquery.validation

**Comment by bytestream** [comment]
The files for 1.20.1 are on CDNJS now e.g. https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.1/jquery.validate.min.js. I assume there's some cache issue preventing it from showing any files on https://cdnjs.com/libraries/jquery-validate/1.20.1

I've tagged 1.21.0 so will consider this resolved.
