### ISSUE TITLE
jquery-validation 1.21.0 availability in NuGet package manager.

### ISSUE THREAD

**Issue by sypatil8** [jquery-validation/jquery-validation#2496]
Please let me know when does jquery-validation version 1.21.0 will be available in NuGet.
I am trying to use latest available version in my project (IDE visual studio), but in visual studio NuGet Package manager not listing this 1.21.0 version.  Latest available version in NuGet package manager is 1.20.0.

**Comment by bytestream** [comment]
I don't understand why NuGet has suddenly stopped pulling the latest version. As far as I'm aware, other CDNs are working OK with v1.21.0

**Comment by sypatil8** [comment]
Thank you for the quick response. But any guess about approximate time needed to make it available in Nuget.

**Comment by bytestream** [comment]
Unless I'm mistaken, it's magically appeared? https://www.nuget.org/packages/jquery.validation
