### ISSUE TITLE
Please add a new feature. To set a special HTML error message for a separate field

### ISSUE THREAD

**Issue by korenevskiy** [jquery-validation/jquery-validation#2506]
## Your environment
* Version of `jquery-validate`:
* Browser name and version:

## Current behavior

Please add a new feature.
To set a special HTML error message for a separate field.
Example:
```html
<input reqvired data-validatemessage="This field can have text">
```
```html
<input reqvired id=fld>
<label id="fld-error" for="fld" class="error" style="display:none" >This field can have text</label>
```

**Comment by bytestream** [comment]
That's already possible - many options available.

https://jqueryvalidation.org/reference/#link-error-message-display
https://github.com/jquery-validation/jquery-validation/issues/2170#issuecomment-392618183
