### ISSUE TITLE
Error message "minlength:" can't set with variable

### ISSUE THREAD

**Issue by jobmail** [jquery-validation/jquery-validation#2508]
## Your environment
* Version of `jquery-validate`: 1.19.5
* Browser name and version: firefox 132.0.2

## Current behavior

messages: {
			mod_rscontact_full_name: {
				required: Joomla.JText._('MOD_RSCONTACT_FULL_NAME_ERROR'),
				minlength: Joomla.JText._('MOD_RSCONTACT_MIN_LENGTH_ERROR')
			},
}

## Expected behavior

This one work fine:

messages: {
			mod_rscontact_full_name: {
				required: Joomla.JText._('MOD_RSCONTACT_FULL_NAME_ERROR'),
				minlength: 'At least 2 characters'
			},
}

**Comment by bytestream** [comment]
That would be a problem with Joomla
