### ISSUE TITLE
Email Validation is a fake

### ISSUE THREAD

**Issue by Digital-Pig-LLC** [jquery-validation/jquery-validation#2509]
## Your environment
v1.19.5
Any and all browsers

## Current behavior
Validate email with no TLD passes

## Expected behavior
Validation should fail

## Live demo 
App is still in dev. How the hell can I provide a live demo? Even more dumb!!!

Create a form, add an input with type="email", add a value with a missing TLD, submit it!

ALL browsers are now ignoring invalid email addresses, so I am forced to us a library, what a F joke! But now, when I include your library and test an invalid email address, i.e. one with no TLD, it still passes!
Your documentation states that email field validation is built in, but it is not.

If I pause on the validate method and execute: $('input[type="email"]', form).valid() it returns true! How is an email address anywhere, ever, with a missing TLD valid?

Stop following the herd like a God damn sheep, and let's get back to reality.

**Comment by Digital-Pig-LLC** [comment]
`function clientValidateForm(form) {
    $(form).validate({
        rules: {
            email_address: {
                required: true,
                email: true,
                pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/
            }
        },
        messages: {
            email_address: {
                required: "We need your email address to contact you",
                email: "Your email address must be in the format of name@domain.[com, co, etc]",
                pattern: "Your email address must include a top-level domain"
            }
        }
    });
}`

This!!! If the only email field on the form with the name and id of "email_address" has a value with a missing TLD, how does this pass as valid?

**Comment by RobJohnston** [comment]
It's valid for the same reason that admin@localhost is valid.
