### ISSUE TITLE
Bug with dateITA and daylight saving time

### ISSUE THREAD

**Issue by rcapile** [jquery-validation/jquery-validation#264]
The dateITA does not validade dates when the date it´s the begging of DST.

For example (in Brazil) the Date 16/10/1966 fails.

When you analyze the date, the var gg is set to 16 but `new Date(1966,9,16)` returns `Date {Sat Oct 15 1966 23:00:00 GMT-0300}`.

So when you compare `xdata.getDate() == gg` (at line 143) it fails because gg is 16. 

A workaround I'm using is to change the line 143

``` js
if ( ( xdata.getFullYear() == aaaa ) && ( xdata.getMonth () == mm - 1 ) && ( xdata.getDate() == gg ) )
```

to 

``` js
if ( ( xdata.getUTCFullYear() == aaaa ) && ( xdata.getUTCMonth () == mm - 1 ) && ( xdata.getUTCDate() == gg ) )
```

so the DST is ignored. I admit : I didn´t do a good test with older browsers.

Does it makes sense?

BTW, great plugin!

**Comment by jmastersbrandagency** [comment]
I've found another issue relating to this date validation, and I've found a fix.
v1.13.1 - 10/14/2014

### Problem
We had some customers in New Zealand complaining they couldn't submit the form.
This was reproducible by changing the system timezone on my OSX. 

### Cause
While New Zealand is in daylight savings time their time zone is GMT+13:00.
When javascript processes the "getUTCDate()" it applies -13:00 time change.

This validation function sets the time to 12 noon while parsing, then the -13 hour shift takes the date to the previous day.
Then the if statement "xdata.getUTCDate() === gg" fails and says the date is invalid.

### Solution
Our solution was to changethe date parser in 
src/additional/dateITA.js:29

xdata = new Date(aaaa, mm - 1, gg, 12, 0, 0, 0);
to
xdata = new Date(Date.UTC(aaaa, mm - 1, gg, 12, 0, 0, 0));

I've tested this with several different timezones and it seems to work well.
