### ISSUE TITLE
validating all tabs on form submit

### ISSUE THREAD

**Issue by prithivirajan** [jquery-validation/jquery-validation#279]
Currently validation happens only on the selected tab. But like to have the validation happening for all the tabs on form submit, would be workaround to achieve this?

This is on one single form.

**Comment by alis06922** [comment]
@counsellorben 
 `$.validator.setDefaults({
    ignore: ""
});

this function not working when i am using CKEditor . It shows required even i filled value to the box

**Comment by Umair778** [comment]
In my case it ignore all validation and submit form.
