### ISSUE TITLE
Remote Validation, Submit button missing in POST

### ISSUE THREAD

**Issue by zawmn83** [jquery-validation/jquery-validation#309]
I'm trying with JQuery 1.4.4 and Validation Plugin 1.9, 
When I click Submit button from a page that has remote validation, the submit button is not include in POST fields.
This issue happen only when user click submit button without set cursor or change anything to the field that has remote validation. 

Below is the code that I tested 

``` php
<?php
    var_dump($_POST);
    if(isset( $_POST ['btnupdate'] )) 
    {       
        echo 'POST success';
    }
?>
<html>
<head>
<script language="javascript" src="javascript/jquery.js"></script>
<script language="javascript" src="javascript/jquery.validate.min.js"></script>     
<script language="javascript">

    jQuery(document).ready(function() 
    {       
        jQuery("#frmeditfriend").validate({
            'rules':{
                'txtemail':{'remote':'friend_exec.php'}
            },
            'messages': {
                'txtemail':{'remote':'Email already existed'}
            }
        });
    });
</script>
</head>
<body>
    <form method="post" id="frmeditfriend" name="frmeditfriend">
        <label>Email :</label>
        <input type="text" value="test@gmail.com" id="txtemail" name="txtemail" />
        <p>
            <input type="submit" id="btnupdate" name="btnupdate" value=" Update " />
        </p>
    </form>
</body>
</html>
```

In the friend_exec.php, for testing I put below code 

``` php
<?php
    echo 'true';
?>
```

**Comment by abrookbanks** [comment]
Upgrading to the jQuery Validation Plugin v1.13.1 didn't fix this for me.

My solution was simple assuming the server side script looked for ```$_POST['submit']``` which was the name of my submit field. Just create a hidden field with same name when the submit button is clicked and write it into your form. The server side (PHP in my case) can use this instead.

```$('#submit_button').click(function () {
        $('<input>').attr({
                        type: 'hidden',
                        name: 'proceed',
                        value: '1'
                    }).appendTo('form');
    });```

**Comment by MilanRaval** [comment]
abrookbanks, your work around worked for me thanks  !

**Comment by abrookbanks** [comment]
@milanraval pleased it helped someone
