### ISSUE TITLE
depency-mismatch

### ISSUE THREAD

**Issue by davidsielert** [jquery-validation/jquery-validation#37]
In a form with the rule set all set in json rules option, I have an input that is optional with no record in rules but has a maxLength='45', the plugin seems to pick this up and add a rule for it, which is fine but .valid() returns 0 (invalid) on the element.

**Comment by KzooDrew** [comment]
I am getting the same "dependency-mismatch" issue when validating a text input with the following rule:
          'myInput': {
                required: false,
                maxlength: 11,
                phone: true
            }

The custom rule definition for phone:
jQuery.validator.addMethod("phone", function (value, element) {
    console.log('phone optional?', this.optional(element)); 
    // when the input is empty, this.optional(element)) returns "dependency-mismatch" which is not === true
    if (this.optional(element) === true) {
        return true;
    }
    // .. rule definition removed, it's irrelevant to the issue 
}
