### ISSUE TITLE
Thousands separators allowed for numbers, but not min/max

### ISSUE THREAD

**Issue by adammessinger** [jquery-validation/jquery-validation#379]
While trying to validate a number field with min and max attributes, I noticed that there was no invalid number complaint for something like "9,000" but that adding commas would cause the value to incorrectly fail min/max validation.

**Comment by piersh** [comment]
this is a joke. both issues #188 and #379 which have been unfixed for years are closed referring to each other as reasons for closing. yet this fix STILL has not made it into release.

**Comment by joeRinehart** [comment]
+1 to the above. This is a joke. Implement the common case (whichever international format is preferred for the library's authors) and give developers a way to extend/change it.

**Comment by joeRinehart** [comment]
In case anyone hits this and needs a quick, U.S.-but-customizable fix, I already had numeral.js involved and using it to preformat values was a pinch:

https://gist.github.com/joeRinehart/0e8af523fdfc567cc670ddca2eaff137
