### ISSUE TITLE
Javascript error at the staticRules method while validating form in IE

### ISSUE THREAD

**Issue by ruado1987** [jquery-validation/jquery-validation#401]
I have encountered a JavaScript error because this very line: var validator = $.data(element.form, 'validator');  in the staticRules method. Somehow it sometimes returns null, thereby resulting in error when executing the next line. This problem only occurs in IE, including IE 6,7,8. I am using jquery validation 1.9 with jquery 1.7.1

**Comment by afilina** [comment]
@prgwiz Thanks for the tip. This actually didn't work for me for some reason, so I used this variation instead:
```
staticRules: function( element ) {
    var rules = {};
    var validator = $.data(element.form, "validator");
    if ( validator && validator.settings.rules ) {
      rules = $.validator.normalizeRule(validator.settings.rules[element.name]) || {};
    }
    return rules;
},
```
If anyone can tell me why validator is sometimes null despite having element.form, that will be great.

**Comment by staabm** [comment]
@afilina could you provide a simplified jsfiddle which demonstrates a situation in which it doesnt work?

**Comment by afilina** [comment]
@staabm Well someone is deleting my comments, so no, I won't spend hours putting up a jsfiddle. I'll just hack the core myself and use it in my legacy projects.

**Comment by staabm** [comment]
> Well someone is deleting my comments

hmm? I can believe that someone intentionally deletes comments in this tracker..

> I'll just hack the core myself and use it in my legacy projects.

feel free to PR your changes, so we have can discuss something.

**Comment by samuelsethhildebrand** [comment]
staticRules: function( element ) {
		var rules = {};
		
		if (!element.form)
		{ validator = $(element).parents('form').data('validator');
		}
		else
		{ validator = $.data( element.form, "validator" );
		}
		
		if ( validator.settings.rules ) {
			rules = $.validator.normalizeRule( validator.settings.rules[ element.name ] ) || {};
		}
		
		return rules;
	},

**Comment by samuelsethhildebrand** [comment]
I updated my post to include more background on my changes.
