### ISSUE TITLE
Remote and depends bug

### ISSUE THREAD

**Issue by devantoine** [jquery-validation/jquery-validation#431]
When you try to remote with depends, the AJAX's parameters are not taken.
The simple test case below illustrates it:

``` javascript
$('#field').rules('add', {
  required: true,
  remote: {
    depends: function(el) {
      return $(el).val() != loginValue;
    },
    url: 'myurl',
    type: 'POST'
  },
  messages: {
    remote: "fail"
  }
});
```

The call is made via GET to the page's url, not in POST to 'myurl'.

**Comment by UniFreak** [comment]
Solved my headache. Thank you :)

**Comment by jackDing2016** [comment]
Works!

**Comment by arya-choudhury** [comment]
Thank you @shakerlxxv it helped me a lot

**Comment by maheshd1991** [comment]
param data: attribute will not dynamically set. it will set only while when document is ready.
