### ISSUE TITLE
Conflict between validate and jeditable plugins: "Cannot read property 'settings' of undefined" 

### ISSUE THREAD

**Issue by tttp** [jquery-validation/jquery-validation#476]
If you have an editable element under a validate form, you get an error.

``` html
<form id="form">
...
<div id="editable">Edit in place</div>
</form>

<script>
$(function(){
  $('#form').validate();
  $('#editable').editable('http://www.example.org/save');
});
```

When clicking on the editable, it generates a form+input field and the validation plugin attaches to this field.
In the delegate method, which does not check if the form has a validator before applying it.

The fix seems to be trivial, add a test 

  if (!validator) return;

Will clone+pull request

**Comment by achirkof** [comment]
Here is the solution for conflict between editable and jquery validate https://github.com/vitalets/x-editable/issues/384#issuecomment-25744788
for error
Uncaught TypeError: Cannot read property 'settings' of undefined

**Comment by thorne51** [comment]
@achirkof There still seems to be some issues here. See my comment [here](https://github.com/vitalets/x-editable/issues/384#issuecomment-25744788)

**Comment by brezuicabogdan** [comment]
Worked for me. Thank you @thorne51
