### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by jzaefferer** [jquery-validation/jquery-validation#502]
- Drop GPL license
- Fix build: Clean dist dir, drop double header from additional-methods.js, only put min files into dist folder inside zip, keep the normal files were they were.
- Get rid of todo file, create issues for anything still valid

**Comment by jacobq** [comment]
I see that the README.md files states that the license is MIT, but I don't see a copy of the license terms (i.e. LICENSE.txt) or a link to it (i.e. http://opensource.org/licenses/MIT). Would you mind adding this? It would make my life better as I need to get approval from my employer's legal/compliance department for each library that I use, and they are rather particular about details like this.
