### ISSUE TITLE
Dynamic forms example doesn't work: JS error on .delegate() call for versions > 1.5.5?

### ISSUE THREAD

**Issue by KingCode** [jquery-validation/jquery-validation#51]
I am trying to use the latest version but get '$("#orderform").delegate is not a function ' error from line 46 of dynamic-totals.html. All recent versions' demos are buggy for this example. The only version which does work is 1.5.5

**Comment by adamongithub** [comment]
It seems to be broken again:

dynamic-totals.html:45 Uncaught TypeError: $(...).validateDelegate is not a function

**Comment by Arkni** [comment]
@adamongithub 

`validateDelegate()` has been removed in `v1.14.0` (this commit to be accurate 747890974caecf0a339f38963a239c3a2f4eb864) and replaced with `.on(...)` which is only available in `jQuery 1.7+`

The demo file need to be changed in order to reflect the changes.
