### ISSUE TITLE
remote validation prevents submit

### ISSUE THREAD

**Issue by ghost** [jquery-validation/jquery-validation#58]
When I enter something valid in a remote validation field, then immediately click on the submit button without hitting tab, the form does not submit. I have to click submit again!

This happens in Firefox 3.0 and 3.6 and in Chrome but not in IE 8.

I think there is some sort of race condition involving validator.pendingRequest but I'm not sure.

To recreate, try this contact form:
http://www.simplyvoting.com/website.php?mode=contact
Enter x as subject and as message
Then enter a valid email (remotely validated).
Click submit.
Nothing happens, click submit again!

**Comment by Rathilesh** [comment]
above code fixed my issue
 `
remote: {
                                    url: "http:url.com",
                                    type: "post",
                                    data: { USER_ID: userid },
                                    async: false,                        // set async  = false
                                 }
`

**Comment by ssantamariaparra** [comment]
Great, the 'async: false' setting solved the problem

**Comment by Rani-Kheir** [comment]
My issue had a different solution, the remote address was returning `{ "valid" = "something-else-other-than-true-or-false" }` and that lead to weird behavior.

The field was green (that gave it the impression that it was good) but the form wasn't submitting.

So if everything above doesn't work, try confirming that you're getting either true or false in the JSON returned from the remote address.

**Comment by Tyler-Petrov** [comment]
> below code fixed my issue
> `remote: { url: "http:url.com", type: "post", data: { USER_ID: userid }, async: false, // set async = false }`

This fixed my problem too.  Thank you so much!
