### ISSUE TITLE
ASP.NET MVC Range data annotation no longer works with jquery-validation 1.11.0

### ISSUE THREAD

**Issue by leniel** [jquery-validation/jquery-validation#626]
Hi,

I have this property:

``` C#
[Range(typeof(int), "0", "150")]
[Display(Name = "Age", ResourceType = typeof(Localization))]
public int PatientAge { get; set; }
```

With jquery-validation 1.10.0 everything works OK. Now with 1.11.0, no matter if I enter a valid value like 10, 15, 20, etc..., it barks at me telling that the value must be between 0 and 150.

Here's the HTML code generated:

``` HTML
<div class="controls">
    <input type="text" name="PatientAge" id="PatientAge" data-val-required="Idade é obrigatório" data-val-range-min="0" data-val-range-max="150" data-val-range="Idade deve estar entre 0 e 150." data-val-number="O campo Idade deve ser um número." data-val="true" class="input-mini input-validation-error" value="">
    <span data-valmsg-replace="true" data-valmsg-for="PatientAge" class="help-inline field-validation-error">
        <span for="PatientAge" class="">Idade deve estar entre 0 e 150.</span>
    </span>
</div>
```

I think this is happening because jquery.validate.unobtrusive.js provided by Microsoft needs to be updated to match this new version of jquery-validation. Anyways I'll revert to v. 1.10.0 for now.

**Comment by weitzhandler** [comment]
Still experiencing the issue.
I'm using *DataAnnotations*' `[Range(typeof(DateTime), "01/01/1915", "01/01/2035")]`, which wouldn't let the validation pass under any condition.

Here's the rendered element:

    <input class="form-control text-box single-line input-validation-error" data-val="true" data-val-date="The field BirthDate must be a date." data-val-range="The field BirthDate must be between 01/01/1915 12:00:00 AM and 01/01/2035 12:00:00 AM." data-val-range-max="01/01/2035 00:00:00" data-val-range-min="01/01/1915 00:00:00" data-val-required="The BirthDate field is required." id="BirthDate" name="BirthDate" type="date" value="" aria-required="true" aria-invalid="true" aria-describedby="BirthDate-error">

**Comment by 8enSmith** [comment]
I too get the same issue as @weitzhandler with DataAnnotations and I'm using jQuery validation 1.14.

Did anyone find a resolution to this problem?

**Comment by dominicrooijackers** [comment]
I'm also having the same error, I saw that the documentation on .net core said that Range for DateTime doesn't work, but it didn't say anything about ASP.NET 4.5.1
