### ISSUE TITLE
resetForm should call unhighlight

### ISSUE THREAD

**Issue by filipiz** [jquery-validation/jquery-validation#65]
Guys, dont you think the reset form should call the unhighlight method for each element?

Instead of

``` js
this.elements().removeClass( this.settings.errorClass ); // on line 381
```

do

``` js
var elements = this.elements();
for (var i = 0; i &lt; elements.length; i++){
    this.settings.unhighlight.call( this, elements[i], this.settings.errorClass, this.settings.validClass);
}
```

Please comment if i undestood wrong the usage of highlight and unhighlight.

**Comment by binarweb** [comment]
This issue should not be closed as this problem still persists in latest version (1.19.1).
As it is now, I have to manually remove every error added by "highlight" method.

**Comment by masuraoru** [comment]
> This issue should not be closed as this problem still persists in latest version (1.19.1).
> As it is now, I have to manually remove every error added by "highlight" method after I'm calling "resetForm".

May be it will help someone.
I faced the same problem when I was trying to use resetForm() while hiding the bootstrap modal (on 'hidden.bs.modal' event). But then I realized that problem was because the form elements were hidden. Changing event to 'hide.bs.modal' fixed the issue.
