### ISSUE TITLE
Don't prevent form submit when using a submitHander

### ISSUE THREAD

**Issue by obecker** [jquery-validation/jquery-validation#650]
If I add a `submitHandler` in the options of the plugin the default form submit is cancelled.
This means I can't use the submitHandler to do some additional logic and then fallback to the default behaviour. IMHO it would be better to use the return value as in the normal jQuery form submit event handler.

Line 68 in the current code would become

``` js
var result = validator.settings.submitHandler.call( validator, validator.currentForm, event );
```

and line 73

``` js
return result;
```

(instead of return false)

**Comment by pensierinmusica** [comment]
Hi @jzaefferer, I'm using the jQuery Validation plugin with a custom `submitHandler` property. Unfortunately though I can't manage to stop the default form submit, even returning `false` in the handler.

Let's take this code example:

```js
submitHandler: function (form) {
  alert('stop');
  return false;
}
```

It alerts "stop", but then submits the form anyways. Do you have any idea how to fix this?

Thanks!
