### ISSUE TITLE
Email Validation Allows Non-Breaking Space at the end of an Email

### ISSUE THREAD

**Issue by Tiestarian** [jquery-validation/jquery-validation#655]
The email validation allows a non-breaking space character at the end of an email address. This should not be allowed (a normal space at the end of an email is marked as invalid).

Can be tested here: http://jsfiddle.net/VzdV8/

To test this:
- Type an email into the input box, then press the space bar. Press validate. This will display a message that the email address is invalid. This is correct functionality. 
- Type an email address again, then press Alt+255 on Windows, or cmd+space on Mac. This will be accepted as valid and won't show an error. This is incorrect. Alt+255 or cmd+space is a non-breaking space.

**Comment by JamoCA** [comment]
I recently started using the following solution to trim input fields and skip fields w/class "noTrim".
https://github.com/jzaefferer/jquery-validation/issues/1354#issuecomment-257599334

**Comment by staabm** [comment]
recently we added a normalizer feature: https://jqueryvalidation.org/normalizer/
