### ISSUE TITLE
Make custom errors simple and more powerful

### ISSUE THREAD

**Issue by jzaefferer** [jquery-validation/jquery-validation#657]
There are a bunch of options related to customizing error messages, resulting in too much complexity, but still not enough flexibility. Need to come up with a better API that gives more control when needed, with less API surface.

See also #493 for an attempt at adding even more complexity to give more control over the markup.

See also #582 for an attempt at providing highlight/unhighlight callbacks for each rule

See #692 for an attempt at providing callbacks for showing pending status of the remote method. There should be events or something similar to make that possible without another option.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by devpratik** [comment]
fgf
