### ISSUE TITLE
Try to remove name attribute requirement

### ISSUE THREAD

**Issue by jzaefferer** [jquery-validation/jquery-validation#659]
I can't tell anymore why the name attribute requirement is there in the first place. Need to figure that out or just drop it, with whatever consequences that has.

Motivation:
- Rules and messages can be configured inline, so no need to reference elements by name
- Having multiple elements with the same name comes up every once in a while, ala `address[]`. Explicit indices usually work (`address[0]`, `address[1]` etc), but are less convenient.

See also #654 for a bad workaround.

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by MisinformedDNA** [comment]
Wow. So you want to give the false impression that you are actually solving problems? Sad.

This issue has been brought up so many times as seen above and the repro is clear and you just close it out again. It just further fragments the discussion of the issue.

**Comment by chrishaines** [comment]
Perhaps this could be solved by supporting an optional html5 data attribute (maybe ```data-validator-name```).  It could then fallback to the name if it does not exist. Instead of referencing element.name directly, it could use a method like so.

```javascript
getName: function(element) {
    return $(element).data('validator-name') || element.name;
}
```
and we can refactor finding by name as such:
```javascript
findByName: function( name ) {
    var escaped = this.escapeCssMeta( name );
    return $( this.currentForm ).find( "[data-validator-name=" + escaped + "], [name='" + escaped + "']" );
}
````

**Comment by staabm** [comment]
@chrishaines changing one attribute for another doesnt make much difference?

I understood the ticket as getting rid of the name attribute completly, if possible.

**Comment by chrishaines** [comment]
@staabm it maintains backwards compatibility and allows you to use the ```rules``` option for ```validate()```. It would also require minimum refactoring.

**Comment by Overbryd** [comment]
I would like to subscribe to the issue, and I am wondering why the solution proposed in https://github.com/jzaefferer/jquery-validation/pull/1648 was not merged in.

I found it very good, as in maintaining backward compatibility and being nice to users who don't supply a name attribute.

Again, it should be quite common not to supply the name attribute. Best example is credit card forms where some preprocessing is taking place and you want to make sure no browser ever sends these inputs to your server.
