### ISSUE TITLE
Problem validate plugin in IE 10

### ISSUE THREAD

**Issue by barbmc** [jquery-validation/jquery-validation#709]
Using IE 10, jquery 1.9.1 and version 1.11 of your validate plugin i see this error

![Screenshot_1](https://f.cloud.github.com/assets/2469630/307340/4ba05dd2-96be-11e2-8631-7f422dcb531d.jpg)

If I don't include the validate plugin I don't get the error

**Comment by AmaliDeveloper** [comment]
You get the solution in this tutorial [Link](https://youtu.be/pCpXG52LNEY)
