### ISSUE TITLE
url validator: hosts without a dot are not considered valid

### ISSUE THREAD

**Issue by severin** [jquery-validation/jquery-validation#787]
Hello there,

I just noticed that the url validator does not consider `"http://localhost/"` as valid url, which it is, however.  In general, urls with hosts without a dot are not considered valid even though they should be.

Thanks for looking into it.

**Comment by kjkrum** [comment]
Whatever the rationale is either way, perhaps URL validation should be consistent with email validation, which does _not_ require a TLD.

**Comment by staabm** [comment]
Email validation is based on the recommendation of the w3c.

As we have a url2 which has a optional tld I dont see why we should change something, which would also introduce a BC break, or at least violate assumptions regarding the url format
