### ISSUE TITLE
Validation v1.11.1 not working on IE8

### ISSUE THREAD

**Issue by cstipkovic** [jquery-validation/jquery-validation#795]
I was using the validation v1.11.1 (https://github.com/jzaefferer/jquery-validation/tree/1.11.1) in my project but when I tested at IE8, the submitHandler function runs ok but it doesn't validate the fields then, the form submit is executed.

Also, using the v1.11.0 (https://github.com/jzaefferer/jquery-validation/tree/1.11.0), the form is correctly validated at IE8.

**Comment by rgjain** [comment]
@cstipkovic , Thanks for raising this issue. I was able to resolve my long going problem. I was struggling from past 2 days.
