### ISSUE TITLE
Changes on hidden fields not beeing re-validated

### ISSUE THREAD

**Issue by mediafreakch** [jquery-validation/jquery-validation#802]
Some fancy jQuery plugins (e.g. slider) use hidden form input fields to set & submit values to server-side). If you want to validate them too, you can simply set `.setDefaults({ ignore: "" })` . It will then be validated and error messages will be shown. However, the plugin does not bind any event listeners to the invalid hidden input fields to track the changes there. 

Desired behaviour: The plugin should register an `onChange` event listener on every input field that hasn't been set to be ignored via `.setDefaults({ ignore: ""})` option once the form submit event has been triggered. Like it registers `onfocusout`, etc., event listeners for other input fields.

**Comment by mhetreramesh** [comment]
+1 for this

**Comment by 3zzy** [comment]
+1

**Comment by giacomodeglinnocenti** [comment]
+1
