### ISSUE TITLE
min="0" does not prohibit negative numbers in v1.11.1

### ISSUE THREAD

**Issue by bridgeland** [jquery-validation/jquery-validation#854]
In v1.11.1, validation seems to work fine with min="1" and min="-1", but not with min="0". Consider this fiddle http://jsfiddle.net/MgvRn/1/   It appropriately objects to a value of -5 in the first input element and in the third, but accepts a -5 in the second one, where min="0". 

![image](https://f.cloud.github.com/assets/5245697/976360/4cc4d4bc-068b-11e3-83f6-1f2db13ab715.png)

Now consider the same code in v1.10 http://jsfiddle.net/mblase75/MgvRn/  Works fine.

**Comment by bpromasmb** [comment]
This bug seems to be back...

**Comment by staabm** [comment]
could you provide a jsfiddle which reproduces it?

**Comment by bpromasmb** [comment]
Apologies. I was using an older version of the plugin. Will remove comments.
