### ISSUE TITLE
PhoneUS fails for phone numbers that include the number 1

### ISSUE THREAD

**Issue by JCOvergaar** [jquery-validation/jquery-validation#856]
I'm not sure how on earth this was coded or has been out there so long, but valid US phone numbers can use all 10 digits. The regex provided in additional-methods.js considers this perfectly good phone number to be invalid: 269-111-1111

The regex as it stands:
phone_number.match(/^(+?1-?)?(([2-9]\d{2})|[2-9]\d{2})-?[2-9]\d{2}-?\d{4}$/);

My change to it in my local code:
phone_number.match(/^(+?1-?)?(([0-9]\d{2})|[0-9]\d{2})-?[0-9]\d{2}-?\d{4}$/);

**Comment by vtrend** [comment]
The regex in additional-methods.js fails for: 866-411-4321 (which is a valid number)

http://jsbin.com/pujaniyuzu/edit?html,output

(https://en.wikipedia.org/wiki/NANPA#Numbering_system)
The Numbering System reads: "in geographic area codes the third digit of the exchange cannot be 1 if the second digit is also 1".

However, 866 is a toll-free number; the geographic area code rule does not apply.

(https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes#800.E2.80.93899)

**Comment by jzaefferer** [comment]
@vtrend thank you for the report, but commenting on closed issues won't accomplish anything. Please file a new issue or, even better, create a pull request that adds tests and fixes the issue.
