### ISSUE TITLE
I think it may be a bug

### ISSUE THREAD

**Issue by shenglingshi** [jquery-validation/jquery-validation#942]
I use jquery 1.9 and I write code like:

``` js
 $("#test").rules("add", {
                required: true,
                minlength: 2,
                messages: {
                    required: "Required input",
                    minlength: jQuery.format("Please, at least {0} characters are necessary")
                }
            });
```

but the firefox console report a error:
TypeError: $.data(...) is undefined
js code is wrong:---->var settings = $.data(element.form, "validator").settings?

**Comment by wangshihui** [comment]
Hi
I get the same error.Because i use rules in a form element.
but the rule method can only be used as a method of  an element in a form
