### ISSUE TITLE
Remote validation and array in data

### ISSUE THREAD

**Issue by pebrian27** [jquery-validation/jquery-validation#954]
In remote validation, array data properties are not serialized properly.

JSFiddle link http://jsfiddle.net/kAxA9/

Steps to reproduce

1) Add a multi select element 
<select multiple>

2) Setup a remote validation and add the select element as an additional data

``` js
$( "#myform" ).validate({
  rules: {
    email: {
      required: true,
      email: true,
      remote: {
        url: "check-email.php",
        type: "post",
        data: {
          usernames: function() {
            return $( "#multiselect" ).val();
          }
        }
      }
    }
  }
});
```

3) select multiple items

Observation: remote validation generates the query string as ?usernames=1,2 instead of ?usernames=1&usernames=2

Fix:

JQuery.Ajax data doesn't accept functions so the functions in the data property must be executed 

``` js
var ajaxOptions = $.extend(true, {
    url: param,
    mode: "abort",
    port: "validate" + element.name,
    dataType: "json",
    data: data,
    success: function (response) {
        ...
    }
}, param);

//we are not supposed to pass functions to the data parameter
//Fix the bug by capturing the function output so array values are
//serialized properly
$.each(ajaxOptions.data, function (key, value) {
    if ($.isFunction(value)) {
        ajaxOptions.data[key] = value();
    }
});

$.ajax(ajaxOptions)
```

**Comment by alexandis** [comment]
Why this is closed? It's 2016 and I still have the same problem trying to use jquery validation remote method. I don't know how to pass array - it's being flattened to comma-separated values within string.
