### ISSUE TITLE
Remote validation causes double submit

### ISSUE THREAD

**Issue by stijnherreman** [jquery-validation/jquery-validation#956]
Crosspost from http://stackoverflow.com/questions/20519666/remote-validation-causes-double-submit

I have a problem with remote validation causing a form to submit twice (and enter the success/error handler twice). The original is an ASP.NET MVC application with unobtrusive validation and jQuery Form for AJAX submitting, but I've been able to reduce to the following:

**remote.json**

> "true"

**test.html**

```
<!doctype html>
<title>test</title>

<form action="" method="post">
    <input name="foo" type="text" value="foo">
    <br>
    <input name="bar" type="text" value="bar">
    <br>
    <input type="submit">
</form>

<script src="//code.jquery.com/jquery-2.0.3.js"></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>

<script>
    $("form").validate(
    {
        rules:
        {
            foo: { remote: { url: "remote.json" } },
            bar: { required: true }
        }
    });

    $("form").on("submit", function ()
    {
        console.log("entering the submit handler");

        if ($(this).valid())
        {
            console.log("form is valid");
        }
        else
        {
            console.log("form is invalid");
        }

        return false;
    });
</script>
```

When the remote validation returns `"true"`, this is the console output:

> GET `http://localhost/validation/remote.json?foo=foo` 200 OK  
> entering the submit handler  
> form is valid  
> entering the submit handler  
> form is valid

When the remote validation returns `"false"`, this is the console output:

> GET `http://localhost/validation/remote.json?foo=foo` 200 OK  
> entering the submit handler  
> form is valid

Am I doing something wrong in my submit handler? It works fine for all other forms (dozens of them). Or is this yet another bug in the library (if so, is there a workaround)?

**Comment by grammophone** [comment]
I confirm the issue, it still holds today.

**Comment by staabm** [comment]
please open a new issue with a jsfiddle or jsbin attached which reproduces your problem.

**Comment by molihub** [comment]
I am using 1.17.0 and I confirm the issue, it still holds today.
I will open a new issue in my free time.

**Comment by burakt91** [comment]
I can confirm that this double submit issue is still happening. I created a Codesandbox.io demo [here](https://codesandbox.io/s/jquery-validation-double-submit-forked-rk15u?file=/index.html). Can you please explain why it's submitting the form twice? It's only happening when using the Remote rule.
