### ISSUE TITLE
valid() function is always returning true

### ISSUE THREAD

**Issue by paragredkar** [jquery-validation/jquery-validation#965]
``` js
jQuery('#btn_submit').on("click",function(){

if( jQuery("#formid").valid()==false){
return false
}
else{
console.log('do further ajax operation')
}

)}
```

``` html
< form id="formid" name="formid" >
< input id="txt_name" name="txt_name" type="text" placeholder="Enter first name"  />
< input id="txt_lastname" name="txt_lastname" type="text" placeholder="Enter last name"  />
< button class="btn ctrl-btn" id="btn_submit">Submit< /button>
< /form>

```

``` js
jQuery('#formid').validate({

        rules : {
            'txt_name' : { required  : true     },           
            'txt_lastname' : {      required  : true } 
        },      
        messages : {
            'txt_name' : {  required  : " Please enter first name"      },
             'txt_lastname' : {required  : " Please enter last name"            } 
        },

        highlight: function(element) { 

        },
        success: function(element) {

        },
        submitHandler : function(form){ 
            return false; 

        }
    });

```

 jQuery("#formid").valid() is always returning true in internet explorer 9, whether field is empty or not.
works well on ie10,11, mozilla, chrome

this form is previously hidden, may be because of that required field validation is not working? 
solutions tried:a) I tried putting  ignore:''    , ignore:[] . but no luck. Ie9 required field validation issue still there. 
b) loaded form without making it hidden. 

still required validation didnt work in ie9

NOTE: but it shows up email type errors and other  custom validator errors sucessfully.  if i try to  implement email and custom validators on the same form.

I am using jquery version 1.8.3 
I tried using jquery validaion plugin versions 1.9,    1.10,  1.11,    1.11

**Comment by abhishekgauravsrivastava** [comment]
I have a form and into this form, I have Jquery-tabs . In my ViewModel, I added the data annotations for each item...

My problem is: when the submit button is hit, the validation occours normally on the active tab, but in the other tabs (that are hidden), the validation seems not working... it only work if i switch to that tab and try to submit the form again, than that tab will be validated.

How can i get the data annotations to work on hidden tabs the same way they do in the active tab?

**Comment by staabm** [comment]
@abhishekgauravsrivastava by default hidden input fields are ignored, see https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L235
